### ISSUE TITLE
Issue with main menu

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#100]
When you resize the window the background disappears
![Screenshot 2023-08-26 064621](https://github.com/fgsfdsfgs/perfect_dark/assets/115612060/0321711c-2170-40f0-b9bb-b49591af3b7e)

**Comment by ghost** [comment]
Is this a non issue? I also noticed the filtering for the background doesn't seem to look correct on it either (looks smoother on my real n64)

**Comment by fgsfdsfgs** [comment]
The "blur" is done differently in the port so it doesn't look as smooth, will maybe fix that in the future, but it's pretty low priority.
The resizing thing is definitely a bug though. I've noticed it before, but I'm not sure why it happens yet.

**Comment by ghost** [comment]
Changing the window's vertical aspect causes framebuffer elements to disappear. It seems to stretch properly when changed horizontally which is strange.

**Comment by ghost** [comment]
Ah okay, i had a feeling the blur was done differently but I wasn't too sure. Good to know that it disappearing is actually a bug too, i'm not very experienced with testing software. Also interesting that it's not just the main menu that has the issue

**Comment by iamgreaser** [comment]
If your GPU driver doesn't properly clear VRAM before use (e.g. radeonsi), you can also occasionally get garbage when resizing:
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/138113/4d12cc1e-01ea-47c4-a2a0-c06b2157845f)

EDIT: Resizing *only* the width doesn't affect it. But the moment the height changes, it ends up losing its texture data in some way.

**Comment by fgsfdsfgs** [comment]
Ah, this is because all framebuffer textures get nuked in the renderer whenever the height changes. I'll have to update the blur texture every time this happens I suppose.
