### ISSUE TITLE
first time setup, no data files

### ISSUE THREAD

**Issue by TuskFGT** [fgsfdsfgs/perfect_dark#105]
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/104387649/c39af73f-5910-4ead-9494-37060f47b3db)

same issue as this guy:
https://gamefaqs.gamespot.com/boards/198275-perfect-dark/45664962#:~:text=This%20is%20a%20common%20problem,able%20to%20save%20like%20normal.

**Comment by fgsfdsfgs** [comment]
Sounds like the EEPROM file didn't create or something. Is there a `eeprom.bin` next to `pd.exe`?

**Comment by fgsfdsfgs** [comment]
This shouldn't cause issues now, but you still won't be able to save if the game can't write to the current working directory.

**Comment by TuskFGT** [comment]
im running it from a shortcut in program files x86 if that helps

**Comment by fgsfdsfgs** [comment]
Yeah, it does. Either move it somewhere else where you have write access (e.g. `C:\Games`, your documents folder, etc) or run it as admin.

**Comment by fgsfdsfgs** [comment]
This has been resolved now that the game can save to AppData/$HOME if it can't write to the working directory.
