### ISSUE TITLE
Nonfunctional on SteamOS Holo

### ISSUE THREAD

**Issue by TuskFGT** [fgsfdsfgs/perfect_dark#106]
linux version does not launch in desktop mode
windows version does not launch through proton

**Comment by megatog615** [comment]
The workaround is to add it to Steam as a non-Steam game and, in the properties dialog, force the Steam Linux Runtime in the compatibility tab.

**Comment by TuskFGT** [comment]
> 

thats exactly what i did for a while after trying to fiddle with it, no results.

**Comment by mmillar-bolis** [comment]
Did you compile this from source or are you running the premade binary? Have you checked dependencies?

Can you provide some more information such as your specific OS build num and kernel version, whether you also happen to be executing the Linux binary from a read-only path, what the exit status is when running the binary from the command-line, whether you have 32-bit libs available and in your library path, and whether you have acquired a 32-bit version of SDL2 or not?

See also [this comment](https://github.com/fgsfdsfgs/perfect_dark/issues/83#issuecomment-1691213286) from @BlackRNG.

**Comment by megatog615** [comment]
> > 
> 
> thats exactly what i did for a while after trying to fiddle with it, no results.

I build the binary on a Debian 11 virtual machine, which is what the Steam Runtime Environment is based on.

**Comment by BlackRNG** [comment]
> > 
> 
> thats exactly what i did for a while after trying to fiddle with it, no results.

try running it from a terminal emulator to see the error log and also show the output of `ldd pd.exe`

**Comment by fgsfdsfgs** [comment]
Guess we'll need a flatpak or something eventually. That would also require an option to store configs and saves in `$HOME`.

**Comment by Ronald-Diemicke** [comment]
I got this to work through lutris and then used that to add it to Steam on the Steamdeck... Windows works with proton 5.13 (I think that's the right version?) but you can also use Lutris on the linux version.

**Comment by TuskFGT** [comment]
holy fuck nevermind lmfao

steam doesn't automatically enable proton for non-steam games like i assumed it would, works fine with proton experimental

**Comment by megatog615** [comment]
Well there is a Linux port and you should probably be using that.

**Comment by fgsfdsfgs** [comment]
Guess I'll close this then.
