### ISSUE TITLE
Cleaning Bot in Investigation does not rotate.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#11]
https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/480e0f02-5e4f-4f11-93e4-53ce3e0c5caf

It moves correctly, but it does not face where it's moving towards.

**Comment by fgsfdsfgs** [comment]
This should be fixed after the latest commit.

**Comment by ghost** [comment]
Can confirm it's fixed. This also fixed the fans in Defection not spinning, and the misaligned escalators in Air Base.
