### ISSUE TITLE
Menus use Nintendo A/B layout, Gameplay uses Xbox layout.

### ISSUE THREAD

**Issue by LanHikariDS** [fgsfdsfgs/perfect_dark#110]
PR #68 remapped the Menu confirm/back buttons to the reverse of what they should be on an Xbox controller, instead following the Nintendo A/B layout. As a result, Xbox Controllers must push B to advance menus, and A to back out, contrary to what the readme shows under Controls. While support for the Nintendo A/B layout should be available, it should be an option, not the standard, as it goes against the standard convention for the PC platform.

**Comment by cylonicboom** [comment]
oops. I got distracted with a grabbable bug and this escaped b/c I was thinking in Steam Deck. I'll fix it.

**Comment by TheNewClassics** [comment]
Is this something the end user could fix/edit in the ini file? It's definitely a little funky not having the A button advance in the menus.

**Comment by LanHikariDS** [comment]
I've no idea, I can't even figure out what the .ini fields mean for controls. Makes it seem like it would just move the A button entirely.
