### ISSUE TITLE
Intermittent crashes in Skedar Ruins upon player death

### ISSUE THREAD

**Issue by Aistarin** [fgsfdsfgs/perfect_dark#111]
On the `66443dd` i686-Linux build, I get the occasional `Segmentation fault (core dumped)` while playing Skedar Ruins on Perfect Agent. This has happened twice when getting killed by a Slayer rocket explosion and once upon falling into the ravine.

Two things these scenarios have in common:
- Player health is very low
- The screen never goes red, the game just immediately freezes before closing

I've attached my eeprom.bin here: [eeprom_20230828.zip](https://github.com/fgsfdsfgs/perfect_dark/files/12458350/eeprom_20230828.zip)

**Comment by iamgreaser** [comment]
PR #114 might fix this - there is an OoB memory access pertaining to cleaning up a bunch of menus when the player dies in single-player.

EDIT: OK, maybe not, it seems there's something else happening as I got a freeze w/ ASan enabled.

**Comment by AXDOOMER** [comment]
```
void func0f0f8120(void)
{
	struct menudialog *prev = g_Menus[g_MpPlayerNum].curdialog;
```

This line is exactly where the address sanitizer causes the program to crash. Occurs in every level when the player dies.

**Comment by iamgreaser** [comment]
With ASan enabled and that bug fixed, there is also a chance that the engine may hang while the player is dying (not sure what role ASan is playing here, but I've yet to trip it when it's disabled). This pertains to a particular case in `_n_sndpVoiceHandler()` where it calls `n_alEvtqNextEvent()` to work out how long to wait for, and when the queue is empty it returns 0, which causes an infinite loop.

A workaround for this would be something like this after the call to `n_alEvtqNextEvent()`:

```
if (sndp->nextDelta == 0 && sndp->evtq.allocList.next == NULL) {
  sndp->nextDelta = sndp->frameTime;
}
```

**Comment by AXDOOMER** [comment]
Maybe it triggers with ASan because it's some kind of race condition. 

Better safe than sorry. If this is an edge case that's not managed properly, you should create a new MR for it.

**Comment by fgsfdsfgs** [comment]
This should be fixed since that PR got merged.
