### ISSUE TITLE
1964-style mouse aiming

### ISSUE THREAD

**Issue by OpenRift412** [fgsfdsfgs/perfect_dark#113]
I assume this is already on the to-do list, but I thought I might as well make an issue for it. There are plans to have cursor-style aiming for playing with a mouse, right?

**Comment by ArhumMK** [comment]
Bump, would like to see this too.

**Comment by fgsfdsfgs** [comment]
Yes, this will be an option later.

**Comment by fgsfdsfgs** [comment]
Added as an option. The port now defaults to it as well. You can turn on the old mode by setting `MouseAimMode` to `1` in the `[Game]` section of the config.

**Comment by ghost** [comment]
The on screen cursor for the aim mode glitches out when near the corners. Not sure what's with that because the behaviour seems the same as 1964, yet it doesn't happen there.

**Comment by fgsfdsfgs** [comment]
Different handling of `G_FILLRECT` coords probably. This was happening before as well.

**Comment by fgsfdsfgs** [comment]
Should be fixed now.

**Comment by OpenRift412** [comment]
@fgsfdsfgs could we perhaps get a sensitivity multiplier for the mouse aiming as well?

**Comment by fgsfdsfgs** [comment]
That's already in, unless you mean specifically for aim mode. Set `MouseSpeedX/Y` in pd.ini.

**Comment by OpenRift412** [comment]
> That's already in, unless you mean specifically for aim mode. Set `MouseSpeedX/Y` in pd.ini.

I meant for specifically aim mode, my bad.

**Comment by Graslu** [comment]
Yeah it seems like aim mode is overly sensitive compared to the normal one.

**Comment by fgsfdsfgs** [comment]
There are now separate sensitivity settings for mouse aim mode under the `[Game]` section in the config:
```
MouseAimSpeedX=0.75
MouseAimSpeedY=0.75
```
Not sure what the optimal default would be here, so set it to 0.75 for now.

**Comment by Graslu** [comment]
Set it to 0.45 on Steam Deck for gyro aim and feels right. May lower it to 0.35 though, will have to test on PC tomorrow.

**Comment by cylonicboom** [comment]
I just tried this out with a mouse and keyboard and it feels amazing.

**Comment by fgsfdsfgs** [comment]
I guess I'll close this. Create new issues if there are any problems related to this.
