### ISSUE TITLE
Disable Filtering for 2D Elements

### ISSUE THREAD

**Issue by OpenRift412** [fgsfdsfgs/perfect_dark#118]
I think for the sake of legibility and clarity, texture filtering should be disabled for 2D elements (HUD, menus, text, etc.). Plus, I think it would more closely match how they appeared on the N64, as removing this filtering would essentially display them at the N64 resolution without any smoothing, which more faithfully matches the original look.

**Comment by fgsfdsfgs** [comment]
Some fonts will look a bit weird without filtering, but I can add an option for this.

**Comment by ghost** [comment]
<img width="811" alt="pausefont" src="https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/880ca96b-4445-423c-819a-88fc6a7a8f59">

The fonts for the side of the pause menu look especially bad. I cannot tell if it's a filtering issue, or if the texture is actually being cut off.
