### ISSUE TITLE
crashing after 2 second

### ISSUE THREAD

**Issue by sardonix** [fgsfdsfgs/perfect_dark#120]
it keeps crashing or does not start at all

**Comment by fgsfdsfgs** [comment]
You might have the wrong ROM. The port doesn't really check the hash or anything.
Only a clean NTSC v1.1 (aka `(USA) (Rev 1)`) ROM in Z64 format will work.

**Comment by sardonix** [comment]
i got the right rom still no luck

**Comment by fgsfdsfgs** [comment]
What OS? Did you build it yourself or download it from here? Do you see any graphics before it crashes?

**Comment by sardonix** [comment]
no download and no i dont see anything black screen not responding then crashes

**Comment by sardonix** [comment]
windows 11 btw
intel hd 4000

**Comment by fgsfdsfgs** [comment]
If you're 100% certain the ROM is correct, then it's probably that Intel GPU.
I pushed a small update that will make it show an error message if anything is wrong on the OpenGL side. Wait until the new automatic build is done and try again.

**Comment by fgsfdsfgs** [comment]
Since there hasn't been any follow up to this in a while, I'll just close it.
