### ISSUE TITLE
Bug hit texture broken?

### ISSUE THREAD

**Issue by StenApp** [fgsfdsfgs/perfect_dark#123]
If i shot people i'm getting these artifacts like in the attached movie.

https://github.com/fgsfdsfgs/perfect_dark/assets/32524257/629e31b8-3ff5-4e5b-bc79-bfc5c71eece5

**Comment by rafccq** [comment]
Already reported here: #9

**Comment by StenApp** [comment]
Ah okay, i wasn‘t aware of this already opened issue.

closed in favor of issue #9
