### ISSUE TITLE
[Oddity] Windows Defender detects pd.exe as Bearfoos trojan.

### ISSUE THREAD

**Issue by SerialDreams** [fgsfdsfgs/perfect_dark#129]
Pretty sure it's a false positive, but I figured it should be noted if it hasn't already.

**Comment by fgsfdsfgs** [comment]
Seems like a common false positive. Don't know what causes this.
pd.exe gets 1/69 on VirusTotal.

**Comment by fgsfdsfgs** [comment]
I'll close this as I have no clue what I can do here.
Remember that if your antivirus detects something that has ".ml" or "AI" in the name, that means it's a machine learning based detection, which seem to have quite high false positive rates. You can always double check on [VirusTotal](https://www.virustotal.com/gui/file-analysis/NzVlNGFmMDFlNDczOWM0ZGViNDU1YThkNzYxY2YyMzM6MTY5MzY4NTQzOQ==) or update your AV's malware database and try again.
