### ISSUE TITLE
Slow Audio Both SFX and Music

### ISSUE THREAD

**Issue by Fuzzybane** [fgsfdsfgs/perfect_dark#13]
This one is probably known but didn't see an open issue for it so I am just dropping this here 
All Music and SFX are crackly and appear to be running slow.

**Comment by Graslu** [comment]
That sounds like your PC is struggling to run the game. That occurs when the framerate drops from 60.

**Comment by Fuzzybane** [comment]
yeah game seems to be locked at 30 here but PC should be more than powerful enough, Ryzen 7 5800X 16GB 3600mhz RAM RTX 4070

**Comment by fgsfdsfgs** [comment]
That's more powerful than what I'm running it on. Might be a vsync issue. What is the refresh rate of your monitor?

**Comment by Fuzzybane** [comment]
@fgsfdsfgs 60hz

**Comment by fgsfdsfgs** [comment]
Weird. Not sure about this one. Can you try forcing VSync to off for pd.exe through the NVIDIA Control Panel? It's at "Manage 3D Settings" -> "Program Settings" -> select pd.exe here -> set "Vertical sync" to "Off" or "Fast".

**Comment by Fuzzybane** [comment]
ok I added the exe to nvidia control panel and forced vsync off and it works fine now, closing this

**Comment by fgsfdsfgs** [comment]
This might actually screw up the game since the frame delta time is probably very small. Oh well, I'll have to add a vsync toggle eventually.

**Comment by Fuzzybane** [comment]
also found out windows 11 keeps changing my display settings and set my refresh to 30hz and once again disabled HDR so it was all on my end anyway :)
