### ISSUE TITLE
Aim inversion still applied to the screen limits

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#131]
Now that free aim is implemented on mouse & keyboard this issue is noticeable. If you have aim inversion enabled, which is usually ignored and default ON in Combat Simulator, and aim to the top or bottom border of the screen, the movement will be inverted "as it should be".

https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/0509f0aa-4f1a-4715-85be-fa6a88ca2b32

**Comment by ghost** [comment]
auto aim is also applied by default on multiplayer unlike singleplayer

**Comment by fgsfdsfgs** [comment]
Auto aim defaults to on everywhere, I'm pretty sure. I didn't change how that works.

**Comment by fgsfdsfgs** [comment]
Inversion should be fixed now. Note that you can still invert mouse by setting `MouseSpeedY` to a negative number.
