### ISSUE TITLE
missing exit option in Small but Perfect Menu

### ISSUE THREAD

**Issue by Mr-Poyetas** [fgsfdsfgs/perfect_dark#133]
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/143344104/fc9e8113-a6d0-4035-a50c-a484b6e0e871)

not an issue, but it would be appreciated

**Comment by fgsfdsfgs** [comment]
Should be fixed now.

**Comment by Mr-Poyetas** [comment]
Thank you.

Also, I thank you really much for your effort porting this game.
