### ISSUE TITLE
Menu lateral text is cut by some pixels

### ISSUE THREAD

**Issue by StenApp** [fgsfdsfgs/perfect_dark#138]
The lateral text during menu is cut by some pixels at the buttom of the text
<img width="1440" alt="Screenshot 2023-09-02 231753" src="https://github.com/fgsfdsfgs/perfect_dark/assets/32524257/ae18627e-3422-4103-92b6-cca76c3b5495">

**Comment by fgsfdsfgs** [comment]
Merged #130 just now, should be fixed.

**Comment by StenApp** [comment]
You are right, tried with [07c3a51](https://github.com/fgsfdsfgs/perfect_dark/commit/07c3a513ef02cdbaa2ec08ae11ed1b4f07d4a860) and works, nice, thank you for your great work here!!!
