### ISSUE TITLE
Skybox water renders strangely

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#139]
Water has strange stretched out and distorted textures, unlike the sky, which has rendered correctly in all the cases I've seen. Maybe it's not accounting for perspective correction?

https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/98d1885f-5863-43e2-99c3-b70804f36f9e

**Comment by fgsfdsfgs** [comment]
No, I probably just fucked up the vertex order when reimplementing it. I'll take a look.
