### ISSUE TITLE
RC-P120 Silver challenge impossible to complete

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#14]
In the recently fixed gun range, the RC-P120 Silver challenge is impossible to complete as the targets won't react to the player turning invisible. They're meant to slowly turn around when using the alt fire option to cloak, but they won't do it.

https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/172a003c-4d1e-4d8c-8f41-69e8719ffb5c

Will update with other challenges that aren't possible to complete, if any.

**Comment by Graslu** [comment]
Just finished completing all the challenges with no issues other than the RC-P120.

I've noticed that other textures got corrupted though, like the computer screen, Tranquilizer, Remote Mines and the RC-P90 in the wall.

![Base Profile Screenshot 2023 08 15 - 20 40 38 25](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/38be4aa2-f4a3-4da6-b28d-afc820ae1051)
![Base Profile Screenshot 2023 08 15 - 20 48 15 87](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/3445f9ae-85ad-4c23-8e59-6f9887ad5da3)
![Base Profile Screenshot 2023 08 15 - 20 48 31 00](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/9a63a1cb-5dfa-4d9c-8726-784b975d9682)

**Comment by fgsfdsfgs** [comment]
The challenge bug should be fixed now. Probably not the textures though.
