### ISSUE TITLE
Make the "reverse pitch" option affect mouse movement as well?

### ISSUE THREAD

**Issue by Analogue112** [fgsfdsfgs/perfect_dark#140]
Previously I would just edit the "MouseSpeedY" in the pd.ini to a negative number and this worked fine but now that the mouse can be used to select items in the radial menu, it now makes the radial menu inverted as well. Maybe it would be best to make the in game option "reverse pitch" affect the mouse movement as well to mitigate this issue. Thank you.

**Comment by Analogue112** [comment]
I noticed a recent action "port: ignore invert pitch setting when mouse aiming" but to my recollection this option never did anything on any of the builds I tried. If this is an issue maybe just add a "Invert Y Axis" option to the .ini file. I literally can't play without an inverted axis unfortunately; even with a mouse.

**Comment by fgsfdsfgs** [comment]
That was to fix a specific bug. I can make it so the invert pitch in-game option works on the mouse.

**Comment by Analogue112** [comment]
That would be great. Thank you so much :)

**Comment by fgsfdsfgs** [comment]
Added that in the latest commit.
