### ISSUE TITLE
[Feature Request] Make screen shaking when exploding

### ISSUE THREAD

**Issue by a1lic** [fgsfdsfgs/perfect_dark#141]
Screen shaking not occurs at exploding.
But occuring in original N64 and XBLA ver.

**Comment by ghost** [comment]
The way screen shaking logic on both GE and PD breaks at 60 FPS. I also think it's a framebuffer effect but I could be wrong on that.

**Comment by fgsfdsfgs** [comment]
Nah, I just need to let it move the viewport around.

**Comment by fgsfdsfgs** [comment]
Added. You can turn it off by setting `ScreenShakeIntensity` to 0 in pd.ini.

**Comment by a1lic** [comment]
Nice work! Thank you very much.
