### ISSUE TITLE
Challenge 12 - Slomo - cannot reenter instantly after beeing killed

### ISSUE THREAD

**Issue by StenApp** [fgsfdsfgs/perfect_dark#142]
I played Challenge 12 and got killed.
I cannot reenter the game by hitting Return, except the game shows the killscreen with countdown of 10 to throw you back in.

**Comment by Phnod** [comment]
Tried to replicate this but was able to respawn pressing Enter, was platform are you using? Did you compile from source or use the precompiled actions? Which version?

**Comment by StenApp** [comment]
I use the automated builds under win11 Radeon Pro 560.
I think it was this one: 
https://github.com/fgsfdsfgs/perfect_dark/actions/runs/6060999132

**Comment by Phnod** [comment]
Tried this again with that build but I get the same result as the original game, being able to respawn as soon as the 10 appears. Was there anything that happened prior to dying that might've caused it? Are you able to replicate it?


https://github.com/fgsfdsfgs/perfect_dark/assets/16583255/af938d5a-7c86-4dd6-b5b9-ce668539156f

**Comment by StenApp** [comment]
Oh, it is normal that i have to wait until the 10 is shown? I thought i can respawn instantly and skip the death animation.
If that‘s the normal behavior, this issue can be closed.
