### ISSUE TITLE
[Feature Request] options for texture upscaling, Gouraud/Phong shading, and Tessellation.

### ISSUE THREAD

**Issue by Moonkeytest** [fgsfdsfgs/perfect_dark#146]
I was wondering about the possibility to include options for:

1) Texture upscaling filters (JINC2 and xBRZ+deposterization).

2) Gouraud or Phong shading (to make those low-poly elements look a little less point).

3) Tessellation (same as above, but probably much more challenging).

**Comment by fgsfdsfgs** [comment]
1. Personally I don't care for scale filters. Most of the time it ends up looking like ass. It might work okay on UI textures or fonts, but beyond that I'd rather allow loading external HD textures and let people upscale them however they want.
2. Per-pixel shading is theoretically possible, there's already a [request](https://github.com/fgsfdsfgs/perfect_dark/issues/22) for it.
3. If you just subdivide existing models without thinking, the game will end up looking like GTA Definitive Edition. This is a problem that would be best solved by allowing models to be loaded externally, which already kind of is a thing. Then maybe someone could port the XBLA models or something.

Regardless, advanced visual enhancements are something to consider after the base game port is completely finished.

**Comment by fgsfdsfgs** [comment]
Since this is covered by other feature requests, I'll close it.
