### ISSUE TITLE
Can't complete dataDyne Extraction on Special Agent

### ISSUE THREAD

**Issue by amphyvi** [fgsfdsfgs/perfect_dark#148]
unable to complete dataDyne Extraction on Special Agent. when attempting to do so, objective 3 (Defeat Cassandra's bodyguards) never completes. when all the guards are killed, their bodies disappear... all except one (doesn't seem to be consistent), and the objective is never marked as complete. all other objectives can be completed normally.

the same objective works fine in regular Agent. haven't tested in Perfect Agent because I haven't unlocked that difficulty for this mission yet.

**Comment by StenApp** [comment]
You have to go downstairs and kill all bodyguards on the other floors.
Maybe a bug?

**Comment by cammydev0** [comment]
i could complete it fine on perfect agent

**Comment by Darken93** [comment]
I was able to complete on both SA an PA. No issues with the bodyguards

**Comment by Graslu** [comment]
Did you kill the ones next to the computer that activates the elevator on PA? You have to kill all of them including those.

**Comment by amphyvi** [comment]
oh... I forgot taking care of the ones on other floors was a requirement on SA/PA. sorry! I was just thinking of the ones immediately around Cassandra in that room at the end. I'll try getting all of them and report back

**Comment by amphyvi** [comment]
it worked lmfao. thanks for the help! sorry I thought it was a problem with the port.
