### ISSUE TITLE
Double bullet holes

### ISSUE THREAD

**Issue by StenApp** [fgsfdsfgs/perfect_dark#150]
I'm getting double bullet holes with one shot.

<img width="1440" alt="Screenshot 2023-09-03 142412" src="https://github.com/fgsfdsfgs/perfect_dark/assets/32524257/6f4ed60a-8871-4c08-bebb-bde35e9be962">

**Comment by Graslu** [comment]
Already reported in #101

**Comment by fgsfdsfgs** [comment]
Closing as duplicate.
