### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by brwnie** [fgsfdsfgs/perfect_dark#153]
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/11775356/280af517-de3b-4de0-b695-77541150e46a)

Occured during Mr Blondes Revenge, Perfect Agent, floor below Cassandras Office

Had just opened door to room where guard is looking out of window and the application hung

**Comment by fgsfdsfgs** [comment]
What version was this on? Commit ID is shown on the startup screen, you can just post a screenshot of that.

**Comment by brwnie** [comment]
Sorry, I've updated since then but at the time of report it was the latest build

**Comment by fgsfdsfgs** [comment]
Yeah, I dunno. Couldn't reproduce this. The backtrace looks like it's in a DLL. Could be in ntdll or could be in your GPU driver.
If you encounter this again, please post the error message again here.

**Comment by fgsfdsfgs** [comment]
Has been a while, probably fixed.
