### ISSUE TITLE
[Bug] Classic Weapons in Multiplayer - RC-P45 replaces "Disabled" when using "Random Five" weapon settings.

### ISSUE THREAD

**Issue by Knaxia** [fgsfdsfgs/perfect_dark#156]
Since the classic weapons have been added at the bottom of the list in the weapons list in combat sim, the "Random Five" option usually always fills the last slot with "Disabled" which is the last entry in the list. Having the classic weapons there makes it pick the RC-P45 instead, which shouldn't.

![Screenshot (40)](https://github.com/fgsfdsfgs/perfect_dark/assets/73440864/fef45253-5f06-4b5a-9398-86cd1244ddd7)
![Screenshot (42)](https://github.com/fgsfdsfgs/perfect_dark/assets/73440864/0169bcdf-3a02-42a7-bbb0-943029fce62c)

**Comment by tmyqlfpir** [comment]
Fixed by PR #160

**Comment by XenoMole** [comment]
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/37374655/449e87c5-4a24-402a-a113-d7513bac59b1)
Same issue but with a different weapon. The save I used to take the screenshot does not have all weapons unlocked.

**Comment by fgsfdsfgs** [comment]
It does turn out that it would be better if the disabled option was last in the list. But that requires patching the mpconfigs on load. Big think.
You know what, let's just do that anyway. Thought we could minimize the amount of patching here, but it doesn't really matter much and is only going to cause issues like this.

**Comment by fgsfdsfgs** [comment]
Alright, reverted it back to an earlier version of #76. Should be fixed now. Guess if someone wants to mod mpconfigs they'll have to take that into account.

**Comment by fgsfdsfgs** [comment]
Reopen this if you find any problems with that solution, I guess.
