### ISSUE TITLE
[Request] Remove Ratio option from CS: Stuff

### ISSUE THREAD

**Issue by Omegacop1543** [fgsfdsfgs/perfect_dark#158]
Nothing major but since both the Ratio and the Hi-Res option were removed, same could go for in CS. 

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/12872978/b263950d-305a-4ca9-bd03-884423aea15a)

**Comment by Atari-Dude** [comment]
I personally would like to see 4:3 ratio still re-listed as a dedicated option though

**Comment by fgsfdsfgs** [comment]
That would be a different option. Though I guess I could reuse the old ratio option for it.
