### ISSUE TITLE
Resolution won't change even when editing the ini file

### ISSUE THREAD

**Issue by 1chiTheKiller** [fgsfdsfgs/perfect_dark#159]
For some reason even when I edit the width and height values in the ini file, the resolution always turns out to be 1536x960.  My system I'm using right now is 1920x1200.  FOV adjustments work, I've turned texture filtering on and off for 3D and 2D elements, and I've edited the controls a bit, so I know the ini file DOES in fact work in changing some options.  Unfortunately it won't change the resolution for me.  Also MSAA won't change either.

So it looks like it DOES render in higher resolutions when it is in windowed mode, but never goes higher than 1536x960 when I make the game full screen.

**Comment by 1chiTheKiller** [comment]
MSAA also seems to work when in windowed mode, same as the higher resolution, but neither when in fullscreen.  Running as admin makes no difference.

**Comment by 1chiTheKiller** [comment]
OK, so I just solved my issue.  I fixed it by adjusting the pd.exe high DPI settings.  I checked the high DPI scaling behavior box, and that now allows the game to render at full resolution and with MSAA in fullscreen mode.

**Comment by fgsfdsfgs** [comment]
The width/height options in the file are for the window size specifically and only have effect in windowed mode.
"Fullscreen" is actually a borderless window, and as such it always takes up the entire desktop resolution.
HiDPI awareness is something I'd need to look at though.
