### ISSUE TITLE
Models are not affected by room darkness.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#16]
<img width="436" alt="dark" src="https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/d673b2af-2166-4919-b79e-ee7c16ca62cf">

To reproduce, use the light switch in the first room on Defection, or load the start of Extraction.

**Comment by Graslu** [comment]
This also applies to vertex shadows:

![Base Profile Screenshot 2023 08 16 - 12 52 50 25](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/7ed57a9e-7c1a-46e6-bfde-6f9911a47d36)

**Comment by fgsfdsfgs** [comment]
This should be fixed now.

**Comment by ghost** [comment]
Can confirm both screenshots are fixed in the current artifact.
