### ISSUE TITLE
[Question] Mouse control (up and down)

### ISSUE THREAD

**Issue by orderorder** [fgsfdsfgs/perfect_dark#168]
In the latest version of the code, the mouse control is reversed. Where could I change this option? Thank you

**Comment by fgsfdsfgs** [comment]
Try Options -> Control -> Reverse Pitch.
It's actually enabled by default, might be a good idea to remove that.

**Comment by orderorder** [comment]
You have to excuse me, I hadn't been able to find the options menu. My fault. Thank you for changing this in the current code and for bringing this amazing game to PC.
