### ISSUE TITLE
Mouse input issue with HorizonScan

### ISSUE THREAD

**Issue by Unradelic** [fgsfdsfgs/perfect_dark#169]
Maybe somebody is already aware of this, but mouse input when using HorizonScan acts wrongly.

Video:
https://github.com/fgsfdsfgs/perfect_dark/assets/20099874/823e23f9-1db0-43a5-8bce-3b038d385c6d

**Comment by Phnod** [comment]
Wasn't sure what was going on in the vid, but testing it out it seems to be a `MouseAimMode=0` issue, I suppose if the HorizonScanner is out the aiming mode should use to fixed aiming instead.

**Comment by fgsfdsfgs** [comment]
Should be fixed now. Aim mode is now ignored when using the Horizon Scanner and acts as if it's set to 1.
