### ISSUE TITLE
Radial menu position incorrect when aspect ratio != 4:3

### ISSUE THREAD

**Issue by rafccq** [fgsfdsfgs/perfect_dark#170]
It is related to [this change](https://github.com/fgsfdsfgs/perfect_dark/commit/2e49ba10dd160b959c33d3004d6e9208bc8fd96b)
Happens in 3/4 players MP or 2 players MP with vertical split.

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/1994385/172516e4-9d95-4201-ad47-21c3d0813530)
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/1994385/75e0f180-216e-4cf4-b427-2731d798aa72)

**Comment by fgsfdsfgs** [comment]
The HUD aspect ratio correction isn't meant to work in split screen yet, looks like I forgot some checks for that. Fixed I think.

**Comment by rafccq** [comment]
Yes is correct now.
Not sure it's related, but the in-game window has a similar problem:
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/1994385/a5fe99da-f34c-4af5-a4d7-710a161bbdde)

**Comment by fgsfdsfgs** [comment]
It is related, but not quite as much of a problem, so I haven't fixed it.
