### ISSUE TITLE
Cannot shoot through grating textures

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#172]
Self-explanatory. They should be ignored by shots. Does not occur to handrails.

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/c411690d-ce5c-4a81-a2c2-fbd12a4072a8)

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/95961853-78d1-4671-ac8c-503b2edcd7c7)

**Comment by fgsfdsfgs** [comment]
Was this always the case with the port?

**Comment by Graslu** [comment]
Tried a version from last week and the first (oldest) version, solid on both. I swear it was non-solid once but I guess not.

**Comment by fgsfdsfgs** [comment]
Ah, I think I found the cause. The hit surfacetype and the sound surfacetype are swapped.

**Comment by fgsfdsfgs** [comment]
Should be fixed now. This might have fixed other related issues, if there were any.

**Comment by Graslu** [comment]
Can confirm it's fixed.
