### ISSUE TITLE
[Partially resolved] [Bug] Area 51 - Infiltration cutscene screen effects broken

### ISSUE THREAD

**Issue by Awii2** [fgsfdsfgs/perfect_dark#173]
In the opening cutscene for the first Area 51 mission, no screen effects show at all. Here is how it looks:
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/87900556/145fbfca-bec3-457e-9eb7-894db2a8ce5b)
Compared to GLideN64:
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/87900556/51564ea4-fe8b-4224-9b92-c432b6f5851b)
There are probably some other screen effects that are broken, but this is the one that is easiest to see.

**Comment by fgsfdsfgs** [comment]
Right, this is yet another missing framebuffer effect.

**Comment by fgsfdsfgs** [comment]
This is now partially fixed. Effect is a bit different.

**Comment by ghost** [comment]
It's still nice just having the effect even if it's bit different. I always though the white noise / signal interference effect in perfect dark was really neat. I love the way the horizon scanner looks too. Also makes me think of the mid-screen scanline effect the nes could do too.

**Comment by Graslu** [comment]
Is the Horizon Scan meant to have an effect? Mine doesn't.

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/56330f17-acd4-4213-8b96-445888416cfe)

**Comment by fgsfdsfgs** [comment]
No, that's not implemented yet.

**Comment by Graslu** [comment]
Ah alright, got a bit confused with the last comment.

**Comment by ghost** [comment]
I got a bit excited about some of the effects working, wasn't my intention to confuse anyone, my bad

**Comment by fgsfdsfgs** [comment]
This has been working for a while now.
