### ISSUE TITLE
Mouse x momentum is preserved when pressing the start menu in pauseless scenarios

### ISSUE THREAD

**Issue by cylonicboom** [fgsfdsfgs/perfect_dark#177]
If the player flings their mouse to the right or left just before pause-less menus, Jo will continue to spin around a bit as if she's on a swivel. I noticed this when I ported my no-pausing mod, but I think counter / co-op might experience this behavior as well.

I have a hacky snippet, which I'll post, which resets the speedtheta if the current player is paused. I think some movement impulse is being preserved in the PC port mouse implementation unintentionally. This doesn't happen w/ Y movement.  This wasn't an issue in the mouse injector + 1964.

- [x] check w/ vanilla + counter/co-op scenario
- [x] post workaround
- [ ] check gdb before updatetheta in walktick

**Comment by fgsfdsfgs** [comment]
Probably need to zero out some angular speed component or something.

**Comment by Graslu** [comment]
Not exactly related but kinda related - on the PC port the mouse still acts like the joystick moving the character, while on 1964 GEPD it exclusively moves the camera. This is noticeable if you move the mouse slowly left or right, you'll notice Jo will "step" to the side on the port. On 1964 it acts more like a PC game where you just spin in place.

In a way this is more accurate to N64 and the real game, but it can feel a bit off at times. Kind of torn between if it should be left as is or not.

**Comment by cylonicboom** [comment]
@fgsfdsfgs yeah I had something in bwalktick to zero it out but this works for walk / grab / drive modes:

https://github.com/fgsfdsfgs/perfect_dark/commit/1e55fe48942316930f86fa738717fe170f10aeaf

I'll get my controller and see if this is even an issue in vanilla pc pd

**Comment by cylonicboom** [comment]
> Not exactly related but kinda related - on the PC port the mouse still acts like the joystick moving the character, while on 1964 GEPD it exclusively moves the camera. This is noticeable if you move the mouse slowly left or right, you'll notice Jo will "step" to the side on the port. On 1964 it acts more like a PC game where you just spin in place.
> 
> In a way this is more accurate to N64 and the real game, but it can feel a bit off at times. Kind of torn between if it should be left as is or not.

I wonder if this happens in xbox pd or n64 2.2. maybe extra sway calculations are happening from the input / movement data that's being collected in the functions rather than the speed angles being messed with directly?

**Comment by cylonicboom** [comment]
I verified that this issue doesn't reproduce in vanilla `port` pd in the co-op. I'll keep the w/o in my own no-pausing mod.
