### ISSUE TITLE
MBR co-op crash

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#180]
Playing Mr. Blondes in PA with AI co-op, used the bombspy on the lobby area and crashed after blowing it up. Able to reproduce multiple times. 

```
EXCEPTION: 0xc0000094
PC: 00462d4f
MODULE: 00400000
MAIN MODULE: 00400000

BACKTRACE:
no information
```

**Comment by fgsfdsfgs** [comment]
Wow, that's a division by zero error. Haven't seen those in a while.
It's a bit strange. The PC value points to `chraction.c:3657`:
```
subindex = random() % g_YeetAnimIndexesByRaceAngle[race][angleindex].count;
```
While this does indeed have a division in it, the `count` field should never be 0 as long as `race` and `angleindex` are correct.
Did this only start happening in the latest build?

**Comment by fgsfdsfgs** [comment]
This might have been fixed in the latest build.

**Comment by Graslu** [comment]
Confirmed.
