### ISSUE TITLE
Polygons fully covering player view.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#183]
This has only occurred on the most recent iterations of the port. I suspect maybe the changes to system trig may have caused this.

https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/6a5ec085-6b8f-41de-9f63-f9727f2cce97

**Comment by iamgreaser** [comment]
This happened to me on Crash Site PA when I reloaded my Falcon 2 (scoped) after I fired 2 shots. I haven't been able to reproduce it.

**Comment by fgsfdsfgs** [comment]
Well then. Time to roll it back.
Can you check if this still happens in the new build?

**Comment by ghost** [comment]
I can't reproduce it in newer builds. 
I will, however, keep the issue open as the other poster seems to suggest it's difficult to reproduce.

**Comment by fgsfdsfgs** [comment]
This was likely a result of the trig thing. Closing for now.
