### ISSUE TITLE
1.2 Analog Movement w/ PC Controllers

### ISSUE THREAD

**Issue by cylonicboom** [fgsfdsfgs/perfect_dark#184]
I'm working on analog movement based on the C stick support @fgsfdsfgs  added.

Creating this to track work tasks so I don't spam w/ emails:

Branch: https://github.com/NeonNyan/perfect-dark-fgsfdsfgs/tree/1.2_analog

Status: Walking / grabbing / biking working as expected.

Tasks:
- [x] implement leaning
- [x] implement  zooming
- [x] implement menu movement
- [x] implement camspy stick movement
- [x] implement slayer rocket airbrake
- [x] test menu sliders

**Comment by cylonicboom** [comment]
- [ ] #42 : it makes more sense to implement this directly rather than implement aim + cstick crouching

**Comment by cylonicboom** [comment]
- [x] TODO: cleanup ints that definitely should not have been changed

**Comment by fgsfdsfgs** [comment]
The relevant PR has been merged, so I'll close this.
