### ISSUE TITLE
Can you please make it for opengl 2.1 or 3.1 please

### ISSUE THREAD

**Issue by sardonix** [fgsfdsfgs/perfect_dark#185]
it will help people like me with bad graphic cards

**Comment by fgsfdsfgs** [comment]
It already only requires GL3. What is your graphics card?

**Comment by sardonix** [comment]
intel hd graphics 2000

**Comment by fgsfdsfgs** [comment]
Is there any particular error you're getting on startup?

**Comment by sardonix** [comment]
wait imma check now
give me a sec

**Comment by sardonix** [comment]
its showing error

**Comment by sardonix** [comment]
ill send screenshot

**Comment by sardonix** [comment]
![Screenshot 2023-09-26 121913](https://github.com/fgsfdsfgs/perfect_dark/assets/106691765/bbc9f5ad-b336-4e0b-95cf-788952fde7b0)

**Comment by fgsfdsfgs** [comment]
That's quite interesting, because the function it crashes on (`glGenBuffers`) is part of GL1.5 and above, so you definitely should have it. You can try running the game with the `--debug-gl --log` command line arguments and then posting the `pd.log` file it creates. Make sure also that your graphics card driver is up to date.

**Comment by sardonix** [comment]
wait sorry but where is the log file
Im a noob sorry

**Comment by fgsfdsfgs** [comment]
Should be in the same folder as where `pd.exe` is, the file that you use to run the game.

**Comment by sardonix** [comment]
![Screenshot 2023-09-26 123552](https://github.com/fgsfdsfgs/perfect_dark/assets/106691765/95a61969-1d7d-49e6-bbbe-1a70b0cac702)
theres no log file

**Comment by fgsfdsfgs** [comment]
[pd.zip](https://github.com/fgsfdsfgs/perfect_dark/files/12726485/pd.zip)
Here, try running this, see what it says.

**Comment by sardonix** [comment]
idk whats going on but theres still no log file sorry for stressing you

**Comment by sardonix** [comment]
![Screenshot 2023-09-26 124345](https://github.com/fgsfdsfgs/perfect_dark/assets/106691765/e3e8c92d-9556-46b5-bafe-496f06147f83)

**Comment by fgsfdsfgs** [comment]
No, this is fine. I don't have a graphics card that old so my only option is to ask you to test this.
[pd.zip](https://github.com/fgsfdsfgs/perfect_dark/files/12726615/pd.zip)
Here, try this one. It should show a different error.

**Comment by sardonix** [comment]
![Screenshot 2023-09-26 130130](https://github.com/fgsfdsfgs/perfect_dark/assets/106691765/2629c615-31aa-40a2-b3e7-c94988e350c2)
just this

**Comment by fgsfdsfgs** [comment]
Well now, that makes no goddamn sense.
[pd.zip](https://github.com/fgsfdsfgs/perfect_dark/files/12726763/pd.zip)
Try this one. It should create a file called `pd-glinfo.log` in the same folder. Post that file if it's there. And a screenshot of the error you get.

**Comment by sardonix** [comment]
![Screenshot 2023-09-26 131415](https://github.com/fgsfdsfgs/perfect_dark/assets/106691765/1ddf6c8f-dbcf-4743-9adf-4450d9deaf1a)
now this is it. no log file

**Comment by fgsfdsfgs** [comment]
It seems you're currently stuck on the Microsoft Software OpenGL driver, which is a shitty software implementation of GL1.1 only that's used when there's no proper GPU driver installed. Either you don't have drivers for your GPU installed or they're unsupported on your version of Windows. You can try installing the newest driver from [here](https://www.intel.com/content/www/us/en/support/products/81502/graphics/processor-graphics/intel-hd-graphics-family/intel-hd-graphics-2000.html).

**Comment by sardonix** [comment]
ok Thanks

**Comment by sardonix** [comment]
Hello i just found i have 2 installed gpus one is intel and other nvidia.
i went and changed it to nvidia and it work TYSM

**Comment by fgsfdsfgs** [comment]
Cool.
