### ISSUE TITLE
Laptop scrolling texture gets stretched after 3 minutes

### ISSUE THREAD

**Issue by AlexiCat** [fgsfdsfgs/perfect_dark#193]
The green scrolling texture on the laptop in the Carrington Institute gets stretched after sitting idle for about 3 minutes

https://github.com/fgsfdsfgs/perfect_dark/assets/25622070/b8e01a98-3bd6-43b4-8d59-4ad13a036ba9

**Comment by bacyco** [comment]
EDIT: I did even more testing, this happens with every monitor if you wait in front of them long enough. 



https://github.com/fgsfdsfgs/perfect_dark/assets/144067266/2b1dbc36-0102-4cc0-a670-e18a6811f7e5


No idea what the mechanism is, but it's seemingly related to player proximity as this will happen in the firing range when you're not even looking at the screen, but in my video it only occurs to one monitor despite being right next to the other.

**Comment by fgsfdsfgs** [comment]
Scroll value was going so high that it was generating tex coords that are out of range. Will commit fix shortly, after I'm done waiting for it to scroll for like 20 minutes just in case.
After waiting for 20 minutes it didn't seem to do this anymore.
