### ISSUE TITLE
Crosshair doesn't sway when Follow Lock-on mode is enabled for CMP150 

### ISSUE THREAD

**Issue by OpenRift412** [fgsfdsfgs/perfect_dark#195]
Like the title says. Don't know why this happens exactly. Only happens when the CMP150 is held and is in Follow Lock-on mode.

**Comment by fgsfdsfgs** [comment]
Might be good to check if this happens with a gamepad. I have a general idea where that might be happening.

**Comment by OpenRift412** [comment]
> Might be good to check if this happens with a gamepad. I have a general idea where that might be happening.

Just checked, it's also happening while playing with a controller.

**Comment by Phnod** [comment]
This was also something that happened in the N64 version too I believe?

**Comment by OpenRift412** [comment]
> This was also something that happened in the N64 version too I believe?

I mean, I tested this in the 1964 GEPD emulator and it still sways with lock-on enabled.

**Comment by Phnod** [comment]
https://github.com/fgsfdsfgs/perfect_dark/assets/16583255/88bc8e7a-b762-4a80-bfad-ba27cdc1df27
Oh huh, tested it with and without 1964, it must be unique to that version.
I remember in the past using the swaying as a visual cue for whether I was currently using the lock on or not.

**Comment by bacyco** [comment]
Just pulled out my N64 and plugged in the cartridge, the crosshair does not sway in Lock-on mode on actual hardware.

**Comment by OpenRift412** [comment]
> Just pulled out my N64 and plugged in the cartridge, the crosshair does not sway in Lock-on mode on actual hardware.

Yeah forget I said anything, I just tested in Simple64 and there's no sway. Issue closed. My bad.
