### ISSUE TITLE
How do I check for SDL2, libGL and ZLib on my system?

### ISSUE THREAD

**Issue by farawaykcmm** [fgsfdsfgs/perfect_dark#2]
Title

**Comment by fgsfdsfgs** [comment]
Depends on what system it is. If you're new to this whole "compiling from source" thing, I'd really suggest you wait until automatic builds or releases are a thing. This project is still in pretty early stages.
On Linux you'll want to install the appropriate packages, on Debian or Ubuntu that would be `libsdl2-dev` and `zlib1g-dev`. libGL is part of your graphics driver there.
On Windows you'll want to install MSYS2, open the MINGW32 environment and install `mingw-w64-i686-toolchain`, `mingw-w64-i686-SDL2` and `mingw-w64-i686-zlib`.

**Comment by fgsfdsfgs** [comment]
There are now automatic builds available. Probably no reason to keep this open.
