### ISSUE TITLE
movement stick shouldn't control radial menu

### ISSUE THREAD

**Issue by cylonicboom** [fgsfdsfgs/perfect_dark#205]
I mistakenly added movement stick tracking in my 1.2 analog branch.

This breaks play with controllers and "radial-ing while running" by forcing the player to release their movement stick to not mess up their radial selection. This is very distracting, makes, rapid-swapping at melee range impractical, and not xbla behavior.

**Comment by fgsfdsfgs** [comment]
Oh. I assumed you added this into the mouse check by mistake.
