### ISSUE TITLE
Is it possible to invert mouse on the PC port?

### ISSUE THREAD

**Issue by AdamBeGood** [fgsfdsfgs/perfect_dark#209]
I've looked through the Configuration file and can't see the option. I just wondered if that is possible. Thank you.

**Comment by fgsfdsfgs** [comment]
Check the Reverse Pitch option in the Control menu.

**Comment by AdamBeGood** [comment]
Sorry! I'd just come back to check that I hadn't missed it in the in-game options... Doh! Thank you - thanks for your work on this!
