### ISSUE TITLE
broken sky on villa (and possibly other maps) 

### ISSUE THREAD

**Issue by sylveonsylvia** [fgsfdsfgs/perfect_dark#21]
the sky on villa renders pitch black (this probably effects other maps too but I haven't tested yet)
![Screenshot_20230816_233423](https://github.com/fgsfdsfgs/perfect_dark/assets/78629289/48e53189-81dc-46af-be35-ab043d8dd3ff)

**Comment by jonaeru** [comment]
Air Base
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/408cb196-8cac-4de0-8a24-ac592d16e09c)

Crash Site
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/b64a55eb-0e0d-4e19-9424-cfc4f41dba9e)

**Comment by StenApp** [comment]
Same problems with proper skybox rendering here

**Comment by fgsfdsfgs** [comment]
This *might* be fixed now. Not sure if the method I chose to render them is exactly the same as the original, but it looks fine.

**Comment by Graslu** [comment]
The skies work now, but it seems like it "lags" behind. Easy to spot in Villa with the blue sky. If you move your aim while looking at the sky, the borders will start "shaking" as it shows the black background behind while it tries to keep up.

**Comment by fgsfdsfgs** [comment]
I think it actually does that in the original too, but doesn't expose the background when it does so. I'll see what I can do about it.

**Comment by fgsfdsfgs** [comment]
That should be fixed now.
