### ISSUE TITLE
Resolution scale / Exclusive fullscreen

### ISSUE THREAD

**Issue by wormmayhem** [fgsfdsfgs/perfect_dark#212]
I'd like to play it in 4K with my 1080p display, but I can't set 4K resolution because Fullscreen mode forces the native resolution. Can you add a resolution scale option (up to 200%) or Exclusive fullscreen mode, so we can set 4K resolution in "pd.ini" file?

**Comment by fgsfdsfgs** [comment]
Why do you need higher than native resolution? There's an MSAA option if it's just for anti-aliasing. Or is it to take hi-def screenshots or something? Exclusive fullscreen will still be limited to your display's max resolution, unless there's a way to override it through the graphics driver or something that I don't know about.
I suppose it's possible to add a mode where it renders to a higher res framebuffer and then blits it to the screen, but again, that'll just end up being downscaled to your native res.

**Comment by wormmayhem** [comment]
You are right, makes no sense to use a higher res since it's a N64 port and doesn't include high res fonts and textures. I'll use only MSAA, thanks for reply, also, I can't wait to see 60+ fps patch!
