### ISSUE TITLE
Laptop gun challenge 2 bug - Not targeting third target

### ISSUE THREAD

**Issue by stephensrmmartin** [fgsfdsfgs/perfect_dark#214]
When in the carrington institute shooting range, the laptop gun's silver challenge is not progressing.

This is the challenge where the three targets are turned around. The solution is to throw the laptop gun in sentry mode beyond the targets, so that it will shoot from behind (in front of?) the targets.

It will always shoot two targets, and stop shooting at the third. It is then impossible to progress.

**Comment by fgsfdsfgs** [comment]
Cannot confirm:

https://github.com/fgsfdsfgs/perfect_dark/assets/2997482/f08860d5-c9b7-4c4f-81c3-6fe13a467aef

Try throwing it lower and closer to the center of the range.

**Comment by Cobra84** [comment]
It is running out of ammo. The higher frame rate is causing a higher rate of fire which causes more ammo waste while switching targets.

**Comment by stephensrmmartin** [comment]
> It is running out of ammo. The higher frame rate is causing a higher rate of fire which causes more ammo waste while switching targets.

Doesn't it start with like, 800 ammo? Seems too fast to run out of ammo.

I threw it exactly as you did, and it again destroys two, then stops immediately after, and doesn't target a third.

**Comment by Cobra84** [comment]
> Doesn't it start with like, 800 ammo? Seems too fast to run out of ammo.

The turret holds 200 rounds and shoots much faster than its regular gun form.

**Comment by stephensrmmartin** [comment]
Hm, is there a built in way to limit fps below 60 to test this problem then? Or should I use an external limiter?

**Comment by fgsfdsfgs** [comment]
> The higher frame rate is causing a higher rate of fire which causes more ammo waste while switching targets.

If that is the issue, then that is a bug that needs to be fixed.
There is a framerate limit option in `pd.ini`, but the game should not run any faster than it runs in that video anyway.

EDIT: This seems to work exactly the same on 1964GEPD.

**Comment by ghost** [comment]
This should be compared against XBLA. If memory serves right, they did alter the turret RoF.

**Comment by stephensrmmartin** [comment]
I limited FPS to 30, and did it on my first try:

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/2332684/a8f4e05c-10c3-4195-b071-c949490aec52)


I did nothing really different, and I had tried it probably 40x at 60fps without success.

**Comment by fgsfdsfgs** [comment]
Confirmed that the turrets indeed shoot every frame. I'm assuming XBLA limits it to every other frame. Will fix once I figure out the best way to do it.

**Comment by fgsfdsfgs** [comment]
This should be "fixed" now, though I'm not sure if the hack broke anything else.

**Comment by stephensrmmartin** [comment]
Woot, worked on first try at 60fps.

Thanks for the quick fix!

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/2332684/17a1c322-df32-4f63-a636-a585d52ac074)
