### ISSUE TITLE
How to change gamepad control bindings without messing with the keyboard ones?

### ISSUE THREAD

**Issue by Tasosgemah** [fgsfdsfgs/perfect_dark#216]
I'm trying to change the gamepad mappings but it seems like i can only change the keyboard ones, which then conflict with the default gamepad ones.

For instance, if i bind R-Shoulder for "next weapon", when i press that button it does that but it also changed the fire mode at the same time. 

Is there a way to change the gamepad bindings only?

**Comment by fgsfdsfgs** [comment]
Oh yeah, I guess I forgot to add a way to delete bindings to the menu. You'd need to bind R-Shoulder to Next Weapon and then remove it from Fire Mode.
In the binding menu there was also a bug with one of the bindings being the same thing as Next Weapon. That has been fixed in the latest build.

**Comment by fgsfdsfgs** [comment]
Okay, you can now do that by selecting the conflicting binding and hitting DEL on your keyboard.
You can also edit the bindings in `pd.ini`.

**Comment by Tasosgemah** [comment]
Ok, i'm trying the pd.ini but it's so confusing though i think i can figure it out.

Also, the fire button is R-Trigger, not R-Shoulder.

**Comment by fgsfdsfgs** [comment]
If you download the latest build, you can now delete the binding in the options menu as well.

**Comment by Tasosgemah** [comment]
Is it possible to unbind "hard coded" functions? For instance the "wheel menu" function (the one that shows you your weapons and gadgets) also counts as a "select/action" function. So wherever i bind it i also make a selection with it. I want to bind it to the "B" button that also functions as "back/cancel" but i can't because when i do, instead of "back/cancel" it also becomes "select/action".

**Comment by fgsfdsfgs** [comment]
The radial menu is supposed to be separate from the accept button. Looks like that's a bug then.
EDIT: Ah, no, that's intentional. Radial menu button also acts as accept in menus because of the way it's set up.

**Comment by Tasosgemah** [comment]
Is it possible to achieve the same control as the N64?

For instance, the radial menu is accessed when you **hold** the cycle weapon button. This button seems to be missing here as you now have 2 separate buttons to cycle the weapons.

Also, the "reload" function is the same as the "use/open" function. But when you are near a door, the reload is disabled so you can open it. You can only reload when you are away from a door/usable item.

I know, condensing the buttons like this is not needed anymore since modern controllers have more buttons. But it's useful  if you are used to playing the original, so you don;t need to re-wire your brain.

**Comment by fgsfdsfgs** [comment]
Not yet, but eventually. There is an [issue](https://github.com/fgsfdsfgs/perfect_dark/issues/161) for this though.

**Comment by fgsfdsfgs** [comment]
N64 controls are now in and I think the rest of this has been sufficiently explained as well.
