### ISSUE TITLE
Reshade not working

### ISSUE THREAD

**Issue by FoxTurret** [fgsfdsfgs/perfect_dark#220]
Reshade loads, compiles shaders, and reads the z-buffer properly, but the image freezes when the main menu appears. Neither the game, nor Reshade crashes. All controls and audio still work, but the image remains stuck on the frame before the main menu is rendered. Reshade's UI and shaders remain functional.

**Comment by parabolee** [comment]
Also found the same problem, would love a solution.

**Comment by fgsfdsfgs** [comment]
Try changing the MSAA setting in pd.ini. Other than that I can't really help you with Reshade, don't know anything about it.

**Comment by FoxTurret** [comment]
It's framebuffer related. I turned of framebuffer effects in pd.ini and it works now. This isn't ideal though. [Their git repo is here](https://github.com/crosire/reshade). I hope that helps.

**Comment by Xii-Nyth** [comment]
I noticed the same in the newer builds, also noticed format has changed from D24x8 to D24s8. it works up until the menu. whats strange is the reshade effects hold even whe effects are disabled, they should clear...

in older builds (09/03) was fine including depth (besides errors which I was going to check if they were fixed)

**Comment by fgsfdsfgs** [comment]
The depth format was changed because some GPUs apparently don't like 24-bit depth with no stencil.
I'm not doing anything extraordinary with the framebuffers (in fact the destination framebuffer never changes unless you have MSAA enabled), so unless the depth format is somehow the problem I'm not sure why it would break.

**Comment by Xii-Nyth** [comment]
ill go track down which update exactly broke it then

**Comment by Xii-Nyth** [comment]
ok, it broke on #338, #337 works fine

**Comment by fgsfdsfgs** [comment]
That makes very little sense. The only thing that changed there was MSAA-related, so if you have that disabled it shouldn't even matter.

**Comment by fgsfdsfgs** [comment]
Pushed a potential fix for this. Check out the new build and see if that fixed it.

**Comment by Xii-Nyth** [comment]
yeah its working great. anything betteer would require modding the game
