### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by erikmartinessanches** [fgsfdsfgs/perfect_dark#225]
Would be fun if this supported Apple Silicon.  Alternatively DirectX (11 or 12?) support since OpenGL 2.1 is not supported in Windows 11 ARM in a VM.

**Comment by fgsfdsfgs** [comment]
What GL version is supported there? You can run this with pretty much any GL version higher than 2.1. On older Macs this would usually be 3.2 Core.
Other than that, I don't know if Silicon can run 32-bit ARM code. I also don't have any Apple devices to test it on.

**Comment by throwaway29292** [comment]
No modern macs (no matter if they are Apple SIlicon or Intel) can compile or run 32-bit applications so the 64-bit support will first need to be added.

I tried to compile it on my Ventura hackintosh. I got so far as ld saying it cannot find any symbols for i386 (almost definitely because the support was removed.)

If the 64-bit support ever gets added, i'll certainly test it on Intel macOS.

**Comment by erikmartinessanches** [comment]
> What GL version is supported there? You can run this with pretty much any GL version higher than 2.1. On older Macs this would usually be 3.2 Core. Other than that, I don't know if Silicon can run 32-bit ARM code. I also don't have any Apple devices to test it on.

If you mean which OpenGL is supported on Apple Silicon (M1), then it [appears to be 4.1](https://unlimited3d.wordpress.com/2020/12/09/opengl-on-apple-m1/). 

Interestingly, [Windows 11 or Arm that runs on Apple M1 Mac is capable of running thousands of 32-bit Windows applications that were initially developed for Intel-based systems](https://forum.parallels.com/threads/running-win-32bit-applications-on-m1-mac.361262/#post-919739).  I'm running Windows 11 arm inside UTM which doesn't support graphics acceleration, although the OpenGL Extensions Viewer does say OpenGL 1.1 and Direct X 11.4, 12.1, but probably not for real. I was unable to start Perfect Dark due to insufficient openGL version. Parallels is another virtualisation software that does support OpenGL 4.1, but I don't use that. 

> No modern macs (no matter if they are Apple SIlicon or Intel) can compile or run 32-bit applications so the 64-bit support will first need to be added.

I think[ these guys](https://www.codeweavers.com/blog/jwhite/2020/11/18/okay-im-on-the-bandwagon-apple-silicon-is-officially-cool) somehow managed.

**Comment by erikmartinessanches** [comment]
> No modern macs (no matter if they are Apple SIlicon or Intel) can compile or run 32-bit applications so the 64-bit support will first need to be added.

I think[ these guys](https://www.codeweavers.com/blog/jwhite/2020/11/18/okay-im-on-the-bandwagon-apple-silicon-is-officially-cool) somehow managed.

**Comment by throwaway29292** [comment]
Yeah that's x86 emulation that doesn't make sense on my Hackintosh where i
can just reboot into windows and use that

Dne po 6. 11. 2023 21:56 uživatel Erik Martines Sanches <
***@***.***> napsal:

**Comment by fgsfdsfgs** [comment]
>OpenGL Extensions Viewer does say OpenGL 1.1

That's almost certainly the Microsoft software fallback GL driver. For that matter, the DX11 implementation might also be software, though I doubt it since you also have DX12 in there.
GL4.1 (core or compat profile) is fine, but you might have to specify it by hand using `--gl-version 4.1` or `--gl-version 4.1core`. 
You'll likely need to figure out some Wine fuckery to run the game until 64-bit compatibility is in.

**Comment by palmerj** [comment]
Note for the moment you can get it working under parallels using Windows 11 ARM.

<img width="2168" alt="pd_parallels" src="https://github.com/fgsfdsfgs/perfect_dark/assets/580022/f49d877b-fc94-4bcd-88ac-764367ed7f5c">

**Comment by Tamasina07** [comment]
Also to add on to palmerj's note, it doesn't work in UTM using Windows 11 ARM.
<img width="1030" alt="Screenshot 2023-11-08 at 17 26 19" src="https://github.com/fgsfdsfgs/perfect_dark/assets/62822072/306a029c-b999-47fe-96c4-4e5bbdc1b866">

However, you can use Mesa3D to run the game, but at a unplayable framerate.
<img width="1021" alt="Screenshot 2023-11-08 at 17 27 00" src="https://github.com/fgsfdsfgs/perfect_dark/assets/62822072/e5bcd741-1bc4-48f4-9e4f-e1f22b7c328e">

**Comment by fgsfdsfgs** [comment]
64-bit compatibility is now in. Unfortunately I still don't have any Apple devices to build it for.

**Comment by fgsfdsfgs** [comment]
There are now automatic builds for OSX, both ARM64 and x86_64. Check the Releases section.
I will close this for now, please notify if the builds don't work.
