### ISSUE TITLE
Pelagic II - Segfault while opening reactor control hatch with Xray active

### ISSUE THREAD

**Issue by whudson** [fgsfdsfgs/perfect_dark#229]
Platform: Debian 12 (64bit)
Version: 479c033 (i686-linux)

On the mission Pelagic II when you equip the X-ray in the upstairs reactor area to press the green switches, if you press the final green switch while the xray is still equipped the game sometimes crashes. With the x-ray unequipped before pressing the final switch I have not had any crashes.

I was also able to cause a crash by pressing one of the red buttons with the Xray equipped - it may have something to do with how close you are standing to the button. I am unable to re-create this crash using the 1964 emulator.

![Screenshot_20231105_114031](https://github.com/fgsfdsfgs/perfect_dark/assets/519003/d25c07f9-8041-4d7d-bb11-e88122cfa054)

![Screenshot_20231105_114116](https://github.com/fgsfdsfgs/perfect_dark/assets/519003/357f3ee4-5a23-41b6-8343-519517f8747a)

Backtrace from GDB:
```
(gdb) bt
#0  bgTestHitOnObj (arg0=0xffffc238, arg1=0xffffc244, arg2=0xffffc250, gdl=0xd7fa2394, gdl2=0x0, vertices=0xd7fc44d0, hitthing=0xffffc33c) at src/game/bg.c:3667
#1  0x5659f8f3 in func0f0849dc (model=0xd80ca27c, nodearg=0xd816aa04, arg2=0xffffc600, arg3=0xffffc60c, hitthing=0xffffc33c, dstmtxindex=0xffffc308, dstnode=0xffffc30c)
    at src/game/propobj.c:15103
#2  0x565a1821 in func0f0859a0 (prop=0xd80d6538, shotdata=0xffffc600) at src/game/propobj.c:15638
#3  0x565a1bd4 in objTestHit (prop=0xd80d6538, shotdata=0xffffc600) at src/game/propobj.c:15705
#4  0x56656b24 in shotCalculateHits (handnum=0, isshooting=0, gunpos2d=0xffffcac8, gundir2d=0xffffcabc, gunpos3d=0xffffcae0, gundir3d=0xffffcad4, arg6=0, 
    distance=4.29483622e+09, cheap=0) at src/game/prop.c:741
#5  0x56657601 in propFindAimingAt (handnum=0, isshooting=0, context=0) at src/game/prop.c:992
#6  0x5669eec9 in lvRender (gdl=0xd7faf524) at src/game/lv.c:1202
#7  0x566d67ab in mainTick () at port/src/pdmain.c:554
#8  0x566d6e95 in mainLoop () at port/src/pdmain.c:499
#9  0x566d6ec5 in mainProc () at port/src/pdmain.c:280
#10 0x566d9bf6 in main (argc=1, argv=0xffffcd14) at port/src/main.c:146
(gdb) frame
#0  bgTestHitOnObj (arg0=0xffffc238, arg1=0xffffc244, arg2=0xffffc250, gdl=0xd7fa2394, gdl2=0x0, vertices=0xd7fc44d0, hitthing=0xffffc33c) at src/game/bg.c:3667
3667	in src/game/bg.c
```

**Comment by fgsfdsfgs** [comment]
Unfortunately I can't replicate this locally, so I have to ask you to execute some commands in gdb if possible when you get that crash again:
```
p gdl
p/x gdl->words
p numvertices
p count
p offset
p vtx
```

**Comment by whudson** [comment]
@fgsfdsfgs
```
Thread 1 "pd" received signal SIGSEGV, Segmentation fault.
bgTestHitOnObj (arg0=0xffffc238, arg1=0xffffc244, arg2=0xffffc250, 
    gdl=0xd7fb277c, gdl2=0x0, vertices=0xd7fd5fa0, hitthing=0xffffc33c)
    at src/game/bg.c:3667
3667	src/game/bg.c: No such file or directory.
(gdb) p gdl
$1 = (Gfx *) 0xd7fb277c
(gdb) p/x gdl->words
$2 = {w0 = 0x4300030, w1 = 0xd7fd6f40}
(gdb) p numvertices
$3 = 4
(gdb) p count
$4 = 0
(gdb) p offset
$5 = 16609088
(gdb) p vtx
$6 = (Vtx *) 0xd8facee0
```

**Comment by fgsfdsfgs** [comment]
Ah, I think I see the problem. Thank you.

**Comment by fgsfdsfgs** [comment]
Pushed a potential fix. See if it still crashes.

**Comment by whudson** [comment]
I just tried for about 5 minutes straight to make it crash with the latest build and I was not able to get it to happen again. Seems like that fixed it!

**Comment by fgsfdsfgs** [comment]
Alright, feel free to reopen this if it happens again,
