### ISSUE TITLE
Incorrect Co-op spawns on DataDyne Defection

### ISSUE THREAD

**Issue by LanHikariDS** [fgsfdsfgs/perfect_dark#23]
When playing dD-Defection in co-operative mode, the Player 2 character spawns in the wrong location, appearing in front of Joanna and becoming stuck inside her. While I haven't compared the other levels' spawn locations with the original game, the rest of Mission 1's levels
_can_ at least be played without teamkilling
https://github.com/fgsfdsfgs/perfect_dark/assets/42668580/678441e4-d5f2-46d4-bae9-fef596c90f9d

**Comment by fgsfdsfgs** [comment]
Looks like they work properly on every single SP level other than Defection. Interesting.

**Comment by fgsfdsfgs** [comment]
Should be fixed now.

**Comment by Graslu** [comment]
This also happens in Area 51: Escape. This is the correct spawn, however on N64 and 1964 GEPD, the AI will unstuck themselves after a second or so. In here you have to make them go stealth mode or turn very quickly to get out.

![Base Profile Screenshot 2023 09 03 - 18 49 27 26](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/ab0494ad-9306-47ae-9748-54298ae4e2ea)
