### ISSUE TITLE
eeprom.bin with 100% save

### ISSUE THREAD

**Issue by LDAsh72** [fgsfdsfgs/perfect_dark#232]
For the 3 people that might be interested, I played through and unlocked all the missions and cheats. The only thing I couldn't do is some of the more difficult challenges in the combat simulator. There are only a few hundred times I can be instantly shot in the face as soon as an enemy pixel appears behind a corner. So, a couple of the multiplayer maps are not unlocked, but singleplayer is 100%.
https://www.violae.net/temp/pd23eep.zip

**Comment by fgsfdsfgs** [comment]
Here's a [100% save](https://github.com/fgsfdsfgs/perfect_dark/files/13311803/eeprom_full.zip) courtesy of Graslu00.
That said, this isn't really an issue so I'll close this.
