### ISSUE TITLE
[Suggestion] Program icon

### ISSUE THREAD

**Issue by OpenRift412** [fgsfdsfgs/perfect_dark#238]
I extracted the icon from 1964 GEPD edition, could be a good icon, at least until someone makes a custom one.
[pd-icon.zip](https://github.com/fgsfdsfgs/perfect_dark/files/13341805/pd-icon.zip)

**Comment by Nioh8** [comment]
I converted this icon for mine 
[pd ico.zip](https://github.com/fgsfdsfgs/perfect_dark/files/13343180/pd.ico.zip)

**Comment by Alexkander66** [comment]
![mqdefault](https://github.com/fgsfdsfgs/perfect_dark/assets/144574408/0b08a040-0b75-4b9d-80fa-78e64df1f794)

Just giving my opinion, I don't think it's right for you to use the N64 logo for the PC version. It would be better if the logo were distinctive of the N64 version, a bit like on the XBLA version.

**Comment by OpenRift412** [comment]
> ![mqdefault](https://user-images.githubusercontent.com/144574408/282635926-0b08a040-0b75-4b9d-80fa-78e64df1f794.jpg)
> 
> Just giving my opinion, I don't think it's right for you to use the N64 logo for the PC version. It would be better if the logo were distinctive of the N64 version, a bit like on the XBLA version.

It's not the N64 logo. It's an uppercase P and a lowercase d put together in a fashion that looks like an N so it transitions well from the N64 logo to the Pd logo. But yeah, I think the Box art eye might be a better fit.

**Comment by OpenRift412** [comment]
> > ![mqdefault](https://user-images.githubusercontent.com/144574408/282635926-0b08a040-0b75-4b9d-80fa-78e64df1f794.jpg)
> > Just giving my opinion, I don't think it's right for you to use the N64 logo for the PC version. It would be better if the logo were distinctive of the N64 version, a bit like on the XBLA version.
> 
> It's not the N64 logo. It's an uppercase P and a lowercase d put together in a fashion that looks like an N when it transitions from the N64 logo to the Pd logo. But yeah, I think the Box art eye might be a better fit.

**Comment by cylonicboom** [comment]
I just download a 🧀 png and set that as my game icon

**Comment by fgsfdsfgs** [comment]
There might be some potential legal issues to take into account, though I really doubt anyone is going to care about a goddamn icon.

**Comment by TheUser912** [comment]
![logo](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/47463f27-165f-4ddd-82cf-f4c3fe6e22b9)
I made a unique render of the "PD" symbol logo from scratch to at least make it distinct compared from the icon used in 1964 GEPD.
I do feel the icon using the box art eye is better, but it's also legally risky.

**Comment by OpenRift412** [comment]
> ![logo](https://user-images.githubusercontent.com/130617241/282846721-47463f27-165f-4ddd-82cf-f4c3fe6e22b9.png) I made a unique render of the "PD" symbol logo from scratch to at least make it distinct compared from the icon used in 1964 GEPD. 

I like it, tho idk how well it scales down in smaller sizes like 16x16.

>I do feel the icon using the box art eye is better, but it's also legally risky.

I mean, maybe? On the other hand though, what makes you think that's any more legally risky than the nature of this project as a whole?

**Comment by fgsfdsfgs** [comment]
> On the other hand though, what makes you think that's any more legally risky than the nature of this project as a whole?

That much might be true, but this repo does not contain any copyrighted graphical assets, so it makes some sense to keep it that way.
That said, good point about the smaller sizes. I believe modern Windows icons usually have variants in 16x16, 32x32, 48x48, and optionally 256x256, probably in a single ICO file.

**Comment by Kroc** [comment]
For small sizes, create a version without the 3D tilt, i.e. face-on, and that should scale down cleanly.

**Comment by ghost** [comment]
> There might be some potential legal issues to take into account, though I really doubt anyone is going to care about a goddamn icon.

Doubt it even matters. Cleaned up decompiled code is already a risk, so how is a icon any different? Just go with it.

**Comment by Kroc** [comment]
Code is a matter of copyright, logos are a matter of trademark. Clean-room decompiled code is 100% safe. With Microsoft owning Rare assets, trademark is a different matter.

**Comment by ghost** [comment]
Hahahahahaha, don't tell me this is "clean room".

It isn't. It maybe be decompiled, but it certainly isnt clean room. Cleaning up the results from a decompiler by hand isn't at all clean-room: it has a distinct legal meaning. Cleaning up results from IDA Pro/Ghidra/some other decompiler, and throwing on GitHub doesn't change the copyright.  "Clean room" would be someone decompiling and writing a natural language document explaining how the software works, without any code attached. And then someone entirely unrelated to that process reimplementing from scratch using those design specs, by hand.

This certainly isn't clean room. Don't tell me it is. Especially when this is a fork from the N64 decompiled code.

**Comment by fgsfdsfgs** [comment]
My logic is just "I'd rather not make it any worse than it (maybe) already is".
I might pick one of the icons posted here later when I get around to it. In the meantime, remember that in Windows you can set custom icons for shortcuts.

**Comment by ghost** [comment]
> My logic is just "I'd rather not make it any worse than it (maybe) already is". I might pick one of the icons posted here later when I get around to it. In the meantime, remember that in Windows you can set custom icons for shortcuts.

One of the most sensible replies I seen :) Yeah, thats 100% true.

**Comment by NicNamSam** [comment]
I manipulated the original logo, which consists of a "PD" (while also making an "N") to say "PC" because it's the PC port. It's an idea for the logo for others to build upon if they want. It can be improved. The thing about the original design is that the "PD" letters weren't very obvious; it was a sneaky design. I think most people saw the "N" first. So it may not be clear that it even says PC. And the colors don't stand out much, but I wanted it to be merely an edit of the original design. Just a possible idea.
![PDPC](https://github.com/fgsfdsfgs/perfect_dark/assets/57078513/745003b3-de90-43bd-b7a6-760f0aa4c8b6)

Edit: ICO file [here](https://www.steamgriddb.com/icon/48153)

**Comment by PeeMoldy** [comment]
> I manipulated the original logo, which consists of a "PD" (while also making an "N") to say "PC" because it's the PC port. It's an idea for the logo for others to build upon if they want. It can be improved. The thing about the original design is that the "PD" letters weren't very obvious; it was a sneaky design. I think most people saw the "N" first. So it may not be clear that it even says PC. And the colors don't stand out much, but I wanted it to be merely an edit of the original design. Just a possible idea. ![PDPC](https://private-user-images.githubusercontent.com/57078513/292335081-745003b3-de90-43bd-b7a6-760f0aa4c8b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMDIwNDgsIm5iZiI6MTcwMzIwMTc0OCwicGF0aCI6Ii81NzA3ODUxMy8yOTIzMzUwODEtNzQ1MDAzYjMtZGU5MC00M2JkLWI3YTYtNzYwZjBhYTRjOGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDIzMzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZjM5ZTdhZmJkZjljMWZiZGEyZWJlM2YyMGQzZTZjZDEzNDcyZDliNWNkNmJiNDNmZjFmMzExNDhlZTgwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UUnLLjCCatl6LNqZu1f1amwp6_hnvOdFeXYbEC1a5kU)

That is nice! You did that with GIMP?

**Comment by NicNamSam** [comment]
> That is nice! You did that with GIMP?

Photoshop

**Comment by PeeMoldy** [comment]
> > That is nice! You did that with GIMP?
> 
> Photoshop

Someone needed help on something, how can I get ahold of you?

**Comment by BiatuAutMiahn** [comment]
I like the one from #374

**Comment by fgsfdsfgs** [comment]
This is now a thing. Uses the icon provided by NicNamSam above. Thanks.
