### ISSUE TITLE
Forward and back controls not working in Control mappings 1.1 and 1.3

### ISSUE THREAD

**Issue by Chunkywolf** [fgsfdsfgs/perfect_dark#239]
When setting the controls to 1.1 or 1.3, up and down navigate through the menus, but do not move the character forward and back in the game. I tried both keyboard, and a n64 controller with a 8bitdo mod. This was using the most current version autobuild C/C++ CI #390 on windows.

**Comment by fgsfdsfgs** [comment]
Those control schemes aren't really supported at the moment. All the modifications to controls are done to 1.2, so it probably borked the other schemes. There are plans to move the current modded control scheme to a separate one and that's likely when they will be restored.
For now, in Advanced options there is a menu that lets you rebind controls.

**Comment by fgsfdsfgs** [comment]
I've added (partial?) support for the original control schemes, so this should work correctly now. The "PC port" control scheme that the port had before is now a separate scheme called Ext and is the default. Note that if you change to an N64 scheme you'll have to rebind some buttons.

**Comment by Chunkywolf** [comment]
As far as I can tell, things are working correctly.  I had to disable the 2nd joystick by setting both sensitivities on it to 0, and there are minor issues with interacting with computers in the institute on load.  Once you play a level, everything in the institute seems to work correctly. I am unsure if this is related, but I have only tried this with my n64 control so far since it was working well. Thanks for the great work!

**Comment by fgsfdsfgs** [comment]
You can also enable/disable "Analog Movement" in the controller settings, this toggles whether the left stick on your controller simulates the C buttons.
What kind of issues are you having with the computer?

**Comment by Chunkywolf** [comment]
I guess it's working correctly, and was probably just my poor memory of the original game, The computers did not allow interaction until after Daniel Carrington walks you around the institute, or you play a mission.

**Comment by fgsfdsfgs** [comment]
Alright, thanks for testing. Closing this since the control schemes seem to work fine.
