### ISSUE TITLE
Add an option to skip intro screens

### ISSUE THREAD

**Issue by Calinou** [fgsfdsfgs/perfect_dark#242]
To get into the game quicker, there could be an option to skip intro screens and the intro cutscene and get to the profile selection screen directly. Perhaps you could even pick a profile to be loaded automatically when the game starts.

This could also be exposed as a CLI argument when you only want to use this for development purposes (unless there's a generic CLI argument to set any setting for a single session).

**Comment by Alexkander66** [comment]
I'm not a fan of deleting start-up intros, it's part of the charm of the game, and frankly, to save 5 seconds. In short, for me, it's a waste of time.

**Comment by fgsfdsfgs** [comment]
This will be an option. I won't outright delete anything.

**Comment by fgsfdsfgs** [comment]
Well, turns out you could already do this by passing `--boot-stage 0x26`, where `0x26` is the number of the training stage.
Should I add a config setting and a shorthand argument like `--skip-intro` as well?

**Comment by fgsfdsfgs** [comment]
Well, added regardless.
Either use `--skip-intro` on the command line or set `Game.SkipIntro` to `1` in `pd.ini`.
