### ISSUE TITLE
Save Game Location

### ISSUE THREAD

**Issue by Havoc1001** [fgsfdsfgs/perfect_dark#249]
Where does the game save to? A friend and i want to play on my game at my house, can he bring his game save to my place?

**Comment by fgsfdsfgs** [comment]
On Windows there should be a file called `eeprom.bin` next to `pd.exe`. If it's not there, check `C:\Users\YourUsername\AppData\Roaming\perfectdark`.

**Comment by Havoc1001** [comment]
I'm new at this....How would i extract the save file from one computer to be able to play that save on a different computer?

**Comment by fgsfdsfgs** [comment]
You just copy the file called `eeprom` to the other computer and put it in the game folder. Or copy the whole folder that the game is in.

**Comment by Havoc1001** [comment]
Just override the one i have on my PC?

**Comment by fgsfdsfgs** [comment]
Yes.

**Comment by Havoc1001** [comment]
Thank you sir. Love the port and Thank you again.

**Comment by DrCarrol** [comment]
how about linux? where does that save to?

**Comment by fgsfdsfgs** [comment]
`~/.local/share/perfectdark` by default.
