### ISSUE TITLE
Question about Multiplayer

### ISSUE THREAD

**Issue by Havoc1001** [fgsfdsfgs/perfect_dark#254]
Not sure if this has been asked, will this ever have online multiplayer?...Or is that even possible?

**Comment by fgsfdsfgs** [comment]
Originally I started this port because I wanted to eventually add multiplayer, but doing so is a very large task, and that's on top of maintaining the port itself. Maybe eventually I'll get around to it, or someone else will beat me to it.
For now I'll close this issue.
