### ISSUE TITLE
[Feature Request] Toggleable Goldeneye 007 style intermittent muzzle flashes

### ISSUE THREAD

**Issue by PeeMoldy** [fgsfdsfgs/perfect_dark#259]
https://youtu.be/mccd7EVx9mk

https://youtu.be/hAVp7LxtadE

https://youtu.be/RizDcxdNDXQ

These videos by HackBond show what I'm talking about. Is there a way to make a togglable option to have intermittent, flickering Goldeneye 007 style muzzle flashes replace the Perfect Dark style ones in the port?

**Comment by fgsfdsfgs** [comment]
You mean just like flash them in and out of existence every other frame?

**Comment by PeeMoldy** [comment]
> You mean just like flash them in and out of existence every other frame?

Yes exactly, just like Goldeneye does it, instead of PD's "flamethrower" style of muzzle flash where it always stays on the screen but just changes shape. I always preferred Goldeneye's muzzle flashes, as I thought they look more realistic. Could the intermittent disappearing MFs be done both in 1st and 3rd person?

**Comment by PeeMoldy** [comment]
Closing issue, as this has been added, but some bugs reported here need to be worked out.

https://github.com/fgsfdsfgs/perfect_dark/issues/310
