### ISSUE TITLE
Game world squished compared to the N64 and Xbox 360 versions.

### ISSUE THREAD

**Issue by UncookedMoa** [fgsfdsfgs/perfect_dark#260]
So I noticed that the entire game world (including weapon models and such) seems to be squished (the HUD itself is fine). The Xbox 360 version also matches simple64's emulation, and my eyes tell me that the way simple64 and the Xbox 360 looks is the intended appearance for the game. The screen squish also allows the player to see more horizontally, even when the vertical FoV seems to match.

Would be nice to have this issue fixed in the port.

**N64 (via simple64):**
![2023-11-30_091377](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/95f3c4b8-6f3a-4e11-8c5d-cfd3ab763e18)

**PC Port (cropped to 4:3):**
![2023-11-30_094733_1440](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/8866a520-17f4-4d85-8d12-02f28da460d1)

**Raw 16:9 PC Port Screenshot:**
![2023-11-30_094733](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/85f99906-3775-42da-9e00-671b6a1b8ef3)

**Xbox 360 version:**
![Perfect Dark-2023_11_30-05_17_10](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/9f2c28fd-2af9-4416-91d8-9ab20e660d66)

----------------

To note, 1964 GEPD also shares the same issue. The way the game world squishes matches the PC port. When set to 4:3, 1964 further squishes the game. The readme makes several mentions of the 1964 emulator, though I have no idea if they could be connected.

**1964 GEPD at 16:9:**
![Base Profile Screenshot 2023 11 30 - 15 34 11 14](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/74cc8224-4ea6-4cbc-a293-0fbf70f9cc2e)

**1964 GEPD at 4:3:**
![Base Profile Screenshot 2023 11 30 - 15 37 58 39](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/115a07ed-9ded-4b7c-9c2b-56aa5b58f46d)

**NOTE:** An additional observation is that the textures on the back wall of these screenshots seem to be tiled in the same way across the PC port, Xbox 360, and the 1964 emulator, where the texture tiles as rectangles, but this differs from the N64 original, which tiles the texture as squares. Gameplay on native hardware indicates that simple64 is emulating this correctly ([NTSC footage](https://youtu.be/lmwOnRdChOw&t=34) [PAL footage](https://youtu.be/NtK6VttAxqU&t=91))

**Comment by UncookedMoa** [comment]
To note, 1964 GEPD also shares the same issue. The way the game world squishes matches the PC port. When set to 4:3, 1964 further squishes the game. The readme makes several mentions of the 1964 emulator, though I have no idea if they could be connected.

1964 GEPD at 16:9:
![Base Profile Screenshot 2023 11 30 - 15 34 11 14](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/74cc8224-4ea6-4cbc-a293-0fbf70f9cc2e)

1964 GEPD at 4:3:
![Base Profile Screenshot 2023 11 30 - 15 37 58 39](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/115a07ed-9ded-4b7c-9c2b-56aa5b58f46d)

**Comment by fgsfdsfgs** [comment]
The tiles are in fact rectangular on N64 (or at least on simple64), they're just hard to see because it's low res and slathered in AA and dithering:
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/2997482/5adc3856-0502-4d0a-8a5a-75c97f32743b)

As for the main issue, I suspect that's because the original game renders at 320x220 instead of 320x240, so when it's upscaled to a "normal" aspect ratio it ends up kind of stretched. Here's a comparison of normal vs tricking the renderer into thinking it's actually 320x240, both set to 640x480:

Normal:
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/2997482/572b185e-fc17-4ac2-a0b7-d1bfee39021a)

Hacked:
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/2997482/926f436f-a368-4e6c-a3be-bfb09e9557c6)

As you can see, the second example approximately matches the size of the N64 viewport, whereas in the first one it appears to be "stretched" to cover the whole 480 lines.

I suppose this is possible to fix by enforcing proper 320x240 on the game side, though it might be tricky.

**Comment by fgsfdsfgs** [comment]
I've pushed an experimental fix for this. It could break something, but so far I haven't noticed any issues. Let me know if the game looks correct to you now.

**Comment by UncookedMoa** [comment]
Nice! The game world definitely looks right to me. As for the wall, I should have looked more closely at the tiles on simple64 before adding that additional observation lol. I was really wondering why I didn't notice it earlier when I was looking through the screenshots. I didn't upscale for more clarity just in case there was a bug with upscaling _somehow_, but I guess I should have taken both with and without upscaling.

Anyway, now that the game world looks right, I'm looking more closely at the HUD. I took screenshots of the 640x480 4:3 window the port launches in and cropped them for these. For the simple64 shots I cropped out the overscan through Photoshop and it does seem like it runs in 320x220 (though cropping a full screen simple64 screenshot gave me 320x223 instead), so they're a little narrower compared to the 4:3 port screenshots. 

The HUD elements on the bottom right ended up getting squished vertically when they were fine in the previous build. This is a new issue caused by the changes. You can notice that in the previous build, the crosshair had the correct height, but was squished horizontally. In the current build, it seems to look right, but it's slightly smaller than the N64 (as you can tell in the upscaled screenshot), since it's been squished both vertically and horizontally. It's easier to tell when you swap between both images back and forth between two tabs. It also seems like those HUD elements on the bottom right are slightly squished horizontally in the previous build though. In the new build, they were also squished vertically too, so it ends up just being smaller now. It seems like it has the same issue as the crosshair, and so it needs to be resized back up again.

**N64 (via simple64):**
![simple64 Desktop Screenshot 2023 12 01 - 09 25 56 81_crop](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/0fb06d8a-d38f-446d-a6ba-b5dddb9a9b52)

**N64 (4x upscaled via simple64):**
![simple64_upscale Desktop Screenshot 2023 12 01 - 09 27 15 28_crop](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/c183dd8c-89d4-42e6-b38f-af5603d80269)

**Previous build [Nov. 27] (4:3 window):** 
Issues: Game world squish, and crosshair squished horizontally. Bottom right HUD elements slightly squished horizontally.
![Previous build 2023-12-01_094109](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/20eea810-23cc-4292-8e47-44845e91d140)

**Current build [Nov. 30] (4:3 window):** 
Issues: Crosshair smaller due to being squished both vertically and horizontally. Bottom right HUD elements seem to be just smaller due to being squished both vertically and horizontally. Maybe just needs to be made larger?
![New build 2023-12-01_093247](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/d8ec3087-0c7b-45f9-94ee-02e50bf4d757)

I also ended up really noticing the crosshair now, which became more obviously stretched horizontally to me in widescreen once the game world looked about right. This issue actually already existed in the previous build. In these screenshots you can tell that the crosshair got squished vertically after the previous build too. Widescreen stretch needs to be fixed for the crosshair.

**Previous build [Nov. 27] (widescreen):** 
Issues: Game world squish, and crosshair stretched horizontally. Only slightly squished vertically. Bottom right HUD elements slightly squished horizontally.
![Previous build_wide Base Profile Screenshot 2023 12 01 - 09 08 26 100](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/1d00011e-37fc-42a6-a3c3-1c5ca2bd95ad)

**Current build [Nov. 30] (widescreen):** 
Issues: Crosshair stretched horizontally, and further squished vertically compared to previous build, making it appear to be just smaller now. Same issue exists with the bottom right HUD elements. Maybe just needs to be made larger?
![New build_wide Base Profile Screenshot 2023 12 01 - 09 08 57 29](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/47ce159d-589b-4e6f-b81f-4555f9ed7eec)

**Comment by UncookedMoa** [comment]
I managed to resize the window to match my simple64 screenshots and it's much clearer what's going on with the HUD on the bottom left.

**Previous build [Nov. 27] simple64 size (TextureFilter2D = 0):**
Issues: World squish, HUD squished horizontally.
![Previous build with texturefilter2d0 2023-12-01_093247_Simple64scale](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/4d582ae7-5715-4b8e-901c-8e25db117b41)

**Current build [Nov. 30] simple64 size (TextureFilter2D = 0):**
Issues: HUD smaller than N64, with a vertically squished crosshair. The crosshair seems slightly smaller horizontally too.
![New build with texturefilter2d0 2023-12-01_093247_Simple64scale](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/a3888933-0e80-4708-a205-695bbff07508)

There's also still the issue of the widescreen stretch of the crosshair as shown in the previous comment that isn't shown here.

**Comment by UncookedMoa** [comment]
So I thought about checking the HUD overlays for the CamSpy and the IR scanner. The update seems to have completely messed up the CamSpy HUD elements. I'm not sure what to really point out when basically everything is off. The previous build did seem close, though it was a little smaller compared to my simple64 shot here. The fish eye effect seems to also be different, but that might just be the size of the circle?

N64 (via simple64) 4x upscaled:
![simple64 upscale Desktop Screenshot 2023 12 01 - 13 48 22 87](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/17a4314f-bb92-4ced-b7fb-43444528f19b)

**Previous build [Nov. 27]:**
![Previous build_43 Base Profile Screenshot 2023 12 01 - 13 38 16 43](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/34f9b81c-04e9-4512-ac0e-1c4d4e0fd6b0)

**Current build [Nov. 30]:**
![New build 43 Desktop Screenshot 2023 12 01 - 14 09 48 07](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/1685af28-448d-43dc-912b-9a982de6bfe6)

Widescreen has no point of reference for scaling (the original's widescreen option stretched the HUD elements, and the 360 version stretches them as well), and it can be difficult since it was clearly made for 4:3. I think it would be a good idea to add a separate "HUD overlay centering" option for these. The reason why HUD centering and overlays should be separate is so that one can choose to have a scaled widescreen HUD at the edges, while also having a 4:3 centered overlay if they so choose. When set to "none" or "wide", the behavior of the previous build can be kept, as it matches the behavior of the 360 version and N64 version in widescreen.

N64 (via simple64) widescreen:
![simple64 wide Desktop Screenshot 2023 12 01 - 17 17 42 12](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/992eff5a-d29e-4155-811f-9a0ba7e6de03)

**Previous build [Nov. 27]:**
![Previous build_nochange Base Profile Screenshot 2023 12 01 - 13 38 16 43](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/823b81b8-082b-4667-b4e9-87cc8f9914ec)

**Current build in widescreen [Nov. 30]:**
![New build_nochange Base Profile Screenshot 2023 12 01 - 13 37 44 58](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/4968d276-48aa-4ba3-a3a0-f91d77dceaaf)

**Xbox 360 version:**
![Perfect Dark-2023_12_01-07_48_45](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/92a4e2ff-eb6d-4d43-9db2-ea80c6c6cf1a)

The IR scanner seems to basically share the same issue as the CamSpy, but without any HUD elements, it doesn't get as affected.
N64 (via simple64) 4x upscaled:
![simple64 upscale IR scanner Desktop Screenshot 2023 12 01 - 14 40 01 91](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/cefd47b0-fd15-42c5-9d83-575d246060b9)

**Previous build [Nov. 27]:**
![Previous build 43 2023-12-01_160412](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/79c24ad1-6b8e-466e-8fc1-7ad9bd4173a1)

**Current build [Nov. 30]:**
![New build 43 2023-12-01_161459](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/d166055f-1f98-4705-8a54-d29776f39f30)

**Current build in widescreen [Nov. 30]:**
![New build IR Scanner Base Profile Screenshot 2023 12 01 - 14 15 49 00](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/25bccb2e-9abe-4cc2-9dde-9290a2fd3751)

**Comment by UncookedMoa** [comment]
Just thought about looking at the main menu and the radial weapon menu, and sure enough, the same issue is present on them. The menu overall looks smaller now compared to the original, while in the previous build, although it was correct vertically, it looked squished.

**N64 (via simple64) 4x upscaled:**
![simple64 2023-12-01_204934](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/82817bb0-9171-4822-aadf-5bd842b239eb)
![simple64 2023-12-01_204957](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/41d66db2-cff6-47c9-a6d8-c6069db0d48d)
![simple64 2023-12-01_205052](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/675007cb-8225-402e-8410-dc18de16801d)

**Previous build [Nov. 27]:**
![Previous build 43 2023-12-01_204055](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/fde9ba04-c63d-4c77-aee9-e36aca4a7a25)
![Previous build 43 2023-12-01_204111](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/3b6770ee-705b-4845-aca5-f8008a13de94)
![Previous build 43 2023-12-01_204132](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/83417fa5-f309-4da7-83fe-df2ca29643a3)

**Current build [Nov. 30]:**
![New build 43 2023-12-01_203917](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/c2d436fe-ce92-445a-879e-e5da70484400)
![New build 43 2023-12-01_203931](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/0ded7e96-315c-4c47-a766-4381ced5f689)
![New build 43 2023-12-01_203949](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/0b4cdf51-2ada-44fc-b8bc-29af69080faf)

**Current build in widescreen [Nov. 30]:**
![New build Base Profile Screenshot 2023 12 01 - 20 34 35 40](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/9eb01ec4-e481-47b7-827f-6585f7f9b593)

**Comment by fgsfdsfgs** [comment]
Fixed this in a different way. Now it should only affect the 3D parts of the game.

**Comment by UncookedMoa** [comment]
> Fixed this in a different way. Now it should only affect the 3D parts of the game.

Wow! This looks really, really good and at a glance, it looks perfect, but on closer inspection, it seems like the HUD is little bit squished compared to the original. (Drawing a perfect square over the weapon mode square shows the new build is a little bit more rectangular than the original game, which does fit a perfect square).

![2023-12-02_103225_square](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/47c60e65-11ad-455c-9470-cd0eee10d16f)

**N64 (via simple64):**
![2023-12-02_102307](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/f5f72372-01ed-44bc-85e7-519cc7a38bfe)

**Current build:**
Issues: Slightly squished HUD.
![2023-12-02_103225](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/2a777622-ed44-45ee-8044-88ccd1ef0301)

**Current build in widescreen:**
Issues: Stretched crosshair. Slightly squished HUD.
![Base Profile Screenshot 2023 12 02 - 10 04 10 08](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/2c41e8f6-9b35-43be-9fc3-7d5e4a4dfaf3)

Would also like to point out that the menu robot wire/arm thing on the left gets more and more squished the wider your aspect ratio, though it seems fine when the aspect ratio is the same as the original. Seems like a similar issue to the crosshair, though I do understand that for the "wire" to reach the screen, it'd have to stretch out though, so this is kind of a complicated issue. Somehow, the Xbox 360 version managed to get the 4:3 look for it, even at 16:9, but they may have just created another asset for it instead.

**N64 (via simple64):**
![2023-12-02_102253](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/cc330a69-9ab0-49e3-aacc-95c6f108948d)

**Current build:**
![2023-12-02_103210](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/89689961-1321-498a-bf87-478b4a929887)

**Current build in 16:9:**
![Base Profile Screenshot 2023 12 02 - 10 02 30 80](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/ddf97d24-9ce3-4618-a5c4-8d84d2037b8c)

**Current build in 21:9:**
![2023-12-02_105434](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/a9d501c8-b18c-48f0-b253-ed7763f87e92)

**Current build in an extremely wide window:**
![2023-12-02_105219](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/ffa5c83c-7d5c-4114-9e3b-8c8ddadeb7aa)
