### ISSUE TITLE
Crosshair is horizontally stretched

### ISSUE THREAD

**Issue by StrikerTheHedgefox** [fgsfdsfgs/perfect_dark#269]
Your crosshair (and the classic one from goldeneye when aiming with its weapons) are a bit horizontally stretched. Looks like the aspect ratio needs correcting.

**Comment by UncookedMoa** [comment]
Yeah, the crosshair stretches more and more the wider the aspect ratio. Conversely, the main menu's robot arm thing on the left squishes the wider your aspect ratio is too ([https://github.com/fgsfdsfgs/perfect_dark/issues/260#issuecomment-1837016828](https://github.com/fgsfdsfgs/perfect_dark/issues/260#issuecomment-1837016828)).

**Comment by fgsfdsfgs** [comment]
Added an experimental fix for at least some of the crosshairs. Note that this also makes all the sight-related graphics be centered 4:3. Extending the horizontal lines on some of the sights is probably required, but it does look a little weird.

**Comment by UncookedMoa** [comment]
> Added an experimental fix for at least some of the crosshairs. Note that this also makes all the sight-related graphics be centered 4:3. Extending the horizontal lines on some of the sights is probably required, but it does look a little weird.

It's actually squished now, along with the rest of the HUD. I think it'd look really nice once it's all unsquished to match the N64 version. I'd actually really like having the N64 sights on widescreen, but they're squished right now. Here's a gif to very clearly illustrate the issue. It also seems like parts of the HUD like the numbers are too bright compared to the original?

![PerfectDarkSightSquish](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/151500eb-edd2-43fa-a1ce-f847dbcfbe68)

**Comment by fgsfdsfgs** [comment]
Pushed a change that should probably fix this. Wait for the autobuild to finish before you try it, as usual.

**Comment by UncookedMoa** [comment]
> Pushed a change that should probably fix this. Wait for the autobuild to finish before you try it, as usual.

It's a little teeny tiny bit closer to the center than the original, but it's all scaled properly now and you'd only notice something is off by comparing with the original. Thank you!

![Perfect Dark HUD comp](https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/de6f0012-5d3a-4daf-a811-7dd37619694b)

**Comment by fgsfdsfgs** [comment]
There are other small scaling issues that will require me to implement integer scaling for the HUD, but I'll close this one then.
