### ISSUE TITLE
Scroll Wheel bindings don't work

### ISSUE THREAD

**Issue by Phnod** [fgsfdsfgs/perfect_dark#27]
`VK_MOUSE_WHEEL_UP` and `VK_MOUSE_WHEEL_DN` don't appear to work inside the kbbinds. Looking it up it seems like they'd need to be handled inside the `SDL_PollEvent` as a `SDL_MOUSEWHEEL` event and grab the `event.wheel.y` value? My experience with regular C projects is a little lacking and I'm struggling to figure out how to link the values properly back to the input file, and if there's a proper way to access the values.

**Comment by fgsfdsfgs** [comment]
Ah yeah, I forgot to implement that. Will fix eventually.

**Comment by fgsfdsfgs** [comment]
Should be fixed now.
