### ISSUE TITLE
Mouse Control Issues

### ISSUE THREAD

**Issue by Mimiq79** [fgsfdsfgs/perfect_dark#271]
Every time the game is opened and I load into the first mission, the fire button is stuck on and empties the clip. I can get to stop by opening the weapon wheel, but then I am unable to fire or use the aim mode.

**Comment by fgsfdsfgs** [comment]
Do you have a controller connected?

**Comment by Mimiq79** [comment]
THAT WAS IT!! I feel dumb now, but thank you so much for the reply and everything y'all are doing for this game!!
