### ISSUE TITLE
Flare Effects Not Rendering Properly

### ISSUE THREAD

**Issue by MUL1NSK1** [fgsfdsfgs/perfect_dark#272]
The flare effects in the current build are not functioning correctly, leading to two major issues:

1. Flares from lamps are penetrating through weapon models in various levels.
2. Flares from the sun are visible through the ship in the intro sequence of "Carrington Villa" and are also passing through walls and other objects.

**Comment by fgsfdsfgs** [comment]
There's an issue that includes these already at #26, so I'll close this.
