### ISSUE TITLE
Crosshair Misalignment

### ISSUE THREAD

**Issue by MUL1NSK1** [fgsfdsfgs/perfect_dark#273]
The crosshair appears to be slightly off-center or shifted to the south-east .

This becomes noticeable when: 
- The zoom window of the Sniper Rifle aligns with the crosshair (fully zoomed in).
- Laser sight/point on the Falcon 2

**Comment by fgsfdsfgs** [comment]
The crosshair aspect fix might have partially fixed this as well.

**Comment by MUL1NSK1** [comment]
Unfortunately not. Still off-center.

But this was also in the n64 version but not a problem at that low resolution and with crosshair sway.


I know it might seem a bit nitpicky, but here are a few screenshots for better visualization (crosshair sway 0/off):
![Screenshot from 2023-12-05 20-32-40](https://github.com/fgsfdsfgs/perfect_dark/assets/152694903/fcf3fca1-1f89-4913-acc8-29a7d27253e6)

![Screenshot from 2023-12-05 20-34-02](https://github.com/fgsfdsfgs/perfect_dark/assets/152694903/039d359e-d08d-4626-8dcc-55aa93c315fe)

Shots are landing where the red dot indicates, rather than at the crosshair.:
![Screenshot from 2023-12-05 20-36-51](https://github.com/fgsfdsfgs/perfect_dark/assets/152694903/fd8493be-eac8-4ff1-8a13-73910ebf3548)

![Screenshot from 2023-12-05 20-46-52](https://github.com/fgsfdsfgs/perfect_dark/assets/152694903/c3485fa9-a0cf-4570-9da9-0e623f2b1e25)

**Comment by Graslu** [comment]
Can confirm it gets worse the further you get from the center

![Base Profile Screenshot 2023 12 07 - 15 39 05 66](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/e8c90429-af7c-4fb3-91ce-e0953c0c1c42)

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/cd1b5711-82f3-4e4b-9aef-c8972271960a)

**Comment by fgsfdsfgs** [comment]
> Can confirm it gets worse the further you get from the center

Looks like that was introduced when I pushed the second aspect correction fix. I don't remember this happening before.
EDIT: Pushed a fix for this. As usual, wait for the autobuilds to finish before downloading.

**Comment by Serenissima697** [comment]
Still seems to be happening with the Falcon 2 for me, it's noticeable with the laser sight - same deviation of the red dot being in the top left. Of course, if this was in the original N64 and just not noticeable because of the control schemes of the time, that might be harder to fix if it's even considered desirable to!
