### ISSUE TITLE
Clipping of Player Weapon Model through Objects 

### ISSUE THREAD

**Issue by MUL1NSK1** [fgsfdsfgs/perfect_dark#275]
I have noticed an issue where the weapon model clips through certain objects such as switches, shelves, and walls. Despite trying different Field of View (FOV) settings, the problem persists. It's worth mentioning that this clipping phenomenon was not present in the N64 version.

**Comment by fgsfdsfgs** [comment]
There is already an [issue](https://github.com/fgsfdsfgs/perfect_dark/issues/18) for this, so I'll close this one.
