### ISSUE TITLE
Linux Version on Steamdeck Crashes Often

### ISSUE THREAD

**Issue by SnoopKatt** [fgsfdsfgs/perfect_dark#277]
I gave this a whirl on Steamdeck, and while I can get it to boot, it does crash pretty often. I haven't gotten past the Villa as a result. It crashes by just hanging on the last drawn screen, and then I need to force close the game. 

I don't have issues on the Windows version using Proton on Steamdeck.

**Comment by fgsfdsfgs** [comment]
There was a [similar report](https://github.com/fgsfdsfgs/perfect_dark/issues/219) before, this might be related. Does this sound similar to what you're experiencing?

**Comment by SnoopKatt** [comment]
> There was a [similar report](https://github.com/fgsfdsfgs/perfect_dark/issues/219) before, this might be related. Does this sound similar to what you're experiencing?

Ahh I thought I checked all the prior issues but I guess I missed this one. Sorry about that!
