### ISSUE TITLE
Can't change CamSpy elevation while using the mouse and keyboard.

### ISSUE THREAD

**Issue by UncookedMoa** [fgsfdsfgs/perfect_dark#279]
On controllers, the CamSpy's elevation can be changed by moving the right thumbstick up and down, but on mouse and keyboard, it makes you look up and down instead. I think it would be nice to either replace the vertical mouse look with elevation control, or have separate CamSpy move up/down bindings.

**Comment by fgsfdsfgs** [comment]
Hold right click and move your mouse.

**Comment by UncookedMoa** [comment]
Oh, I had no idea that was a thing. Guess that works well too.
