### ISSUE TITLE
Mouse sensitivity slows down the higher the frame rate

### ISSUE THREAD

**Issue by UncookedMoa** [fgsfdsfgs/perfect_dark#283]
While less noticeable on lower frame rates, mouse sensitivity starts to slow down a lot the higher you go.
Demonstrated with Sensitivity Matcher:

https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/2a12311f-6bcc-45c3-8f77-aeebc2df791c

**Comment by fgsfdsfgs** [comment]
You're not really supposed to go above 240. The game explodes if you do and that would be kind of difficult to fix. Does this happen at 120-240 FPS as well?

**Comment by UncookedMoa** [comment]
> You're not really supposed to go above 240. The game explodes if you do and that would be kind of difficult to fix. Does this happen at 120-240 FPS as well?

That makes a lot of sense. I'd read a lot of articles/video titles that claimed this port had uncapped support so I had no idea I have to stay under 240 fps. The sensitivity matcher isn't very consistent with the game, since it seems like there's some movement that makes the spinning inconsistent, but any potential difference would be very minor. It does seem to start getting noticeably slower above 240 fps though. Would be nice to have a yaw value to use to actually match my sensitivity and convert it over from other games. Is there any yaw value for the game recorded?

I do know that 30 fps does still have something sped up compared to the original, such as the CamSpy bobbing, however. (https://github.com/fgsfdsfgs/perfect_dark/issues/284#issue-2022950930)

**Comment by fgsfdsfgs** [comment]
There are some issues that are present even when not exceeding 240 or even 30, yes.
`g_Vars.currentplayer->vv_theta` is the current player's yaw in degrees, `->vv_verta` is the pitch. I don't have any recorded values of degrees per frame or anything like that on hand.

**Comment by fgsfdsfgs** [comment]
I'll close this since this is already mentioned in #247.
