### ISSUE TITLE
CamSpy bobbing too aggressive (and gets more aggressive the higher the frame rate)

### ISSUE THREAD

**Issue by UncookedMoa** [fgsfdsfgs/perfect_dark#284]
CamSpy bobbing seems to be tied to frame rate and speeds up the higher you go, and slows down the lower you go.

https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/26d1638f-6008-4aa7-8842-a47809c7b547

The 30 fps setting still makes the bobbing too aggressive. Note how the bars on the right side for elevation go up and down two bars instead of just one, like it does on the N64 and Xbox 360. I understand that the performance of simple64 may affect the results, so Xbox 360's locked 60 fps behavior is shown here as well, which seems to match simple64's. They all start at 80 H/M, but the 30 fps setting on the PC port can go as high as 95 H/M, while the other two ports only ever go up to 90 H/M.

https://github.com/fgsfdsfgs/perfect_dark/assets/42000511/415c8d6c-bcbd-4cc7-95dd-5532ef1c4aeb

**Comment by fgsfdsfgs** [comment]
I sort of partially fixed this, but it would be pretty difficult to match the bobbing rate exactly with 30FPS without changing how it bobs.

**Comment by fgsfdsfgs** [comment]
Guess I'll close this, please reopen if the bobbing is still much too fast.
