### ISSUE TITLE
Menus tied to frame rate

### ISSUE THREAD

**Issue by UncookedMoa** [fgsfdsfgs/perfect_dark#285]
This is probably a known issue due to how obvious it is, but the menu effects, such as the flashing effect, speed up/slow down depending on the frame rate and can get ridiculously fast. This also applies to the radial menu for weapon swapping, which can make it more difficult to swap between weapons.

**Comment by fgsfdsfgs** [comment]
This is mentioned in [this issue](https://github.com/fgsfdsfgs/perfect_dark/issues/247), so I'll close this one.
