### ISSUE TITLE
Frame buffer effects run at the wrong aspect ratio

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#29]
Compare me pausing to the actual game footage, the crates and mission time at the left get offset and stretched.

https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/845d8962-8daf-4496-a6c7-999bf7a94bcc

**Comment by 8sm32K4D1K5f3E** [comment]
Seems to only happen in Hi-Res mode, could be related to Hi-Res mode's different render width.

**Comment by ghost** [comment]
Very strange, you can even see the aspect ratio change in real time when enabling/disabling it.

https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/9b9a9513-db7f-45ab-9e1e-9c762f5c87eb

**Comment by fgsfdsfgs** [comment]
Does it make sense to even leave the hi-res mode option available? Does it have any effect in the port that I haven't noticed?

**Comment by fgsfdsfgs** [comment]
I'll leave it in for now. Should be fixed.
