### ISSUE TITLE
Completing Combat Simulator Challenges Above 22 Stops Unlocking Weapons.

### ISSUE THREAD

**Issue by captinwill** [fgsfdsfgs/perfect_dark#290]
I have completed challenges 1-27 and the last weapon I have unlocked is the n-bomb. Take note, because that is not how to n64 and xbla versions do it. It is supposed to be that completing 23 challenges unlocks the last item, the x-ray scanner, which i do not have, nor the laser.

Screenshots:

![20231207155436_1](https://github.com/fgsfdsfgs/perfect_dark/assets/71353277/f06900fd-2265-48a8-ac34-b521dab52313)
![20231207155443_1](https://github.com/fgsfdsfgs/perfect_dark/assets/71353277/4471f624-a987-4936-b7ce-451727355704)
![20231207155448_1](https://github.com/fgsfdsfgs/perfect_dark/assets/71353277/8bf9d912-710d-4fef-9788-c7fdb733699d)
![20231207155452_1](https://github.com/fgsfdsfgs/perfect_dark/assets/71353277/263b5cf8-4cc3-40ee-b89a-d30dd8ac743c)
![20231207155456_1](https://github.com/fgsfdsfgs/perfect_dark/assets/71353277/37e707ff-fef4-4352-a156-5f4e6ac220e1)
![20231207155500_1](https://github.com/fgsfdsfgs/perfect_dark/assets/71353277/1f550a24-ddf4-4815-8a71-ad1a8db015b3)
![20231207155504_1](https://github.com/fgsfdsfgs/perfect_dark/assets/71353277/86e0d843-3eeb-4ac2-aeda-4c26badab717)
![20231207155639_1](https://github.com/fgsfdsfgs/perfect_dark/assets/71353277/7607b472-5fb3-4793-bdde-b60d62677960)

**Comment by RyanDwyer** [comment]
The weapons which have a challenge requirement to unlock them also need to have been picked up in solo missions before they're unlocked. So for the laser you need to have started Defense. For the Xray scanner you need to have unlocked Rescue.

**Comment by captinwill** [comment]
Interesting, because that's never how it was when I played the XBLA or n64 version. Also, wouldn't the gold magnum have the same rule, requiring you to have unlock Air Force 1 - Rescue?

**Comment by PeeMoldy** [comment]
> Interesting, because that's never how it was when I played the XBLA or n64 version. Also, wouldn't the gold magnum have the same rule, requiring you to have unlock Air Force 1 - Rescue?

No sir. You can unlock the DY357-LX by playing the Capture The Case Challenge in that 1 challenge or you can disarm Trent Easton in Crash Site.

**Comment by fgsfdsfgs** [comment]
So this is working as intended then?

**Comment by RyanDwyer** [comment]
Yes.
