### ISSUE TITLE
Random crashing in Combat Simulator challenges

### ISSUE THREAD

**Issue by JamesPConnolly91** [fgsfdsfgs/perfect_dark#298]
Linux version on Steam Deck OLED
When playing Combat Simulator challenges as single player, game will randomly freeze indefinitely, have to force quit program. Game has not frozen in single player campaign missions so far, only in combat simulator.

**Comment by JamesPConnolly91** [comment]
Actually, the freezes may have been related to the aim button issue as mentioned in another post. Tried using the launch command /home/deck/.steam/steam/steamapps/common/SteamLinuxRuntime_sniper/run %command% instead of running in Steam Linux compatibility mode and it seems to run better in brief testing. I will post back if the issue persists.

**Comment by fgsfdsfgs** [comment]
I wonder why this happens with the one specific SteamOS runtime, but so far not on any other Linux distro, nor on Windows.

**Comment by JamesPConnolly91** [comment]
Tested some more, appears to be stable. I did run into a separate issue with Combat Simulator challenges sims difficulty levels. I'll make a separate post on that, but I'll close this one. Thanks.
