### ISSUE TITLE
Mouse and Keyboard controls not working when an XInput controller is connected before launch

### ISSUE THREAD

**Issue by Nyxem64** [fgsfdsfgs/perfect_dark#3]
If you have an Xinput controller connected to the computer before launching pd.exe, keyboard and mouse controls fail to work. Disconnecting the controller and restarting pd.exe fixes the issue. Not exactly an urgent issue but I should mention it in case someone else runs into the problem of their controls suddenly not working.

**Comment by fgsfdsfgs** [comment]
This should be fixed now. And controller input should actually sort of work properly now.
