### ISSUE TITLE
Crash looking down Defection elevator shaft

### ISSUE THREAD

**Issue by Phnod** [fgsfdsfgs/perfect_dark#30]
Got an unknown GBI opcode on the elevator after it started moving down towards the lobby. I was fooling around with some cheats at the same time, and have reliably replicated and narrowed it to looking down the shaft while holding the Phoenix. I wish I could provide more information of what command value it was trying to process but I'm unsure of how to read the stderr buffer or how to run this through a debugger. 

![2023 08 18 T(22 28 00)pd_6Cv4RRwOCA](https://github.com/fgsfdsfgs/perfect_dark/assets/16583255/a54c1c6d-fd26-4966-a40c-1252bb329939)

![2023 08 18 T(23 04 58)pd_1QSsr6PcBw](https://github.com/fgsfdsfgs/perfect_dark/assets/16583255/c52b02e5-f5e1-481b-8ba4-0b152fc74618)

![2023 08 18 T(22 26 47)pd_gKBrRHsVAq](https://github.com/fgsfdsfgs/perfect_dark/assets/16583255/5ad9c46a-c8e2-446c-9819-6ef379ae144b)

**Comment by fgsfdsfgs** [comment]
This seems to be the same crash that sometimes happens on Villa when looking at the sky on one of the balconies. Still investigating that one.
You will get the stderr messages if you run the game from a cmd/PowerShell/terminal window.

**Comment by zxz41** [comment]
Might be heap corruption. Seems to happen after doing things like opening and closing the menu a few times (modified free heap block). Can recreate on Defection w/o cheats.

**Comment by fgsfdsfgs** [comment]
Will try to recreate this under asan later. It's entirely possible I fucked something up in the C++ part of things and didn't notice.

**Comment by fgsfdsfgs** [comment]
This might be fixed as of latest few commits.
