### ISSUE TITLE
Local Play and Possible Peer to Peer Online Play

### ISSUE THREAD

**Issue by Brannick-Bane** [fgsfdsfgs/perfect_dark#303]
Team,

First, my sincerest admiration for the work on this port. Truly glorious. 

However, I'm having difficulty playing locally with M+K and a secondary controller for player two. I have adjusted the pd.ini file for Players 2 through 4 to their respective numbers (ControllerIndex=(Number of player). This does not seem to be effective. How do I assign a secondary or tertiary controller so these players can join in challenges?

Now, with this being PC, Is there support to make a peer-to-peer connection to play online? If so, what; 's the correct process or additional data that needs to be downloaded?

Again, great work.

**Comment by fgsfdsfgs** [comment]
Go to Extended Options -> Controller and assign controllers there for each player, or alternatively set `FirstGamepadNum` to 1 in the config.
There are currently no multiplayer features in the port other than the split screen local multiplayer. They might be added in the future.

**Comment by fgsfdsfgs** [comment]
There is now a netplay branch, though it is still extremely raw.
