### ISSUE TITLE
[Feature Request] "Picked up a ____" text box skips if that weapon is already out of your inventory by the time it pops up

### ISSUE THREAD

**Issue by Atari-Dude** [fgsfdsfgs/perfect_dark#305]
In Combat Simulator-- if you've already thrown down, or had that weapon disarmed before the text box even appears, there should be an option to prevent it from popping up to simply alert you that you _had_ a weapon, instead of telling that you can currently utilize it.

I would also argue that in addition, if you have already swapped to the weapon it's letting you know you've picked up, the popup might be redundant. Perhaps there could be 2 variants:

1) where the text box is blocked if the weapon is no longer in your inventory
2) where the text box is blocked if the weapon is no longer in your inventory or if you're holding the weapon at the moment the text box is set to appear

**Comment by fgsfdsfgs** [comment]
That's a very specific request and it isn't one that's really easy to implement "correctly". I guess you could clear the message whenever you get disarmed, but then that would clear *any* message. Otherwise the messages themselves would have to track what item they're for.

**Comment by Atari-Dude** [comment]
Closing this as an unnecessary enhancement.
