### ISSUE TITLE
Mouse wheel not working

### ISSUE THREAD

**Issue by MultipleMegaPixels** [fgsfdsfgs/perfect_dark#31]
The mouse wheel doesnt work, it doesn't change weapons. I think it's still in development.

**Comment by fgsfdsfgs** [comment]
Well yeah, it's not bound to anything by default. There's also no way to configure the binds right now, so you'll have to change them in `port/src/input.c`.

**Comment by MultipleMegaPixels** [comment]
Thanks for the answer!

**Comment by MultipleMegaPixels** [comment]
How to bind them?

**Comment by Phnod** [comment]
I was playing around with having the 2 extra buttons bound to the scroll wheel for switching backwards and forwards through weapons and potentially being able to use them through menus. I'd love to do something like this but I also see another PR that'll use the buttons? I could try to expand the amount of bindable buttons from 16 to 32 if you think that's something that'd be useful in the future?

**Comment by fgsfdsfgs** [comment]
I'd like to add a way to change the bindings first, then think about extending the input. Since that PR also removes some duplicated functions, maybe it also frees up some buttons that you could use for the weapon changing.

**Comment by cylonicboom** [comment]
@fgsfdsfgs we can close this now.
