### ISSUE TITLE
GE64-style Muzzle Flashes Pistols and Shotgun Lose Muzzle Flash If Enabled.

### ISSUE THREAD

**Issue by PeeMoldy** [fgsfdsfgs/perfect_dark#310]
So the muzzle flashes for Machine Guns and Assault Rifles look amazing with "GE64-style Muzzle Flashes" enabled, it is just like Goldeneye, maybe even better than Goldeneye, but now there is a new issue. So just like how the K7 Avenger loses it's Muzzle Flash if Threat Detector is enabled, ALL pistols, classic included, and the Shotgun lose their Muzzle Flashes if "GE64-style Muzzle Flashes" is enabled. This includes the MagSec 4 whether single shot OR 3-Round Burst is selected(which would benefit greatly if GE64-style Muzzle Flashes worked with it). Is there a way to keep the amazing effects of "GE64-style Muzzle Flashes" for Machine Guns and Assault Rifles while keeping the muzzle flashes for all pistols and the shotgun; and is there a way once muzzle flashes are restored in this mode, to allow Intermittent GE64-style Muzzle Flashes for the 3 Round-Burst mode of the MagSec4? I will also point out that Windows Defender auto-quarantined the pd.exe as malware named "Behavior:Win32/DefenseEvasion.A!ml", which is a false positive, as 90 AVs ran by VirusTotal did not detect any malware in the latest nightly build for PD PC Port.

@Nyxem64

**Comment by fgsfdsfgs** [comment]
That is not the fault of the original PR, I fucked up when implementing the option.

**Comment by fgsfdsfgs** [comment]
Fixed.
