### ISSUE TITLE
Slight Inconsistent Delay When Starting Up pd.exe

### ISSUE THREAD

**Issue by PeeMoldy** [fgsfdsfgs/perfect_dark#311]
So sometimes when I start up pd.exe in Windows 10 after the latest build, there is a slight delay before the game starts, other times it starts up in seconds. I wonder what is causing this new bug?

**Comment by fgsfdsfgs** [comment]
As long as it's not above 5 seconds, it is not a bug. Slight variation in startup time is also normal.
