### ISSUE TITLE
Feature Request: Reduce Sensitivity For Numbered Horizontal Scroll Dials

### ISSUE THREAD

**Issue by PeeMoldy** [fgsfdsfgs/perfect_dark#312]
So the horizonal scroll dials, like for setting the score and time limits in the combat simulator, as well as setting the vertical FOV are way too sensitive. Just one tap of a button makes the number on the dial go lower or higher way to fast, so it will go to 20 to 86 in 1 tap. Is there a way to make it go slower, or to adjust it's sensitivity?

**Comment by JacksBestGaming** [comment]
Using A and D instead of the arrow keys will let you adjust it slower.

**Comment by PeeMoldy** [comment]
Hmmm... I'll try that.

**Comment by PeeMoldy** [comment]
> Using A and D instead of the arrow keys will let you adjust it slower.

This works!

**Comment by PeeMoldy** [comment]
I'm closing this thanks to hero @JacksBestGaming finding the solution.
