### ISSUE TITLE
64-bit/MacOS

### ISSUE THREAD

**Issue by JayBeest** [fgsfdsfgs/perfect_dark#317]
Hi there,

I am attempting a 64-bit conversion of the port. If possible I would like to discuss / collaborate on this.
I don't know how to send you a message privately, so here we go!

At the moment I am just trying to get something compiled, and am a bit stuck has something to do with the Gfx union and the gsSPDisplayList macro.

In any case, if you are available and want to discuss the matter, please let me know!

Regards,
jb

**Comment by fgsfdsfgs** [comment]
64-bit support is a pretty big undertaking, which is why I haven't bothered with it yet.
* There are many places in the code where pointers are passed and stored using `u32` or even `s32`. Some I've already changed to `uintptr_t`/`intptr_t`, but a lot still remain. A lot of these places are also pretty hard to find.
* Many structures that are directly loaded from the ROM have pointer fields that will be larger on 64-bit, requiring you to rewrite big chunks of `preprocess.c` to use two different sets of structs: one for the original ROM data and one for how it's stored in memory.
* The `Gfx` structs (which are for display lists) are also directly loaded from the ROM, so you'll have to apply the above approach to them too. Their individual bytes are also accessed in some places in the game code, though I've already tried to abstract it somewhat. sm64-port and libultraship can be used as an example of how to deal with extending `Gfx`.
* The renderer should understand 64-bit display lists just fine, though you may need to fixup some things related to how segmented pointers are represented.

And this is just what I can remember off the top of my head. There might be more issues.

**Comment by JayBeest** [comment]
Thanks for your reply!

I get that is quite a big undertaking, but I think it is good practice for me, and i found that it helps me explore and discover the code bit by bit. Already I am getting somewhat familiar with it.

I will continue on the grind, and report back in a while :D

**Comment by JayBeest** [comment]
Also, thanks for the tips, I was already peaking at the current build of libultraship, for reference.
I did not think of SM64, might take a look there too.
For now I'm mostly focusing on compiling a binary, will dive deeper into pointer size / casting and all the rest later.

My current issue is in pdmain.c and gbi.h, giving the following error:

`port/src/pdmain.c:203:2: error: initializer element is not a compile-time constant
        gsSPDisplayList(&var800613a0),
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/PR/gbi.h:1704:33: note: expanded from macro 'gsSPDisplayList'
#define gsSPDisplayList(   dl)  gsDma1p(   G_DL,dl,0,G_DL_PUSH)
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/PR/gbi.h:1667:5: note: expanded from macro 'gsDma1p'
    (uintptr_t)(s)                            \`

I've tried a bunch already, and am not sure I understand why _the element is not constant_. Beginning to wonder it's maybe some old 32-bit gcc stuff that's just less strict?

Will boot up a Linux machine to check how that one handles it.

**Comment by fgsfdsfgs** [comment]
If you're trying to compile with Clang (and chances are you are, since you're on OSX), that expression is technically [only constant](https://github.com/llvm/llvm-project/issues/61737) [in GCC-extended C](https://github.com/llvm/llvm-project/issues/64874). You can try replacing `-std=c11` with `-std=gnu11` in `Makefile.port` or whatever is the extended standard flag for Clang. If that doesn't work, you'll have to get GCC from brew or continue on Linux or something.

Note that this applies only if there aren't any preceding errors. If there are, it could be thinking that it isn't constant because some type is not defined or something.

**Comment by JayBeest** [comment]
I'm trying both clang and gcc, already removed all 'standards' no luck :| so can't imagine -std=gnu11 working. Will try.
Linux has the same issue, but slightly more involved error msg, that has some clue mayhap:

include/PR/gbi.h:1667:5: error: initializer element is not computable at load time
 1667 |     (uintptr_t)(s)                            \
      |     ^
include/PR/gbi.h:1704:33: note: in expansion of macro ‘gsDma1p’
 1704 | #define gsSPDisplayList(   dl)  gsDma1p(   G_DL,dl,0,G_DL_PUSH)
      |                                 ^~~~~~~
port/src/pdmain.c:203:9: note: in expansion of macro ‘gsSPDisplayList’
  203 |         gsSPDisplayList((uintptr_t) &var800613a0),
      |         ^~~~~~~~~~~~~~~
**include/PR/gbi.h:1667:5: note: (near initialization for ‘var8005dcc8[1].words.w1’)
 1667 |     (uintptr_t)(s)                            \
      |     ^**
include/PR/gbi.h:1704:33: note: in expansion of macro ‘gsDma1p’
 1704 | #define gsSPDisplayList(   dl)  gsDma1p(   G_DL,dl,0,G_DL_PUSH)
      |                                 ^~~~~~~
port/src/pdmain.c:203:9: note: in expansion of macro ‘gsSPDisplayList’
  203 |         gsSPDisplayList((uintptr_t) &var800613a0),
      |         ^~~~~~~~~~~~~~~

The extra info in **bold** interesting..

**Comment by fgsfdsfgs** [comment]
I think I'll need the full log. You can attach it as a text file and remove any personal information if you want.
As a side note, sometimes `gcc` is actually an alias for Clang in OSX by default. You can check if you're actually using gcc using `gcc -v`.

**Comment by JayBeest** [comment]
Seems to lead to [smokeinit.c](https://github.com/fgsfdsfgs/perfect_dark/blob/port/src/game/smokeinit.c) found these orphaned Gfx structs :)

**Comment by fgsfdsfgs** [comment]
These are absolutely used elsewhere in the game. They are display lists that are used when rendering smoke.
There are many other problems where you will encounter pointers to static display lists being used in this way, so you'll need to solve this issue for sure.
Just in case, you're using `make -f Makefile.port` and not just `make` when building, right?

**Comment by JayBeest** [comment]
I understand, if i'm not mistaken &var800613a0, var80061380 and var80061360 are even part of the basis of this display list structure, It is just stuffed in with the smoke init for now (see the comment).

**Comment by JayBeest** [comment]
You want the full compilation log? That's a ton :) 
[log.txt](https://github.com/fgsfdsfgs/perfect_dark/files/13742167/log.txt)

and yes, i'm using `make -f Makefile.port` but it already needs a bit of tweaking on both to makefile and the rest of the code get where i'm at now.

**Comment by fgsfdsfgs** [comment]
This almost seems like it's forcing C89 for some reason, but that can't be the case. Can you give me the output of `gcc-13 -v`?
Also try `-std=c23` or `-std=c18` (or `gnu` instead of `c`) and see what happens.
Additionally if that doesn't work, maybe put an `#include <stdint.h>` in `PR/gbi.h` above the existing `#includes`. Just in case the error actually comes from it somehow not recognizing `uintptr_t`.

**Comment by JayBeest** [comment]
<img width="1060" alt="Screenshot 2023-12-21 at 15 32 48" src="https://github.com/fgsfdsfgs/perfect_dark/assets/67948678/2821b465-7c6d-4373-ab00-5c012e2f3fc7">

Sadly no, it is not about the stds.. 

<img width="1057" alt="Screenshot 2023-12-21 at 15 43 15" src="https://github.com/fgsfdsfgs/perfect_dark/assets/67948678/9a24922f-cad4-4899-bed5-9f638b121b1a">

I think these are good leads, but I might have to unfold those macros to figure out what is happening exactly:

include/PR/gbi.h:1668:5: note: (near initialization for 'var8005dcc8[1].words.w1')
and
include/PR/gbi.h:1668:5: note: (near initialization for 'var8005dcc8[2].words.w1')

**Comment by fgsfdsfgs** [comment]
Have you tried this though:
> Additionally if that doesn't work, maybe put an #include <stdint.h> in PR/gbi.h above the existing #includes. Just in case the error actually comes from it somehow not recognizing uintptr_t.

My GCC is also 13.2.0 and I can build just fine for both Windows and Linux with no changes.

**Comment by JayBeest** [comment]
Yes i've tried, but casting to `uintptr_t` is actually part of the porting effort / solution ;) if you want to fool around with it yourself, i can push my current build

**Comment by JayBeest** [comment]
You can build fine? what do you mean? a 64bit executable?

**Comment by JayBeest** [comment]
the moment i turn on the -m32 flag it will compile pdmain. it is no use ofcourse, but altogether strange.
Also, the 32-bit executable builds just fine on my linux machine

**Comment by fgsfdsfgs** [comment]
> a 64bit executable?

No, a 32-bit one.

> but casting to uintptr_t is actually part of the porting effort / solution

Casting to `uintptr_t` should not change the constant-ness unless it's a different size from the pointer or from the `.w1`/`.w2` fields in `Gfx`. In the original code it's casted to `unsigned int` instead and that does not seem to cause a problem. Perhaps `uintptr_t` is typedef'd to `u32` elsewhere in the code and screws it up?
`#include <stdint.h>` there would ensure that it's using the proper definition of `uintptr_t`, which is why I asked.

**Comment by JayBeest** [comment]
> Perhaps `uintptr_t` is typedef'd to `u32` elsewhere in the code and screws it up?

I think i've seen that somewhere yes, was wondering about it, at the same time I solved previous casting errors using `uintptr_t` and `intptr_t` successfully, also the compiler warned me before about it missing here and there (stdint.h) sadly I don't think that is the issue here. I will find that typedef and see if its the issue

**Comment by JayBeest** [comment]
Ah no, its the other way around, types.h from libultra has a blanket typedef:
```
typedef s32 ptrdiff_t;
typedef s32 intptr_t;
typedef u32 uintptr_t;
```
interesting

**Comment by fgsfdsfgs** [comment]
That's hidden under `#ifdef PLATFORM_N64`, so it shouldn't affect anything.
Though I'm thinking of the `#defines` in `src/include/types.h`. I can't actually find the lines you posted. Where exactly did you find this?

**Comment by JayBeest** [comment]
ah! I still have a copy of libultraship in here.. i should get rid of that, I hope my Makefile does not include that. Let me see, ok, that was not an issue, so the typedef uintptr_t was not the issue

**Comment by JayBeest** [comment]
if you want to try for yourself i've pushed all my tweaks over [here](https://github.com/JayBeest/perfect_dark_mactry/tree/64-bit)

**Comment by JayBeest** [comment]
I found the culprit! it was the pointers to .w0 and .w1 in the Gword struct inside the Gfx union!!
Thanks a bunch for all your input!!

**Comment by fgsfdsfgs** [comment]
That union has to be exactly 8 bytes on 32-bit platforms and 16 bytes on 64-bit platforms (so two pointers). Extending those word pointers is the first step, then you'll have to fixup the other union members and all the macros that set them.

**Comment by JayBeest** [comment]
Not per se, the `Gfx` union is permanently fixed at 64-bits, by law :P it is mentioned in gbi.h
But you are right, lot of work left, on to the next error!

Also 4 bytes is 32 bit and 8 bytes is 64 ;) but I think i know what you mean.

**Comment by fgsfdsfgs** [comment]
It's fixed by law on N64. You'll have to extend it here because it must be wide enough to hold 2 pointers.
I meant that the struct must be 8 bytes on 32-bit platforms and 16 bytes on 64-bit platforms, not the pointers. It holds two longwords, 32-bit each on N64, so 4 + 4 = 8. Here you must extend them to 8 bytes each, so 8 + 8 = 16.
Check gbi.h in either libultraship or sm64-port. `w1` and `w2` are `uintptr_t` there.

**Comment by JayBeest** [comment]
Ah, sure yes that makes sense. Is it rly necessary for this union though? It seems to be 64 bit in ultralib still.
Wouldn’t being able to correctly read / write to this structure be enough?

**Comment by JayBeest** [comment]
> Check gbi.h in either libultraship or sm64-port. `w1` and `w2` are `uintptr_t` there.

Yes, this was the fix to the issue. But uintptr_t tells the compiler exactly that if I’m not mistaken (the address being 32-bit instead of 64-bit)

I could be completely mistaken, not too familiar with this conversion stuff. But uintptr_t is has size 4 right?

I do get your point, and at the same time I'm still figuring out how this whole thing works. I will continue debugging compilation errors for now, to be continued

**Comment by fgsfdsfgs** [comment]
`uintptr_t` is the size of a pointer, so 4 bytes on 32-bit and 8 bytes on 64-bit.

**Comment by JayBeest** [comment]
I see, well i've got a segfaulting executable now, I'm happy!!

**Comment by JayBeest** [comment]
This is the Gwords struct in the current libultra:

```
typedef struct {
    uintptr_t w0;
    uintptr_t w1;

    // unsigned long long w0;
    // unsigned long long w1;
} Gwords;

```
It seems they had the same idea as you at first but it is not implemented (yet).
I can imagine this union being populated directly from the ROM. With all the byteswapping going on, updating this union to be 128 bits could be alot more cumbersome.
Messing up the the structure some (bitshifting) functions rely on (not to mention an ungodly amount of padding).
instead making a 32-bit pointer address work seems more sensible?

**Comment by fgsfdsfgs** [comment]
There are many places in the game where it just puts an actual pointer into `w2` when loading textures or vertices. It'd be somewhat difficult to implement another solution. There are in general no guarantees about the address layout of anything, so you can't really e.g. pass them relative to module base or something.

**Comment by JayBeest** [comment]
I think you are completely right :) bit misleading the comment about the union being 64-bits by law.
Changing the Gwords from 2x u32 to 2x uintptr_t indeed increased the size from 8 to 16.

In any case, thanks for all your feedback!!

**Comment by JayBeest** [comment]
>* Many structures that are directly loaded from the ROM have pointer fields that will be larger on 64-bit, requiring you >to rewrite big chunks of `preprocess.c` to use two different sets of structs: one for the original ROM data and one for >how it's stored in memory.
>
>* The `Gfx` structs (which are for display lists) are also directly loaded from the ROM, so you'll have to apply the above >approach to them too. Their individual bytes are also accessed in some places in the game code, though I've already >tried to abstract it somewhat. sm64-port and libultraship can be used as an example of how to deal with extending >`Gfx`.
>
>* The renderer should understand 64-bit display lists just fine, though you may need to fixup some things related to how >segmented pointers are represented.


And btw you were dead-on with your predictions, preprocessing the rom is segfaulting. Now the real challenge..

<img width="1680" alt="Screenshot 2023-12-21 at 22 19 12" src="https://github.com/fgsfdsfgs/perfect_dark/assets/67948678/7d6a8597-c918-424b-b337-b5ef10adffa6">

**Comment by JayBeest** [comment]
So I've been reading quite a bit of the ([preprocess.c](https://github.com/fgsfdsfgs/perfect_dark/blob/port/port/src/preprocess.c)) code, again and again, slowly getting a grasp on what is going on.
For now I want to focus on the part that is currently segfaulting: preprocessing of the sound.
I think the romfile is loaded correctly, I see no reason why it wouldn't ([romdataLoadROM()](https://github.com/fgsfdsfgs/perfect_dark/blob/f2a2458795e74e173d9b9dc0f1311f65b969d2c6/port/src/romdata.c#L374C13-L374C13)) - while debugging I found all values in a given ALInstrument struct to seem reasonable, and I even crosschecked against a working 32-bit binary.
Now I'm looking at creating the 64 bit memory structures (that need it).
Looking at [libaudio.h](https://github.com/fgsfdsfgs/perfect_dark/blob/port/include/PR/libaudio.h) and for now at the soundbank [part](https://github.com/fgsfdsfgs/perfect_dark/blob/f2a2458795e74e173d9b9dc0f1311f65b969d2c6/include/PR/libaudio.h#L168) I found the following structs that need an x64 implementation:


```
typedef struct {
	ALADPCMloop *loop;
	ALADPCMBook *book;
} ALADPCMWaveInfo;

typedef struct {
	ALRawLoop *loop;
} ALRAWWaveInfo;

typedef struct ALWaveTable_s {
	u8          *base;          /* ptr to start of wave data    */
	s32         len;            /* length of data in bytes      */
	u8          type;           /* compression type             */
	u8          flags;          /* offset/address flags         */
	union {
		ALADPCMWaveInfo adpcmWave;
		ALRAWWaveInfo   rawWave;
	} waveInfo;
} ALWaveTable;

typedef struct ALSound_s {
	ALEnvelope  *envelope;
	ALKeyMap    *keyMap;
	ALWaveTable *wavetable;     /* offset to wavetable struct           */
	ALPan       samplePan;
	u8          sampleVolume;
	u8          flags;
} ALSound;

typedef struct {
	u8          volume;         /* overall volume for this instrument   */
	ALPan       pan;            /* 0 = hard left, 127 = hard right      */
	u8          priority;       /* voice priority for this instrument   */
	u8          flags;
	u8          tremType;       /* the type of tremelo osc. to use      */
	u8          tremRate;       /* the rate of the tremelo osc.         */
	u8          tremDepth;      /* the depth of the tremelo osc         */
	u8          tremDelay;      /* the delay for the tremelo osc        */
	u8          vibType;        /* the type of tremelo osc. to use      */
	u8          vibRate;        /* the rate of the tremelo osc.         */
	u8          vibDepth;       /* the depth of the tremelo osc         */
	u8          vibDelay;       /* the delay for the tremelo osc        */
	s16         bendRange;      /* pitch bend range in cents            */
	s16         soundCount;     /* number of sounds in this array       */
	ALSound     *soundArray[1];
} ALInstrument;

typedef struct ALBank_s {
	s16                 instCount;      /* number of programs in this bank */
	u8                  flags;
	u8                  pad;
	s32                 sampleRate;     /* e.g. 44100, 22050, etc...       */
	ALInstrument        *percussion;    /* default percussion for GM       */
	ALInstrument        *instArray[1];  /* ARRAY of instruments            */
} ALBank;

typedef struct {                /* Note: sizeof won't be correct        */
	s16         revision;       /* format revision of this file         */
	s16         bankCount;      /* number of banks                      */
	ALBank      *bankArray[1];  /* ARRAY of bank offsets                */
} ALBankFile;

```

@fgsfdsfgs Could you (or someone else?) check if i'm on the right path here?

**Comment by JayBeest** [comment]
Also I'm pretty sure [this](https://github.com/fgsfdsfgs/perfect_dark/blob/f2a2458795e74e173d9b9dc0f1311f65b969d2c6/port/src/preprocess.c#L46) alreadySwapped function including the //mask hack needs more of my attention.
Also I'm wondering, in the case of the soundbanks, do we only need to change the way the struct is accessed by the preprocessor on x64?

**Comment by fgsfdsfgs** [comment]
You're thinking the other way around. You'll need two variants for all those structs: a "host" version, which is just how they already appear in the existing headers (with any integer fields that might hold a pointer converted to `(u)intptr_t`), and a "ROM" version that has `u32`s in place of pointer fields. So instead of changing the existing structs, you'll need a new set of always-32-bit structs. This will be required for any struct that is loaded from the ROM and has pointer fields, `Gfx` and any structs loaded from the ROM that have fields that *might* store pointers.
You won't need the `alreadySwapped` hack because you'll need to allocate completely new structures instead of swapping them in place, as their size will be different.
There is in fact an asset extractor made by Ryan Dwyer [here](https://gitlab.com/ryandwyer/pd-extract) which already does all (or at least most of) this.

**Comment by JayBeest** [comment]
Nice! Thanks, the thought going through my mind just now was: “There is something backwards in my reasoning, it doesn’t really add up”. Makes a lot more sense now, thanks again!

**Comment by fgsfdsfgs** [comment]
64-bit platforms are now supported thanks to Raf's efforts. I have not tried building the game for aarch64 though and the only platforms with autobuilds are currently i686 and x86_64.

**Comment by fgsfdsfgs** [comment]
In addition there are now OSX builds for both ARM64 and x86_64. I will close this, please notify if they don't work.

**Comment by GB-CG** [comment]
@JayBeest Are you able to make a version for legacy macOS 10.14 and below? Right now the autobuilds are only for the modern versions.

**Comment by fgsfdsfgs** [comment]
The game would probably build fine for that, but I don't know how to force it to use the older frameworks/SDK/libs/whatever.

UPD: I've decreased the version requirement to 10.9. Current versions of SDL2 don't go any lower than 10.7, but I'm pretty sure 10.9 is required for the GameController stuff to work. We'll see if it affects anything.
