### ISSUE TITLE
Question about builds

### ISSUE THREAD

**Issue by Dreamboum** [fgsfdsfgs/perfect_dark#318]
[
![fddfdfdf](https://github.com/fgsfdsfgs/perfect_dark/assets/65136045/41fdb27e-f1af-408f-aaaa-d9bd3362ded0)
](url)

I would be grateful if you could enlighten me about the builds. I feel lost, because I see version numbers like "#476" and "#314", as well as "94df3fc". I would like to know what the real version number is, and it would be nice if this was made more visible and simplified.

**Comment by fgsfdsfgs** [comment]
The latest mainline build can always be downloaded from the [links in the README](https://github.com/fgsfdsfgs/perfect_dark?tab=readme-ov-file#download). If you don't need anything else, then that's all you need to know.

Automatic builds are made both for all branches in the mainline repository (i.e. this one, the latest base version of the port), as well as for any Pull Requests submitted to it (e.g. the one at the top is for [this PR](https://github.com/fgsfdsfgs/perfect_dark/pull/314)). PRs are basically features or changes submitted by other people.

To identify which builds are for PRs and which are for the mainline repo, look at the little blue tag on the right of the build. If it says `port`, that's the base version. If it says something else, that's someone's PR. You can test these if you want, but if you find problems with them, please post them on that particular PR's page and not in the main issue tracker.

The # number is the sequential number of the build. It just counts up for all the builds ever made.

The other hex number is the ID of the commit that triggered the build. This is basically the ID of the source code revision that the build was made from. The latest commit ID is displayed on the front page for the repository (here on the right):
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/2997482/0753d8d2-30d3-45e9-a873-96a153a4b1bf)
You can use this ID to figure out whether you have the latest version or not, so you can think of it as the version number. To figure out what exact version you have, you can look at the [commit log](https://github.com/fgsfdsfgs/perfect_dark/commits/port/).

**Comment by Dreamboum** [comment]
![hfg87](https://github.com/fgsfdsfgs/perfect_dark/assets/65136045/0ebe73e0-b6b7-4c12-a339-2b530f0f3fed)

In the link you gave me, there is no version number indicated, and when I look in the port, there is nothing specific indicated. Frankly, I don't think it's well explained, it's too confusing. You don't use the same methods as developers, who use for example v1.0 or v1.10. I can't find myself in your builds and there is no clear indication.

[](https://github.com/fgsfdsfgs/perfect_dark?tab=readme-ov-file#download)

**Comment by PeeMoldy** [comment]
> ![hfg87](https://private-user-images.githubusercontent.com/65136045/292223345-0ebe73e0-b6b7-4c12-a339-2b530f0f3fed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNzAyOTIsIm5iZiI6MTcwMzE2OTk5MiwicGF0aCI6Ii82NTEzNjA0NS8yOTIyMjMzNDUtMGViZTczZTAtYjZiNy00YzEyLWEzMzktMmI1MzBmMGYzZmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE0NDYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NDU1NWU2ZDUxYmU0ZmM1MDk3YjVkMTZiMmU1NDZjMjYyYzczYWM4OTFlOWE3YmNjODlhZDk0N2NlMmI2NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f56OX7CeJMtG3pVofku_hmbIeZrWEV-qIYnhupwzByk)
> 
> In the link you gave me, there is no version number indicated, and when I look in the port, there is nothing specific indicated. Frankly, I don't think it's well explained, it's too confusing. You don't use the same methods as developers, who use for example v1.0 or v1.10. I can't find myself in your builds and there is no clear indication.

I think the build code is in the title screen, no?

**Comment by fgsfdsfgs** [comment]
There are no actual version numbers because there are no releases. I don't make them because changes are still frequent and there's no roadmap of any kind. I'm not sure why you need them, since you already have the ability to check whether you have the latest build or not, and all builds are uniquely identified for debugging purposes.

If you want to identify which build you have, the commit ID is displayed on the startup screen under "Variant":
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/2997482/4f4e820c-27af-46b9-ae4a-fd2b86898523)

Also, when I said "links in the README", I meant specifically the ones called `i686-windows` and `i686-linux` that point directly to the latest builds for those platforms.

**Comment by djdv** [comment]
@fgsfdsfgs 
I created https://github.com/fgsfdsfgs/perfect_dark/pull/320 to possibly assist with this.
You're welcome to decline it if not interested.

**Comment by fgsfdsfgs** [comment]
That PR has been merged and now there's an automatically updated release. Automatic builds also now include executables for PAL and JPN.
