### ISSUE TITLE
Bug fixed in the compilation for the European version.

### ISSUE THREAD

**Issue by StevenCastroSC** [fgsfdsfgs/perfect_dark#322]
Good morning of afternoon depending on the side where are you sir/madam.

I have to say this project is incredible and I don't know as programor how you can decopilate a console game; it has to be scary and difficult. 

I would like to contribute, When I tried to compilate the pal version 8.7 I got an error with:

src/game/mplayer/ingame.c: In function 'mpAwardsMenuHandler':
include/PR/gbi.h:2438:18: warning: 'colour' may be used uninitialized [-Wmaybe-uninitialized]
 2438 |     _g->words.w1 = (unsigned int)(d); \
      |     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
src/include/gbiex.h:90:42: note: in expansion of macro 'gDPSetColor'
   90 | #define gDPSetEnvColorViaWord(pkt, rgba) gDPSetColor(pkt, G_SETENVCOLOR, rgba)
      |                                          ^~~~~~~~~~~
src/game/mplayer/ingame.c:679:33: note: in expansion of macro 'gDPSetEnvColorViaWord'
  679 |                                 gDPSetEnvColorViaWord(gdl++, colour);
      |                                 ^~~~~~~~~~~~~~~~~~~~~
src/game/mplayer/ingame.c:645:21: note: 'colour' was declared here
  645 |                 u32 colour;
      |                     ^~~~~~
i686-w64-mingw32-gcc -std=c11 -c -DVERSION=4 -DVERSION_HASH=\"787758c03\" -DVERSION_TARGET=\"i686-windows\" -DVERSION_ROMID=\"pal-final\" -DVERSION_BRANCH=\"port\" -DMATCHING=0 -DPAL=1 -DPIRACYCHECKS=0 -DROM_SIZE=32 -D_LANGUAGE_C=1 -DAVOID_UB=1 -I include -I include/PR -I src/include -I src/generated/pal-final -I src/lib/ultra/audio -I port/include -IC:/msys64/mingw32/include/SDL2 -g -fno-inline-functions -fno-strict-aliasing -funsigned-char -fwrapv -Wall -Wno-address -Wno-aggressive-loop-optimizations -Wno-int-in-bool-context -Wno-misleading-indentation -Wno-missing-braces -Wno-multichar -Wno-tautological-compare -Wno-unused-but-set-variable -Wno-unused-value -Wno-unused-variable -Wno-format-truncation -Wno-pointer-sign -Og -o build/pal-final-port/src/game/mplayer/mpaicommands.o src/game/mplayer/mpaicommands.c
i686-w64-mingw32-gcc -std=c11 -c -DVERSION=4 -DVERSION_HASH=\"787758c03\" -DVERSION_TARGET=\"i686-windows\" -DVERSION_ROMID=\"pal-final\" -DVERSION_BRANCH=\"port\" -DMATCHING=0 -DPAL=1 -DPIRACYCHECKS=0 -DROM_SIZE=32 -D_LANGUAGE_C=1 -DAVOID_UB=1 -I include -I include/PR -I src/include -I src/generated/pal-final -I src/lib/ultra/audio -I port/include -IC:/msys64/mingw32/include/SDL2 -g -fno-inline-functions -fno-strict-aliasing -funsigned-char -fwrapv -Wall -Wno-address -Wno-aggressive-loop-optimizations -Wno-int-in-bool-context -Wno-misleading-indentation -Wno-missing-braces -Wno-multichar -Wno-tautological-compare -Wno-unused-but-set-variable -Wno-unused-value -Wno-unused-variable -Wno-format-truncation -Wno-pointer-sign -Og -o build/pal-final-port/src/game/mplayer/mplayer.o src/game/mplayer/mplayer.c
src/game/mplayer/mplayer.c:2721:48: error: 'L_MISC_261' undeclared here (not in a function); did you
 mean 'L_MISC_461'?
 2721 |         /*0x2a*/ { MUSIC_SKEDARRUINS_KING,120, L_MISC_261, SOLOSTAGEINDEX_SKEDARRUINS }, //
"Skedar Warrior" (Skedar Leader)
      |                                                ^~~~~~~~~~
      |                                                L_MISC_461
make: *** [Makefile.port:311: build/pal-final-port/src/game/mplayer/mplayer.o] Error 1

To resolve I just changed the mplayer.c with notepad and put "L_MISC_261" defintion like "#define L_MISC_261 261" to resolve the conflit in line: /*0x2a*/ { MUSIC_SKEDARRUINS_KING, 120, L_MISC_261, SOLOSTAGEINDEX_SKEDARRUINS }, // "Skedar Warrior" (Skedar Leader)

Now is creating the pal .exe file perfectly. If you need more information or if is ok, please let me know.

Phantastic work. Maybe in the future I will hack the rom to put other audio languages or mods depending in how the exe works with the rom. I don't know if this is possible but is important to give another life to one clasic game.  Thank you again.

**Comment by PeeMoldy** [comment]
> Good morning of afternoon depending on the side where are you sir/madam.
> 
> I have to say this project is incredible and I don't know as programor how you can decopilate a console game; it has to be scary and difficult.
> 
> I would like to contribute, When I tried to compilate the pal version 8.7 I got an error with:
> 
> src/game/mplayer/ingame.c: In function 'mpAwardsMenuHandler': include/PR/gbi.h:2438:18: warning: 'colour' may be used uninitialized [-Wmaybe-uninitialized] 2438 | _g->words.w1 = (unsigned int)(d); | ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~ src/include/gbiex.h:90:42: note: in expansion of macro 'gDPSetColor' 90 | #define gDPSetEnvColorViaWord(pkt, rgba) gDPSetColor(pkt, G_SETENVCOLOR, rgba) | ^~~~~~~~~~~ src/game/mplayer/ingame.c:679:33: note: in expansion of macro 'gDPSetEnvColorViaWord' 679 | gDPSetEnvColorViaWord(gdl++, colour); | ^~~~~~~~~~~~~~~~~~~~~ src/game/mplayer/ingame.c:645:21: note: 'colour' was declared here 645 | u32 colour; | ^~~~~~ i686-w64-mingw32-gcc -std=c11 -c -DVERSION=4 -DVERSION_HASH="787758c03" -DVERSION_TARGET="i686-windows" -DVERSION_ROMID="pal-final" -DVERSION_BRANCH="port" -DMATCHING=0 -DPAL=1 -DPIRACYCHECKS=0 -DROM_SIZE=32 -D_LANGUAGE_C=1 -DAVOID_UB=1 -I include -I include/PR -I src/include -I src/generated/pal-final -I src/lib/ultra/audio -I port/include -IC:/msys64/mingw32/include/SDL2 -g -fno-inline-functions -fno-strict-aliasing -funsigned-char -fwrapv -Wall -Wno-address -Wno-aggressive-loop-optimizations -Wno-int-in-bool-context -Wno-misleading-indentation -Wno-missing-braces -Wno-multichar -Wno-tautological-compare -Wno-unused-but-set-variable -Wno-unused-value -Wno-unused-variable -Wno-format-truncation -Wno-pointer-sign -Og -o build/pal-final-port/src/game/mplayer/mpaicommands.o src/game/mplayer/mpaicommands.c i686-w64-mingw32-gcc -std=c11 -c -DVERSION=4 -DVERSION_HASH="787758c03" -DVERSION_TARGET="i686-windows" -DVERSION_ROMID="pal-final" -DVERSION_BRANCH="port" -DMATCHING=0 -DPAL=1 -DPIRACYCHECKS=0 -DROM_SIZE=32 -D_LANGUAGE_C=1 -DAVOID_UB=1 -I include -I include/PR -I src/include -I src/generated/pal-final -I src/lib/ultra/audio -I port/include -IC:/msys64/mingw32/include/SDL2 -g -fno-inline-functions -fno-strict-aliasing -funsigned-char -fwrapv -Wall -Wno-address -Wno-aggressive-loop-optimizations -Wno-int-in-bool-context -Wno-misleading-indentation -Wno-missing-braces -Wno-multichar -Wno-tautological-compare -Wno-unused-but-set-variable -Wno-unused-value -Wno-unused-variable -Wno-format-truncation -Wno-pointer-sign -Og -o build/pal-final-port/src/game/mplayer/mplayer.o src/game/mplayer/mplayer.c src/game/mplayer/mplayer.c:2721:48: error: 'L_MISC_261' undeclared here (not in a function); did you mean 'L_MISC_461'? 2721 | /_0x2a_/ { MUSIC_SKEDARRUINS_KING,120, L_MISC_261, SOLOSTAGEINDEX_SKEDARRUINS }, // "Skedar Warrior" (Skedar Leader) | ^~~~~~~~~~ | L_MISC_461 make: *** [Makefile.port:311: build/pal-final-port/src/game/mplayer/mplayer.o] Error 1
> 
> To resolve I just changed the mplayer.c with notepad and put "L_MISC_261" defintion like "#define L_MISC_261 261" to resolve the conflit in line: /_0x2a_/ { MUSIC_SKEDARRUINS_KING, 120, L_MISC_261, SOLOSTAGEINDEX_SKEDARRUINS }, // "Skedar Warrior" (Skedar Leader)
> 
> Now is creating the pal .exe file perfectly. If you need more information or if is ok, please let me know.
> 
> Phantastic work. Maybe in the future I will hack the rom to put other audio languages or mods depending in how the exe works with the rom. I don't know if this is possible but is important to give another life to one clasic game. Thank you again.

Are you going to do a pull request for this?

**Comment by fgsfdsfgs** [comment]
Thanks for the tip, pushed a slightly different fix. Both PAL and JPN builds should work now.
