### ISSUE TITLE
Negative score in Challenges a̵f̵t̵e̵r̵ ̵p̵l̵a̵y̵i̵n̵g̵ ̵N̵e̵t̵w̵o̵r̵k̵ ̵m̵a̵t̵c̵h̵e̵s̵

### ISSUE THREAD

**Issue by Mr-Poyetas** [fgsfdsfgs/perfect_dark#328]
I know Net support is highly experimental for now and prone to errors, so I hope this helps

https://github.com/fgsfdsfgs/perfect_dark/assets/143344104/8d218665-8486-4656-8c63-3b81cde02351

**Comment by PeeMoldy** [comment]
Was there a suicide before?

**Comment by Mr-Poyetas** [comment]
https://github.com/fgsfdsfgs/perfect_dark/assets/143344104/d3014b47-ac5a-4956-9a91-65ab1051f5ed

At first I thought this error was related to playing a Network Game before going into Challenges, but I've deleted both the eeprom and the .ini file and the error persists.

**Comment by fgsfdsfgs** [comment]
While it's good that you reported this, note that all kinds of other things might be broken in `port-net` because of the 8 players extension. If you want to play single player or split screen, I'd recommend using the regular `port` branch for now.

**Comment by Atari-Dude** [comment]
I'm guessing it must already be known but if not, bots are also unable to really gain score themselves in splitscreen in the netplay build. Been playing splitscreen on the netplay build for a while now just for testing purposes (I bet most folks aren't playing local splitscreen) and yeah, I'm ashamed it took both my father and I like, a week or two to realize why all the sims were suddenly scoring _so_ terribly lol

**Comment by fgsfdsfgs** [comment]
Should be fixed now. Make sure to wait for the build to complete before testing, as usual.
