### ISSUE TITLE
Controller Sensitivity

### ISSUE THREAD

**Issue by Nioh8** [fgsfdsfgs/perfect_dark#33]
I know it's early days but the controller especially looking with the right stick seems very sensitive. Is there any setting i can change? or just wait for things to mature, thanks.

**Comment by fgsfdsfgs** [comment]
There is now an option to scale the sticks. In pd.ini under the `[Input]` section set, for example,
```
RStickScaleX=0.5
RStickScaleY=0.5
```
Change 0.5 to whatever suits your needs.
Proper sensitivity will probably have to be added into the game later.

**Comment by Nioh8** [comment]
awesome stuff, thanks for that.
