### ISSUE TITLE
No Left Gun Bullet Tracer When Firing Guns In Water In Carrington Villa

### ISSUE THREAD

**Issue by PeeMoldy** [fgsfdsfgs/perfect_dark#336]
So when dual wielding guns in the PD PC Port, the left gun doesn't have a bullet tracer when firing them into water in Carrington Villa, only the right one does. This can be easily seen when mag dumping dual wielded automatic guns. Can this be fixed in the next version?

![pdpcpar53x2burstfirecv](https://github.com/fgsfdsfgs/perfect_dark/assets/152383944/923c43f4-5a88-4f74-b9a0-eb136cdb5844)
![pdpcpar53x2burstfirecviv](https://github.com/fgsfdsfgs/perfect_dark/assets/152383944/48f1bdda-c71a-473d-bfc5-655f4f838c38)
![pdpcpar53x2burstfirenoleftbullettracercv](https://github.com/fgsfdsfgs/perfect_dark/assets/152383944/534e3198-efb5-4d80-b9ae-4a166bdb5229)

**Comment by Flax4** [comment]
I messed around with this a bit, firing in the water does seem to mask the tracer, when firing at the mountain you can clearly see the tracer. 

![bild](https://github.com/fgsfdsfgs/perfect_dark/assets/50862920/3b91ab45-f1f3-41e3-8e7a-bb2a1fd174df)

https://github.com/fgsfdsfgs/perfect_dark/assets/50862920/89932c30-2d9d-4e0d-8dad-3b4905e74506

**Comment by fgsfdsfgs** [comment]
This is probably because of the lack of transparency sorting. If that's the case, I won't fix it since it's very minor. If I ever add transparency sorting, then it will be fixed among other issues [like this](https://github.com/fgsfdsfgs/perfect_dark/issues/149).

**Comment by PeeMoldy** [comment]
> I messed around with this a bit, firing in the water does seem to mask the tracer a little bit, when firing at the mountain you can clearly see the tracer.
> 
> ![bild](https://private-user-images.githubusercontent.com/50862920/294788478-3b91ab45-f1f3-41e3-8e7a-bb2a1fd174df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2NzQyODIsIm5iZiI6MTcwNDY3Mzk4MiwicGF0aCI6Ii81MDg2MjkyMC8yOTQ3ODg0NzgtM2I5MWFiNDUtZjFmMy00MWUzLThlN2EtYmIyYTFmZDE3NGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAwMzMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNWVmODYyN2I2ZmIxY2U5ODVkNTc5ZDBjNGMwMWRjZTdlMzAyNWUxZDkzMWY2NDlhMmZkMTA1MTE2OTYyNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y9qAjSd49MLMDFj9kkytXgGTBCFVHS9iwlS24oPZYsE)
> 
>  2024-01-07.23-11-58.mp4

Good find!

**Comment by PeeMoldy** [comment]
> This is probably because of the lack of transparency sorting. If that's the case, I won't fix it since it's very minor. If I ever add transparency sorting, then it will be fixed among other issues [like this](https://github.com/fgsfdsfgs/perfect_dark/issues/149).

Is this the reason light beams pierce through everything?

**Comment by fgsfdsfgs** [comment]
> Is this the reason light beams pierce through everything?

No, that's a different issue that's more easily fixable.

**Comment by PeeMoldy** [comment]
> > Is this the reason light beams pierce through everything?
> 
> No, that's a different issue that's more easily fixable.

The ending cutscene for Crash Site is where there piercing light is most noticeable, right before Mr. Blonde deals with Trent Easton.

**Comment by fgsfdsfgs** [comment]
Yes, there's [an issue](https://github.com/fgsfdsfgs/perfect_dark/issues/26) for the light coronas already.
Since there's also an issue for the transparency sorting (and this issue appears to be the result of that), I'll close this as well.
