### ISSUE TITLE
Possible vanilla bug about ammo crates in Skedar MP map

### ISSUE THREAD

**Issue by Mr-Poyetas** [fgsfdsfgs/perfect_dark#337]
I'm not sure if the developers originally intended these ammo crates to work this way, but it looks like the ammo crates belong to the gun on the opposite side

https://github.com/fgsfdsfgs/perfect_dark/assets/143344104/4871304e-b457-468a-bec9-330fb8629666

**Comment by Flax4** [comment]
This is vanilla, I'd say it's a design choice, but choice or bug, it's vanilla behaviour.

**Comment by Mr-Poyetas** [comment]
I know, I tested this on emulator before opening this issue

**Comment by fgsfdsfgs** [comment]
This is part of the level, so I can't really fix it in the code without making a huge mess. You can probably fix it if you want by making a custom setup file that changes the layout.

**Comment by Mr-Poyetas** [comment]
Alright, thanks!
