### ISSUE TITLE
Slow Motion/Combat Boost does not work.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#34]
To reproduce: Start a multiplayer match with the Slow Motion option enabled, or use the Combat Boost in Carrington Institute Defense. The game will run the same speed than slow down as intended.

**Comment by fgsfdsfgs** [comment]
This one is a bit weird. Looks like the slow motion is done by just capping the delta time values, so if the game is lagging it will also run in slow motion. But since the game is not lagging on PC it won't ever hit that cap anyway, so it continues running as normal.

**Comment by ghost** [comment]
Would replacing the cap with a multiplied factor of delta work? (IE: capping at delta * .25 instead of a hard set value). That would future proof it for 60+ FPS support than simply altering the value to work with 60.

**Comment by fgsfdsfgs** [comment]
Should be fixed now. Running at higher framerates will require redefining the `TICKS` macro anyway, so it should hopefully work when that's supported.
