### ISSUE TITLE
Simulant kills count as suicide/team kill in Combat Sim

### ISSUE THREAD

**Issue by superjeepboy** [fgsfdsfgs/perfect_dark#342]
Exhibited behaviour as title. Affects local play only - as bots are not supported online as of writing. When killing Simulants of any kind in Combat Simulator, kills count as negative kills on bots. This is obviously not expected behaviour, and still happens when multiple players in split screen are connected.

**Comment by fgsfdsfgs** [comment]
Refer to [this issue](https://github.com/fgsfdsfgs/perfect_dark/issues/328), especially [this comment](https://github.com/fgsfdsfgs/perfect_dark/issues/328#issuecomment-1876695196). If this is actually on `port` and not `port-net`, then notify me here and I'll reopen this issue.

**Comment by superjeepboy** [comment]
Decided to sanity check myself and got myself a copy of latest `port`, and this bug does not exist there. Score counts as expected. You can keep this closed!
