### ISSUE TITLE
Frame rate (?)

### ISSUE THREAD

**Issue by Urammar** [fgsfdsfgs/perfect_dark#344]
So im on a 3090, with a full on cpu. I can get solid 60fps of course, but there seems to be some kind of.. micro stuttering? Lost frames? Just every now and again.

You will play the game, then a few lights will be visible or something, and input responsiveness changes, and the game just feels a bit choppy for a moment.

The system requirements for this are, like, literally an n64. I get this is early days, but how is it possible for this to happen at all? Something funky in the renderer?

**Comment by Urammar** [comment]
Updated to the latest build, this might actually be fixed?

**Comment by fgsfdsfgs** [comment]
> The system requirements for this are, like, literally an n64.

If the game ran natively on the N64 back in the day, it does not mean the system requirements for its PC port or an emulator running it are also N64 tier. That said, a 3090 should be leagues above them anyway.

 When things like this happen, it is most often related to VSync, so I would recommend screwing around with the `VSync` and `FramerateLimit` variables in `pd.ini`. If you currently have `VSync=0`, try setting it to `1` or `-1` and `FramerateLimit` to `0`. If you have it at `1`, try setting it to `-1`. If that doesn't work either, set it to `0` and `FramerateLimit` to `120` or whatever your monitor's refresh rate is.

**Comment by Urammar** [comment]
> When things like this happen, it is most often related to VSync, so I would recommend screwing around with the `VSync` and `FramerateLimit` variables in `pd.ini`. If you currently have `VSync=0`, try setting it to `1` or `-1` and `FramerateLimit` to `0`. If you have it at `1`, try setting it to `-1`. If that doesn't work either, set it to `0` and `FramerateLimit` to `120` or whatever your monitor's refresh rate is.

This seems to largely be fixed. Though it seems to possibly be related to layered transparency?
