### ISSUE TITLE
[Info Request] What are the expected contents of modconfig.txt?

### ISSUE THREAD

**Issue by mmillar-bolis** [fgsfdsfgs/perfect_dark#346]
Currently, these are my command line arguments:

```
--basedir "/Path/To/GameData" --rom-file "Perfect_Dark-USA-RevA.z64" --moddir "/Path/To/ModData" --savedir "/Path/To/Profile" --eeprom-file "eeprom.bin" --log
```

My runtime log features this entry:

```
ERROR: fsFileLoad: could not find file: /Path/To/GameData/modconfig.txt
```

However, this has no bearing on the engine loading `ModData/files/LeldE`, which appears to succeed without issue. Still, it looks like this was added with mod folder support in `d98575d`. I would like to future-proof any patches I make, if `modconfig.txt` is necessary, but I can't seem to figure out what its contents should be.

**Comment by fgsfdsfgs** [comment]
Have you checked https://github.com/fgsfdsfgs/perfect_dark/wiki/Modding ? There is also an example at the bottom.

**Comment by mmillar-bolis** [comment]
*Sigh* No, I'm dumb and didn't notice that there's a wiki now. Hey, sorry about that and thanks so much!

**Comment by fgsfdsfgs** [comment]
`modconfig.txt` is really only necessary if you're modifying stages though. The wiki page should have info on how to replace other stuff as well.

**Comment by mmillar-bolis** [comment]
Makes more sense now. This is great! A few months back, I had just grepped around for arguments, but clearly I had not checked back for a while now. I will give the wiki a thorough read! Thank you again!
