### ISSUE TITLE
Simulant  all/attack command causes crash

### ISSUE THREAD

**Issue by assassinscurse87** [fgsfdsfgs/perfect_dark#347]
crashes in combat simulator when instructing two or more simulants to kill a tarket using the all control with more than one human player.
if i remember correctly this is a vanilla bug, but i'm bringing it up as its still a bug, it's still present, and as such doesnt appear to be a limitation of the original N64 hardware
EXCEPTION: 0x0000005
PC:00071955
MODULE: [00070000]
MAIN MODULE [00070000]

version b9db86f (windows)

edit: also worth noting, i'm using the NTSC 8.7 Final (US latest) ROM for your port, but i originally discovered this particular bug with a PAL 8.7 Final cartridge

**Comment by fgsfdsfgs** [comment]
Can you provide the full crash log? There should be a stack trace at the bottom.

**Comment by assassinscurse87** [comment]
![Screenshot 2024-01-15 022113](https://github.com/fgsfdsfgs/perfect_dark/assets/156285486/154da6cb-3e82-4351-94a8-7c252e506590)

this is the most recent crash hence the PC and MODULE discrepency
