### ISSUE TITLE
Combat Simulator splitscreen flash

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#35]
Playing splitscreen through combat simulator creates this flashy show. Similar to some video plugins on emulators, I believe it's related to the frame buffer. Does not happen through Co-Op.

**SEIZURE WARNING:**
https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/150a61f7-7575-4956-ae11-addfcf5764d3

**Comment by fgsfdsfgs** [comment]
This should be fixed in [the last commit](https://github.com/fgsfdsfgs/perfect_dark/commit/7e26e6eac03cd433117b06d54a23ee8180a70b0d).
