### ISSUE TITLE
Disable the LOD reduction in splitscreen (and by extension, netplay)

### ISSUE THREAD

**Issue by StrikerTheHedgefox** [fgsfdsfgs/perfect_dark#350]
When you have more than 1 player, be it splitscreen or netplay, weapon models, and perhaps other models as well drop significantly in LOD. Since this is no longer needed, as we're not running on N64 hardware, could this behaviour be disabled?

**Comment by fgsfdsfgs** [comment]
There is a PR for this already (#333). I'll close this when I get around to merging it.

**Comment by fgsfdsfgs** [comment]
This has been merged now.
