### ISSUE TITLE
[Bug Report] Splitscreen stutters when multiple players shoot simulatenously (both branches)

### ISSUE THREAD

**Issue by Atari-Dude** [fgsfdsfgs/perfect_dark#351]
https://www.youtube.com/watch?v=mpO0o2lUJGY

While playing splitscreen offline a while back, these stutters during shootouts began. I believe now it may be associated with the netplay build, as I am currently unable to replicate the behavior with the non-netplay build. I believe I've noticed these stutters with most of the weapons if not all, but it's most prevalent with fully automatics such as these Bond ones. I otherwise get a smooth, consistent 60fps experience. Issue does not occur during online play.

PC Build: AMD Ryzen 5 5600X, AMD Radeon RX 6650XT. Played with 2 N64 controllers via Raphnet adaptor.

**Comment by fgsfdsfgs** [comment]
If you disconnect or disable both controllers and try splitscreen with the keyboard, does the issue still occur?

**Comment by Atari-Dude** [comment]
I'm unsure, I don't seem able to map both players to a single keyboard, so without controllers connected I can't fire both player's weapons simultaneously, which is when the stutters noticeably occur

**Comment by Atari-Dude** [comment]
Hmm, odd. Upon further testing, the stutter does appear for me in the non-netplay build too. I didn't see evidence of it yesterday when I had time to test it only briefly, but while doing a proper session with my dad I did notice it. Whenever both players are shooting simultaneously, or one of the players is being shot by the other, it creates the lag/stutter effect. I do wonder if it has to do with the controllers being connected but also seems like it's a little harder to replicate that way since I don't know how to remove the controller yet still be able to fire/move both players around from just a keyboard. The stutter is most noticeable when both players are moving around and firing at each other, or hitting each other.

**Comment by fgsfdsfgs** [comment]
You have to bind Start, Z Trigger and one of the weapon change buttons for all the extra players to some key on the keyboard. It can be one key for all the Start buttons, one key for all the Z Triggers, etc. You can do this in the Extended options.

**Comment by Atari-Dude** [comment]
Currently when I play with just keyboard (tested just now on standard branch), it seems perfectly smooth.

_I remember now_, when I was emulating an Xbox 360 controller via a program called XOutput, I had [these](https://github.com/fgsfdsfgs/perfect_dark/issues/321) issues... then I asked Graslu and he offered me [this](https://raw.githubusercontent.com/gabomdq/SDL_GameControllerDB/master/gamecontrollerdb.txt) solution. Immediately after that was when the shootout stutters began. His fix solved 99% of my unresponsive controller issues, but introduced the shootout stuttering.

So perhaps natively adding auto detect for the N64 controllers using the Raphnet adapter would solve this issue then? Instead of having to utilize a third party solution, in this case having to add a gamecontrollerdb text file in the directory to let PD recognize N64 controllers, or what I tried a month ago but experienced major issues with XOutput.

**Comment by fgsfdsfgs** [comment]
Do those controllers have vibration support?

**Comment by Atari-Dude** [comment]
The N64 controller can. I don't use a Rumble Pak personally, but I know the Raphnet adapter is indeed compatible with PD's original rumble functionality if you slot it in the controller. It also can read the N64 memory cards too, which would be cool to see compatible in the PC port someday too

**Comment by fgsfdsfgs** [comment]
That could be the problem then. Every time you fire a gun, the game tries to play a rumble effect, but I'm assuming the adapter has to poll the Rumble Pak to see if it's even there, which blocks the game until the pak responds or some sort of timeout elapses.
I'll push a change that completely disables the rumble requests if vibration strength is set to 0 shortly.

**Comment by fgsfdsfgs** [comment]
Pushed. You should be able to test it on the new non-net build; the net build will update in a few minutes.

**Comment by Atari-Dude** [comment]
Sorry for the delay in testing-- just did an hour or so worth of matches with my dad. Happy to report it was stutter-free the entire time! Thank you!
