### ISSUE TITLE
[CRASH] start armed conflict with shields

### ISSUE THREAD

**Issue by assassinscurse87** [fgsfdsfgs/perfect_dark#355]
after testing out the new start armed feature, I have managed to break something within 3 minutes 🤣
starrt armed spawns with whatever is in weapon slot one, and whilst it works fine for most non weapon items (although I have also noticed cloaking device simply does nothing) the shield simply is not one of them. level loads as normal and it does show the shield bar around the health bar on screen, however it promptly crashes and throws the following error window.

P.S. great work withg the port so far, I look forward to breaking more things in the future

![Screenshot 2024-01-18 190733](https://github.com/fgsfdsfgs/perfect_dark/assets/156285486/718ac1cf-0aad-44bc-bcd5-4cc3a6ce9daa)
Version is NTSC US Final / 474a6df

**Comment by Atari-Dude** [comment]
I know Combat Boosts give 0

**Comment by fgsfdsfgs** [comment]
This has been fixed.
