### ISSUE TITLE
[feature request] precache assets for better optimization

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#357]
modern pcs should have more than enough resources to precache all the assets at launch without issue
this would fix lag spikes from when cameras explode and etc

**Comment by fgsfdsfgs** [comment]
The game does not load anything at runtime if you aren't using mods. I don't think I've ever seen lag spikes from exploding cameras either. Do you have a RaphNet N64 adapter connected?

**Comment by fgsfdsfgs** [comment]
Closing this since I've seen no other reports of stutter when stuff explodes.
