### ISSUE TITLE
[Feature request] Setting for antialiasing

### ISSUE THREAD

**Issue by s-ilent** [fgsfdsfgs/perfect_dark#36]
Hi! Would it be possible to add options for hardware antialiasing? (i.e. multisampling AA and FSAA)

It's technically possible to force it from the GPU driver, but doing that breaks framebuffer effects. 

| No AA | MSAA | FSAA |
| - | - | - |
| ![No AA](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/0174b5c5-b24b-47d3-b33a-8ff082b6e334) | ![MSAA](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/48b9e5b1-12b2-4a36-9669-4f537cf42d16) | ![FSAA](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/727d42c1-52b6-4399-80f6-570ea30aa46f) |

**Comment by fgsfdsfgs** [comment]
Added an MSAA setting to the config. Under the `[Video]` section you can add
```MSAA=4``` (or any number in the 1-16 range, if supported by your driver)
Framebuffer effects seem to work fine with that.

**Comment by s-ilent** [comment]
Thanks! This works great.
Tested with 4x MSAA, and also enhancing the AA through the driver.
| MSAA | FSAA |
| - | - |
| ![Native MSAA](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/e90dc58f-59c6-4be1-9450-5433bbeac4d6) | ![Native MSAA with SSAA](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/422c7314-efa7-4671-bf43-088868f249dc) |
