### ISSUE TITLE
Portal issue in Carrington Institute

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#37]
At a certain angle as shown in the image it's possible to load the room below us, which clips in geometry with the current one.

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/aa5498c5-5928-48e9-bda2-6f1a3ba81f82)

**Comment by fgsfdsfgs** [comment]
This might actually be related to the crashes in Villa and Defection (#30). In both of those spots I can get some portal bugs to occur.

**Comment by fgsfdsfgs** [comment]
This might be fixed as of latest few commits.

**Comment by Graslu** [comment]
Can't seem to replicate any more.
