### ISSUE TITLE
I need to know name table for bindings mouse/keyboard

### ISSUE THREAD

**Issue by Sol1vaN** [fgsfdsfgs/perfect_dark#370]
Hi there, 

I want to bind all mouse buttons (modern ones) with X1 mouse button , X2 mouse button, etc
aka button 4, button 5, etc.

Can you add to the manual a list with all allowed keyboard keys to bind.
The same for mouse of course.

Doom Retro do this (mean while some day the author make a good menu interface for binds).
[https://github.com/bradharding/doomretro/wiki/Console-Commands](url)

**keyboard**
`0 to 9, a to z, -, +, =, backspace, tab, [, enter, ], ctrl, ;, ', shift, capslock, \, ,, ., /, alt, space, scrolllock, printscreen, home, up, pageup, left, right, end, down, pagedown, insert, delete, escape, F12, numpad0 to numpad9`

**mouse**
`mouse1 to mouse8, wheelup, wheeldown`

**joystick**
`dpadup, dpaddown, dpadleft, dpadright, start, guide, back, leftthumb, rightthumb, leftshoulder, rightshoulder, lefttrigger, righttrigger, button1 to button4, paddle1 to paddle4, touchpad, misc1`

**Comment by fgsfdsfgs** [comment]
I might add that as a wiki page later. For now, they should be mostly the same as [this list](https://wiki.libsdl.org/SDL2/SDL_Scancode#values). Take the name from the "Key Name" column, make it all-caps, replace all spaces with `_`. So for example `Right Alt` -> `RIGHT_ALT`.

**Comment by Sol1vaN** [comment]
ey! thanks for the quick reply 🤗🖐

but, there's no info for mouse button names.
trying i've got with the right names: MOUSE_X1 and MOUSE_X2 for mouse button 4 and mouse button 5 respectively.
i guess the following names are MOUSE_X3, MOUSE_X4 and so on for mouses with more buttons.

looking in this page i have the idea: SDL_BUTTON_X1

[https://wiki.libsdl.org/SDL2/SDL_MouseButtonEvent](url)

seeya

**Comment by fgsfdsfgs** [comment]
Mouse buttons:
```
	"MOUSE_LEFT",
	"MOUSE_MIDDLE",
	"MOUSE_RIGHT",
	"MOUSE_X1",
	"MOUSE_X2",
	"MOUSE_WHEEL_UP",
	"MOUSE_WHEEL_DN",
```

**Comment by AxisE1028** [comment]
Would it be possible to please confirm the name for Keypad 0 / Insert please? I know that "KP_1" (for example) works fine but I am unable to bind it to Keypad Insert. I've tried "KP_0", "KP_INS", "KP_INSERT", "KP_00", "KP_000" and some more, none of them seem to be the right one.

This is an amazing project, I thank you so much for your time!

**Comment by Sol1vaN** [comment]
> Would it be possible to please confirm the name for Keypad 0 / Insert please? I know that "KP_1" (for example) works fine but I am unable to bind it to Keypad Insert. I've tried "KP_0", "KP_INS", "KP_INSERT", "KP_00", "KP_000" and some more, none of them seem to be the right one.
> 
> This is an amazing project, I thank you so much for your time!

today is not neccesary.
because in game you can rebind all the keys, look:

![pd_2024_05_26_11_26_35_059](https://github.com/fgsfdsfgs/perfect_dark/assets/33560454/476da421-ee7c-439a-8255-31a73322fe3f)
![pd_2024_05_26_11_26_50_598](https://github.com/fgsfdsfgs/perfect_dark/assets/33560454/490f858b-d38a-4eb2-bf79-6965d322b069)
![pd_2024_05_26_11_26_45_108](https://github.com/fgsfdsfgs/perfect_dark/assets/33560454/910f764c-14fc-495e-889d-166b238ce878)
![pd_2024_05_26_11_26_58_129](https://github.com/fgsfdsfgs/perfect_dark/assets/33560454/63dbe9d9-7520-4afc-8b81-0253b17a5737)
