### ISSUE TITLE
Multiplayer intro swirl camera sometimes jitters.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#38]
How to reproduce: Start a multiplayer match, and sometimes the camera swirl animation will jitter.

https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/b07077df-0aaf-470e-bfce-7267fe5bf102

**Comment by fgsfdsfgs** [comment]
This has probably been fixed in d7926f1.

**Comment by ghost** [comment]
Appears to be fixed, this also fixed the Camspy rotation in https://github.com/fgsfdsfgs/perfect_dark/issues/20#issue-1853135268
