### ISSUE TITLE
Movement rework?

### ISSUE THREAD

**Issue by mrwallace888** [fgsfdsfgs/perfect_dark#380]
Hey, when you get the chance, is there a possibility of reworking movement somewhat? It feels very odd at times and it throws me off compared to other FPS games.

Some things I especially wanted to point out:
-Moving diagonally is _significantly_ faster than moving in a cardinal direction which is kind of annoying.
-You have inertia when moving (you don't instantly stop and go), however this inertia does _not_ follow Newtonian behavior. For example, if you're running north and you suddenly change direction and go west, your northern inertia _follows_ your direction change west, instead of you moving west but still fighting the remaining northern inertia. I don't know how else to describe this, but you might know what I'm referring to.

It makes gameplay feel very strange and it's almost nauseating even.

**Comment by fgsfdsfgs** [comment]
Sorry, but I'd say that's modding territory. This is a port of the original game with enhancements, not a remake, and that is how it behaves in the original game. Maybe I'll add some sort of config option for inertia some time in the future.
