### ISSUE TITLE
Three-point filtering shouldn't be applied to some textures

### ISSUE THREAD

**Issue by s-ilent** [fgsfdsfgs/perfect_dark#39]
When using TextureFilter=1, some objects like the distant buildings here still use nearest neighbour filtering. 
![Normal](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/7e944682-6789-4741-9b6b-2b6e3d3e1e18)
This matches up with the original game running in an emulator, so that's not a problem. (Simple64/Parallel)
![Emulated](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/182225bd-78d2-42c1-8e75-38d4fb3b06fc)
However, when using TextureFilter=2, those objects have three-point filtering applied, as well as the UI.
![Three point](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/878fd8ff-6197-4219-9722-5574ee91fc90)

**Comment by TwelveEyes** [comment]
Those buildings are filtered though playing PD on an actual N64. What's the problem?

**Comment by fgsfdsfgs** [comment]
No, that's right, when three-point is turned on all textures are filtered. This is not quite correct as the game uses both filtered and unfiltered textures, the easiest example of the latter being the level previews in the main menu.

**Comment by s-ilent** [comment]
> Those buildings are filtered though playing PD on an actual N64. What's the problem?

On the N64, it isn't the texture filtering itself that smooths the result out but the other filters the hardware does... as far as I know. If you check [some N64 footage](https://www.youtube.com/live/OmiO9X7qf_A?feature=share&t=290) you can see the windows are blocky in a square rather than hexagonal way.

**Comment by OpenRift412** [comment]
This also seems to cause the TextureFilter2D variable to not apply, either.

**Comment by OpenRift412** [comment]
Any further updates on this issue?
