### ISSUE TITLE
Request: Ability to control sentry guns

### ISSUE THREAD

**Issue by NotFragile74** [fgsfdsfgs/perfect_dark#400]
Hey, I don't know if any other alterations will be made to the game's code, but I had an idea: what if there were a way to manually control sentry guns, whether by using a gadget or by hacking in to a terminal?

**Comment by fgsfdsfgs** [comment]
That's pretty out there, don't think this should be in the base port. Should probably be a mod when/if we get enough modding capabilities to pull that off.

**Comment by FrostKnight** [comment]
Sounds very interesting... I remember 007 Nightfire allowed you to do that with their autogun. Of course their autogun could only shoot in two directions and its range flat out sucked.
