### ISSUE TITLE
[Bug] Simulants do not switch weapons after running out of ammo with Classic GE guns

### ISSUE THREAD

**Issue by Atari-Dude** [fgsfdsfgs/perfect_dark#401]
I've noticed that for some simulants in Combat Simulator, they do not seem to reload some gun(s?)-- I've definitely noticed this in particular, with the RC-P45... Some sims will just ignore reloading. But if you turn on the cheat for unlimited ammo no reloads, they will shoot as they should.

https://github.com/fgsfdsfgs/perfect_dark/assets/66316465/f1a64125-23da-452d-b905-3cde9106b658

**Comment by Atari-Dude** [comment]
Upon further research I believe this bug is caused by toggling on Spawn With Weapon.

**Comment by fgsfdsfgs** [comment]
Seems to work fine on my end with the RCP45.

**Comment by fgsfdsfgs** [comment]
This has been confirmed to be fixed.
