### ISSUE TITLE
Textures and objects disappear in Darkness (Datadyne: Extraction level)

### ISSUE THREAD

**Issue by epic-piano** [fgsfdsfgs/perfect_dark#404]
Came across a weird glitch where the skybox will show through objects in the darkness in the 3rd level. I've uploaded a video of the beginning lower floor with and without the night-vision on where you can see the skybox will protrude and show through a seemingly specific texture (if I'm not mistaken). Also, the outside buildings seem do disappear when night-vision is switched off. 

https://www.youtube.com/watch?v=zGpSGaGyJiM
(video was recorded at 3840x1080 resolution, 60fps - apologies if video is still being processed by YouTube)

I should also point out this was on the latest version of the decompiled game (downloaded an half an hour prior to post)
Couldn't see this being mentioned recently, but thought I would bring it to your attention.

**Comment by fgsfdsfgs** [comment]
Known issue, some of these textures are translucent in the dark when they shouldn't be. This is mentioned in #101 already, so I'll close this.
