### ISSUE TITLE
[N64 Bug Fix Request] Give Night Vision at respawn in Perfect Darkness Combat

### ISSUE THREAD

**Issue by jonaeru** [fgsfdsfgs/perfect_dark#405]
In Perfect Darkness (Cheat) you have the Night Vision first, but if you kilked you never get it again.
I think it would be nice if I could get that every time we respawn.

**Comment by fgsfdsfgs** [comment]
Should be fixed now that your PR is merged.

**Comment by blaiz** [comment]
Oh yeah there's a similar issue if you have the "Cloak" cheat and you die, then you respawn without the Cloak. I might spend some time and see if I can also make it so you always respawn with the Cloak if the cheat is active. Curious that that's not how the game already works.
