### ISSUE TITLE
[N64 Bug Fix Request] Fix X-Ray Scanner model in Combat Simulator

### ISSUE THREAD

**Issue by jonaeru** [fgsfdsfgs/perfect_dark#407]
The X-Ray Scanner model is Night Vision, which looks wrong.

![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/2eac214e-117b-427c-849d-e14cf045d4c1)

**Comment by jonaeru** [comment]
Correct model
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/64701608/7832f0c6-7d9a-47d5-b54e-91a7538c9b06)

**Comment by fgsfdsfgs** [comment]
Should be fixed now that your PR is merged.
