### ISSUE TITLE
radial menu should be on Q instead of G

### ISSUE THREAD

**Issue by cylonicboom** [fgsfdsfgs/perfect_dark#41]

**Comment by cylonicboom** [comment]
Is blocked by #40

**Comment by ghost** [comment]
You should also be able to use the mouse for selecting items with the Radial menu. This behaviour is consistent with 1964 GEPD, and makes more sense than using WASD while holding Q, or letting go of the mouse to use the arrow keys to select an item.

**Comment by MultipleMegaPixels** [comment]
The Q radial menu has this bug where you cant change to weapons that are located in the left up and down corner.

To replicate: press Q, and while holding it down, press W and A or S and A
