### ISSUE TITLE
[Bug] FistSims will pick up Classic weapons and equip, but can't do anything with them

### ISSUE THREAD

**Issue by Atari-Dude** [fgsfdsfgs/perfect_dark#413]
The FistSim utilizes some weapons like a Falcon 2 and can use its secondary function to allow him to pistol whip. But the Classic weapons should be blocked from FistSim's repertoire since they do not feature such a secondary function.

https://github.com/fgsfdsfgs/perfect_dark/assets/66316465/e15162b8-ca76-463a-9ff3-de3f9702f165

The stage (Stack) is from a mod, but behavior occurs in base game identically.

**Comment by fgsfdsfgs** [comment]
This has been confirmed to be fixed.
