### ISSUE TITLE
Weapon firing mode malfunctions

### ISSUE THREAD

**Issue by spamzilla** [fgsfdsfgs/perfect_dark#424]
Frequently in the combat simulator the weapon I'm using will be in the other firing state than what is displayed on the screen. I tried restarting the program but it didn't work. On N64 it takes a couple seconds to switch firing modes but I don't know if that has anything to do with it.

**Comment by Atari-Dude** [comment]
I don't use extended controls, but I've never encountered anything like this since I started playing on the PC port daily last year. I know that if you swap weapon functions while actively firing, it won't swap until you let up and then start firing again. But I'm guessing that's not what you mean?

**Comment by spamzilla** [comment]
I'm not sure about extended controls? What I mean is that the modes get mixed up. I'm having a hard time reproducing this glitch though.

**Comment by fgsfdsfgs** [comment]
Is this in a network game? If not, is it possible to record a video or something?

**Comment by cylonicboom** [comment]
What weapon does this happen with?

**Comment by spamzilla** [comment]
I've been trying to recreate the situation this was happening in for about an hour now and I haven't had any luck. It was with 7 simulants, a random map, random weapons, and capture the briefcase mode. It was happening with all of my guns. It wasn't a network game.

**Comment by spamzilla** [comment]
Sorry guys.. false alarm. I determined that the problem was my keyboard. I have a wireless one sitting on top of a worn out laptop keyboard. It was hitting shift through the keyboard.

**Comment by spamzilla** [comment]
Sorry guys.. false alarm. I determined that the problem was my keyboard. I have a wireless one sitting on top of a worn out laptop keyboard. It was hitting shift through the keyboard.
