### ISSUE TITLE
A detailed tutorial on how to create exe files?

### ISSUE THREAD

**Issue by NMSS1984** [fgsfdsfgs/perfect_dark#425]
Hello, this is the first time I write here, and desperation has led me to this, I guess...

I've been trying to build an exe for the PAL version of the game for Windows using MSYS2 for several hours. I don't have much knowledge about messing with code, but I'm watching similar tutorials and trying to learn how to use it. Obviously no luck. I have run into the impossibility of building a version of the EXE for the PAL version even though I have followed the steps, but either something is not working right for me, or I am too stupid to understand them.

I have already read that several people have asked you for an EXE for the other versions, whether PAL or JAP; and I've also seen that you intend to release them at some point or implement a single EXE for all versions of the game, which I suppose will take time. So, for the moment, perhaps a tutorial aimed at people not familiar with MSYS2 will help us create our EXE and work quietly in the meantime.

I am not proposing that this tutorial be done by you, but by anyone who has knowledge of this and wants to help, of course. Because looking for information about errors without having anything to do with what you are trying to do makes it even more confusing.

And well, it was just this, I'm sorry to be another one on the list asking about the EXE for your region. Greetings, thank you for your attention and for all your work.

**Comment by jonaeru** [comment]
I have posted instructions on how to build on my website, sorry but it's in Japanese. I hope this is helpful.
http://pdlabo.knowhow.jp/pc-port/pd-pc-port/#i-5

For the Japanese version, `ROMID=jpn-final` needs to be added to the make command.
Similarly, for the PAL version, add `ROMID=pal-final`.

`make -f Makefile.port ROMID=pal-final`

**Comment by NMSS1984** [comment]
> I have posted instructions on how to build on my website, sorry but it's in Japanese. I hope this is helpful. http://pdlabo.knowhow.jp/pc-port/pd-pc-port/#i-5
> 
> For the Japanese version, `ROMID=jpn-final` needs to be added to the make command. Similarly, for the PAL version, add `ROMID=pal-final`.
> 
> `make -f Makefile.port ROMID=pal-final`

Thanks a lot! It was exactly what I needed. With these instructions I have finally been able to create the executable for the European version :)

Thank you again and I hope the project continues to grow.

**Comment by fgsfdsfgs** [comment]
Automatic builds now include executables for PAL and JPN. I've also updated the build instructions a little bit to make them slightly less vague.
