### ISSUE TITLE
I found a softlock in Co-Operative mode

### ISSUE THREAD

**Issue by spamzilla** [fgsfdsfgs/perfect_dark#428]
I discovered that trying to play Co-Operative 'Area 51 - Escape' on Agent mode causes the CPU simulant to spawn too closely to the player. This means that you cannot aim left or right or move at all. You can only look up and down. Just to test it, I enabled the Phoenix cheat and it _is_ possible to kill the simulant and continue forward as normal (other than the health you lose). 

![Perfect Lock](https://github.com/fgsfdsfgs/perfect_dark/assets/48328838/c8c43eb4-9f52-466f-a0e1-19d258f4f653)

**Comment by fgsfdsfgs** [comment]
[Known bug.](https://github.com/fgsfdsfgs/perfect_dark/issues/270)

**Comment by spamzilla** [comment]
Oh sorry! I just found out you can pistol whip the simulant to death too...
