### ISSUE TITLE
Linux Clang `stdlib.h` Build Error Failure (`conflicting types for 'random'`)

### ISSUE THREAD

**Issue by ThisNekoGuy** [fgsfdsfgs/perfect_dark#429]
[build-log.txt](https://github.com/fgsfdsfgs/perfect_dark/files/15287864/build-log.txt)

Linux Distro: Gentoo (LLVM17-built via [`libc++` standard library](https://libcxx.llvm.org) and `glibc`)
Specific Toolchain Used: Clang 17.0.6

## Reproduction Steps
1. Clone the repo and `cd` into it
2. Run `make -f Makefile.port TARGET_PLATFORM=i686-linux TOOLCHAIN=i686-pc-linux-gnu-clang` and wait for build failure
3. [`sed -i 's|-std=c11|-std=gnu11|g' Makefile.port` and `sed -i 's|-std=c11|-std=gnu11|g' Makefile`](https://github.com/fgsfdsfgs/perfect_dark/issues/317#issuecomment-1866159296)
4. `sed -i 's|gcc||g' Makefile.port` and `sed -i 's|gcc||g' Makefile`
(`gcc` gets appended to the end of `i686-pc-linux-gnu-clang` like "i686-pc-linux-gnu-clanggcc" for some reason)
5. `sed -i 's|g++|clang++|g' Makefile.port` and `sed -i 's|g++|clang++|g' Makefile` (g++ remains in the make files for some reason, like `gcc`, despite the configuration being set initially)
6. Run `make -f Makefile.port TARGET_PLATFORM=i686-linux TOOLCHAIN=i686-pc-linux-gnu-clang` again
7. Wait for `/usr/include/stdlib.h:521:17: error: conflicting types for 'random'`

## Description
Like the MacOS issue (https://github.com/fgsfdsfgs/perfect_dark/issues/317), Clang building fails but for a different error from what I've read over there.

**Comment by fgsfdsfgs** [comment]
> gcc gets appended to the end of i686-pc-linux-gnu-clang like "i686-pc-linux-gnu-clanggcc" for some reason

It gets appended because the Makefile expects gcc. It just takes a toolchain prefix and then appends compiler executable names (`gcc`, `g++`) to it. This was meant mostly for different architectures rather than different compilers.

The issue you're experiencing is the result of enabling GNU extensions on all files. This exposes [`random()`](https://linux.die.net/man/3/random), which conflicts with a function with the same name in the PD decomp codebase. I'll probably have to rename it. It probably won't be the only name conflict either.

**Comment by ThisNekoGuy** [comment]
Seems to happen without step 3 too (leaving `-std=c11` alone); this seems to trigger it more easily without needing the `sed` replacements just after cloning:
```bash
make -f Makefile.port TARGET_PLATFORM=i686-linux TOOLCHAIN=i686-pc-linux-gnu-clang CC="clang" CXX="clang++" CPP="clang-cpp" AR="llvm-ar" NM="llvm-nm" AS="llvm-as" RANLIB="llvm-ranlib" OBJDUMP="llvm-objdump" OBJCOPY="llvm-objcopy" STRINGS="llvm-strings" READELF="llvm-readelf" ADDR2LINE="llvm-addr2line" STRIP="llvm-strip"
```

**Comment by fgsfdsfgs** [comment]
Might also be due to it being exposed by default in glibc. I'll see what I can do.

**Comment by fgsfdsfgs** [comment]
Committed a bunch of changes. I can now build it with Clang 16 on Linux without any Makefile edits by running `make -f Makefile.port TARGET_PLATFORM=i686-linux CC=clang CXX=clang++`.

**Comment by ThisNekoGuy** [comment]
3 errors in `include/PR/os_libc.h` under Clang 17:
[build-log.txt](https://github.com/fgsfdsfgs/perfect_dark/files/15296278/build-log.txt)

**Comment by fgsfdsfgs** [comment]
Removed that `sprintf` declaration from there.

**Comment by ThisNekoGuy** [comment]
Builds now :+1:
Might want to remove the `.exe` for Linux builds though; Linux can detect it's a binary without the extension but leaving it with the `.exe` will make anyone who doesn't think twice of it (like Linux newbies) launch it with Wine instead by accident if they click on it

**Comment by fgsfdsfgs** [comment]
Yeah, I'm aware. Couldn't be arsed to add a thing in the Makefile to change the extension.
