### ISSUE TITLE
Portal issue in Attack Ship

### ISSUE THREAD

**Issue by murkantor** [fgsfdsfgs/perfect_dark#43]
Just before you enter the bridge, the lift portal seems to break. It works when you enter the lift, but exiting makes the player fall into the void into the hangar below.
![1](https://github.com/fgsfdsfgs/perfect_dark/assets/38683527/281c7620-1109-4eb1-9325-d664339d4f96)

Video:
https://youtu.be/FFKq9rrbYps

**Comment by murkantor** [comment]
Update: Just tested on #53 and the issue still occurs.

**Comment by fgsfdsfgs** [comment]
This might be fixed as of latest few commits.

**Comment by fgsfdsfgs** [comment]
Okay, now it should be fixed for real.
