### ISSUE TITLE
Add 60HZ function for PAL version

### ISSUE THREAD

**Issue by Dreamboum** [fgsfdsfgs/perfect_dark#433]
The PAL version is limited to 50Hz. It would be nice if you could increase this limit to 60Hz like the USA version.

**Comment by fgsfdsfgs** [comment]
You can already do this by setting `TickRateDivisor=0` and `FramerateLimit=60` in `pd.ini` (or `FramerateLimit=0` and `VSync=1` if your monitor is 60Hz). I will probably eventually merge all versions into one executable that runs at 60.

**Comment by fgsfdsfgs** [comment]
Other than the solution above, this will be solved automatically when I make the port support loading all possible ROMs, so I'll close this issue.
