### ISSUE TITLE
Impossible to go back with a controller

### ISSUE THREAD

**Issue by Dreamboum** [fgsfdsfgs/perfect_dark#434]
I've been following your project since the beginning. I don't remember if there was a backspace bug. With the controller, it's impossible to go back, you have to use the keyboard and press Escape.

**Comment by Shivaan88k** [comment]
Something got changed on a new update, but can be fixed by rebinding Use/Cancel. Go to Key Bindings in Extended Options.

**Comment by fgsfdsfgs** [comment]
You don't have to rebind it. Disable "Mouse menu navigation" in the Extended mouse options. This will be fixed properly soon.

**Comment by fgsfdsfgs** [comment]
Should be fixed now.
