### ISSUE TITLE
Crash on dataDyne Central - Defection on Special Agent

### ISSUE THREAD

**Issue by MorriganAensland-Hill** [fgsfdsfgs/perfect_dark#441]
It was my first time on playing the PC Port, as I played on the first mission on Special Agent difficulty. Whenever I picked up the shield dropped by the enemy guard I shot, the game crashed.

**Comment by fgsfdsfgs** [comment]
Is there a file called `pd.crash.log` in the game folder? Or in `~/.local/share/perfectdark` if you're using Linux.
Please post that if there is.

**Comment by MorriganAensland-Hill** [comment]
Crash!

EXCEPTION: 0xc0000005
PC: 00643dca
MODULE: [004c0000]
MAIN MODULE: [004c0000]

BACKTRACE:
#00: 00643dca: [004c0000]+00183dca
#01: 61feb1dc: SDL_DYNAPI_entry+1430124
#02: 61e62bb2: [61e60000]+00002bb2
#03: 0062cff8: [004c0000]+0016cff8
#04: 00640a81: [004c0000]+00180a81
#05: 00643f25: [004c0000]+00183f25
#06: 61e649c4: [61e60000]+000049c4
#07: 00644f0a: [004c0000]+00184f0a
#08: 0062905e: [004c0000]+0016905e
#09: 00649665: [004c0000]+00189665
#10: 00649546: [004c0000]+00189546
#11: 00649813: [004c0000]+00189813
#12: 75c484b5: beginthreadex+213
#13: 75c48581: endthreadex+145
#14: 75867ba9: BaseThreadInitThunk+25
#15: 774dbe3b: RtlInitializeExceptionChain+107
#16: 774dbdbf: RtlClearBits+191


I think it has to do with the crosshair colour and GE64 muzzle flash settings turned on. I tried to reconstruct the crash, but it worked OK until I was at the elevator.

**Comment by fgsfdsfgs** [comment]
This was because of the recent multithreaded audio changes. I've reverted them for now because of this and other audio-related issues that cropped up today, so this should be fixed now.
