### ISSUE TITLE
Unlock Counter Operative mode for Solo and Netplay

### ISSUE THREAD

**Issue by Alexkander66** [fgsfdsfgs/perfect_dark#451]
![Counter Operative](https://github.com/fgsfdsfgs/perfect_dark/assets/144574408/9f043bcb-265e-44fe-9a55-c80ea8c16325)

It frustrates me that Counter Operative mode is blocked in single-player. I was wondering if you could unlock it. I know it's pointless, but I hate seeing modes blocked, and the game isn't really 100% finishable without it. I'm also wondering if you're going to include the Counter Operative mode for Netplay?

**Comment by fgsfdsfgs** [comment]
You can just set `FakeGamepads` to `2` in `pd.ini` to unlock it. That will still spawn a player 2 that doesn't do anything though, because it isn't really an option to have it with one player.
It is not available in netplay, but may be implemented in the future.

**Comment by Alexkander66** [comment]
In fact, it's useless solo. There are no stars in Counter Operative mode on N64. I confused it with the XBLA version where they were available.

**Comment by fgsfdsfgs** [comment]
I guess I'll consider this solved for now, other than the netplay part.
