### ISSUE TITLE
Would it be possible to combine Linux and Windows for automatic build?

### ISSUE THREAD

**Issue by Dreamboum** [fgsfdsfgs/perfect_dark#455]
I was wondering if it was possible to combine the two together.

**Comment by fgsfdsfgs** [comment]
What do you mean?

**Comment by Dreamboum** [comment]
Put Linux and Windows in the automatic build without having to download separate versions.

**Comment by fgsfdsfgs** [comment]
I don't really see why I'd want to do that. The executables are already fat as it is.

**Comment by Dreamboum** [comment]
The file is 50 MB, it's tiny. In short, as you wish.

**Comment by fgsfdsfgs** [comment]
I think I'd rather keep them separate. Windows users don't really need Linux binaries, Linux users *might* need Windows binaries if the game for some reason runs better under Wine for them, and users that want both are rare enough that I doubt downloading a second ZIP would be a major inconvenience. Not to mention it's easier to write CI scripts to handle them separately.
