### ISSUE TITLE
About the unification of PD versions to USA Rev 1?

### ISSUE THREAD

**Issue by Dreamboum** [fgsfdsfgs/perfect_dark#456]
You said you were going to unify everything on the USA REV1 version, but are you going to keep the exclusive assets of the Japanese version as well as the debug versions?

**Comment by fgsfdsfgs** [comment]
I don't know yet. I don't even know what those assets are.

**Comment by Dreamboum** [comment]
![maxresdefault](https://github.com/fgsfdsfgs/perfect_dark/assets/65136045/812b1bbf-e461-4e22-acfa-880e38d73a48)



https://censorship.fandom.com/wiki/Perfect_Dark?veaction=edit&section=1
The Japanese version isn't really an asset, it's just that Joanna Dark's skin is different and the bodies disappear due to Japanese censorship.

**Comment by fgsfdsfgs** [comment]
The face texture is loaded from the ROM, so you'll have the JP one if you have the JP ROM. Codebase would be that of NTSC, except with text rendering changes where necessary.

**Comment by Dreamboum** [comment]
So you'd have to modify the ROM, which you don't want to do. Because I've tried this Japanese ROM translated into English and, strangely enough, it makes no difference: the ROM remains in Japanese when I use your PC port.

http://n64vault.com/pd-misc:japanese-with-eng-text

**Comment by fgsfdsfgs** [comment]
No. Why would you want to modify the ROM? If you want JP ROM with the original face textures, you can just replace them with a mod.
That ROM changes a variable that makes the JP version use its built in English translation. This won't translate to the port because the port doesn't load code from the ROM.

**Comment by fgsfdsfgs** [comment]
I guess I'll consider this question answered.
