### ISSUE TITLE
White ball of light passing through the weapon

### ISSUE THREAD

**Issue by Dreamboum** [fgsfdsfgs/perfect_dark#459]
![55588585](https://github.com/fgsfdsfgs/perfect_dark/assets/65136045/f1eeee9b-65b5-4693-9e89-4ffcfac4b398)

I don't know if anyone noticed this bug on the PC version, but in the N64 version this white ball of light doesn't pass through the weapon.

**Comment by fgsfdsfgs** [comment]
Known issue.
