### ISSUE TITLE
VSync Force On Causes Freeze at Launch

### ISSUE THREAD

**Issue by shoober420** [fgsfdsfgs/perfect_dark#462]
I'm on a Windows 11 machine with the latest NVIDIA drivers as of writing (555.99), and experience the game freezing at launch and stuck at 1 fps when having VSync set to Force on. Having VSync set to "Force off" will run the game fine, with some minor tearing and stuttering. Having VSync set to "Use the 3D application setting" appears to enable Vsync without the game freezing at launch. Why is the game freezing and stuck at 1 fps if I have VSync Force on, but runs fine with VSync if "Use the 3D application setting" is selected?

**Comment by fgsfdsfgs** [comment]
I don't know, I don't develop NVIDIA drivers. You shouldn't have to set it to "Force on" because you can enable vsync in the game's config file (`pd.ini`). Does that not work for you?

**Comment by shoober420** [comment]
With VSync at "Use the 3D application setting", and VSync=1 in pd.ini file, VSync is enabled and works great. It must be a NVIDIA driver bug when using Force on for VSync. My apologies.

**Comment by fgsfdsfgs** [comment]
It might have been screwing up because you were basically forcing vsync on top of the vsync that was already enabled, and I'm not even sure what that would do. In general the control panel overrides are a last resort if the game settings don't work or don't have something you need.
