### ISSUE TITLE
Suggestion make it work without 32 bit libraries.

### ISSUE THREAD

**Issue by FrostKnight** [fgsfdsfgs/perfect_dark#463]
Also, I don't know what specific dependencies are needed, but I would love to be able to  use it with as few dependencies as possible.

I currently use sndio and xenocara. I use a chimaera of a linux distro. Just a heads up. But yeah, I have much interest in this.

**Comment by fgsfdsfgs** [comment]
This is not that easy. The game currently cannot be built for 64-bit targets, so the 32-bit libraries are necessary. There are a couple other issues about 64-bit support, so I'll close this one. When that is implemented this problem will automatically go away.

**Comment by FrostKnight** [comment]
> This is not that easy. The game currently cannot be built for 64-bit targets, so the 32-bit libraries are necessary. There are a couple other issues about 64-bit support, so I'll close this one. When that is implemented this problem will automatically go away.

So Basically, when you think its possible to do so, without insane amounts of work you will reconsider?

I am just trying to understand the context between what you said from This is not easy, to When that is implemented this problem will automatically go away.

I just want to understand for this reason. Let me know.

**Comment by megatog615** [comment]
Essentially the game needs to be ported to 64-bit.

**Comment by FrostKnight** [comment]
> Essentially the game needs to be ported to 64-bit.

Is that even possible? 

Btw, I assume it would be too much work to have the multilib libaries added to this program directly . You know, so you wouldn't need to get any 32 bit libraries externally.

Btw, who is it who ported it to 32 bit? Just curious.

**Comment by fgsfdsfgs** [comment]
Yes, it is possible. It requires quite a lot of work.
The game was already "32-bit". This means it assumes things like address/pointer sizes being 32-bit in a lot of places, which is the crux of the problem. When I was porting it to PC I did not fix this because I wanted to get it to work first.
You can't really "add" libraries to the Linux builds. Every Linux distro under the sun has different packages and library versions. Things like Flatpak and AppImage are supposed to deal with this, but the PR for Flatpak (#165) seems to have been abandoned.

**Comment by FrostKnight** [comment]
> Yes, it is possible. It requires quite a lot of work. The game was already "32-bit". This means it assumes things like address/pointer sizes being 32-bit in a lot of places, which is the crux of the problem. When I was porting it to PC I did not fix this because I wanted to get it to work first. You can't really "add" libraries to the Linux builds. Every Linux distro under the sun has different packages and library versions. Things like Flatpak and AppImage are supposed to deal with this, but the PR for Flatpak (#165) seems to have been abandoned.

So if you got it to work, would you consider porting it to 64 bit?  Or was that something you thought about before but 
changed your mind on.

I didn't realize you couldn't add libraries to linux builds. My bad...

**Comment by fgsfdsfgs** [comment]
Yes, 64-bit support is planned.

**Comment by FrostKnight** [comment]
> Yes, 64-bit support is planned.

Alrighty, that's all I needed to know. Thanks
