### ISSUE TITLE
Another Idea: New weapons

### ISSUE THREAD

**Issue by FrostKnight** [fgsfdsfgs/perfect_dark#465]
I have in the past thought, a flamethrower (depends how long it hits you for) and a sword (mostly one hit kill) 

Would be cool weapons to have.

**Comment by fgsfdsfgs** [comment]
This is a bit out of scope for the project. Might be a good idea for a mod though.

**Comment by FrostKnight** [comment]
> This is a bit out of scope for the project. Might be a good idea for a mod though.

This was literally a shot in the dark as an idea. ;)

So no problem.

**Comment by FrostKnight** [comment]
Actually, been meaning to ask, do you know of anyone who uses this page who would be willing to add weapons from say nighfire, agent underfire, both gamecube games, to perfect dark?

There are two weapons I would love added from both, one has something called trip mines, you pass by the lazer coming out of the mine and the bomb  usuallykills you

And the other is a samurai weapon which has a slayer like damage on overcharge mode and non-overcharge mode it does a lot of dmg just shooting a lazer. takes like half of the health off of it hits in the body.

Also has a scope on it that you can use to shoot it from faraway.

I know your project doesn't plan to do this, but I would be interested if you knew anyone who would be interested in making a rom hack with these and other weapons added to the perfect dark rom. To put it bluntly, would love to see all three games weapons put into Perfect Dark.  Would be beyond awesome.  I don't know who would be willing to, but it would sound badass as all get out.
