### ISSUE TITLE
Retire the old Makefile and make Makefile.port "Makefile"

### ISSUE THREAD

**Issue by megatog615** [fgsfdsfgs/perfect_dark#467]
Is there a reason why the original Makefile is being held on to? Maybe the Makefile.port should be Makefile and the old Makefile should be removed or renamed.

**Comment by fgsfdsfgs** [comment]
There's no particular reason. At first I was keeping it to see if I still could build the N64 ROM, but that's impossible by now. I'll probably remove it.
