### ISSUE TITLE
Switch to CMake

### ISSUE THREAD

**Issue by megatog615** [fgsfdsfgs/perfect_dark#468]
As an alternative to #467, switch to CMake to generate system-specific Makefiles.

**Comment by fgsfdsfgs** [comment]
I'll consider it.

**Comment by FrostKnight** [comment]
> I'll consider it.

I prefer regular make myself. Then its easier to port to other OS, such as BSDs for example.  Also, cmake is bigger in bloat.

Just sayin

**Comment by fgsfdsfgs** [comment]
This is now done. Though still no exotic platform support.
