### ISSUE TITLE
[BUG] Building issues...

### ISSUE THREAD

**Issue by WindmillPunch** [fgsfdsfgs/perfect_dark#472]
No matter what, I can't seem to build it... The auto build gives me this error. I've tried a few different solutions such as running it as an administrator as well as changing the location of the folders.

![Screenshot 2024-06-20 210403](https://github.com/fgsfdsfgs/perfect_dark/assets/114552514/206c806a-4d27-4cac-bdef-c7f2396684fe)

When it came to the manual building using Mingw32, while downloading dependencies and checking package integrity it would give errors such as:

error: mingw-w64-i686-bzip2: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/mingw-w64-i686-bzip2-1.0.8-2-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).

And ask if I want to delete it, I tell it no for all instances, of that one by one, but eventually it tells me:
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.

Unsurprisingly, continuing down this process results in errors and I'm not able to get much further. I'm just rather confused as to what's causing this as I'm not seeing anyone else having this kind of issue. I also apologize if this is a misuse of the github issues page.

**Comment by fgsfdsfgs** [comment]
Enable file name extensions in Windows Explorer. Your ROM is actually named something like `pd.ntsc-final.z64.z64`. You can confirm this by right clicking it and going to Properties. Remove the second extension and it should work.
As for the second error, reinstall msys2.

**Comment by WindmillPunch** [comment]
That is exactly what the issue was... Thank you so much. I had thought I enabled file name extensions previously but apparently did not... that's embarrassing.
