### ISSUE TITLE
Can't map C-buttons while mapping key bindings

### ISSUE THREAD

**Issue by NotFragile74** [fgsfdsfgs/perfect_dark#478]
I'm trying to get the key bindings for the N64 controllers to match the original N64 controls, but whenever I try to map the strafe function, I can't map any of the C-buttons to it. I can only strafe using the C-buttons for Player 1 on the 1.1 controller scheme.

**Comment by fgsfdsfgs** [comment]
Works just fine on my end. What exactly can't you bind? What do you press, what do you expect to happen and what actually happens? Are you trying to bind them to a physical N64 controller?

**Comment by NotFragile74** [comment]
> Works just fine on my end. What exactly can't you bind? What do you press, what do you expect to happen and what actually happens? Are you trying to bind them to a physical N64 controller?

I'm trying to get it so that I can use the left and right C-buttons to strafe for Player 2. However, when it asks me to press a new key or button, pressing the C-buttons does nothing, and I can only use the D-pad to strafe for Player 2. And yes, I am trying to bind them to an N64 controller. I know it's not a controller issue because I've tried two different controllers in Player 2's port, and the C-buttons won't strafe on either one, but they will for Player 1.

**Comment by fgsfdsfgs** [comment]
It sounds like the C buttons are being detected as a hat or stick or something. Maybe try disabling "Analog Movement" in the Extended Gamepad Options menu. If that doesn't work, try downloading [this file](https://raw.githubusercontent.com/mdqinc/SDL_GameControllerDB/master/gamecontrollerdb.txt) and placing it in the same folder as `pd.exe`.

**Comment by NotFragile74** [comment]
OK, I think I got it working. I don't know if it was the file or disabling "Analog Movement", but I can now strafe with the C-buttons. Thanks!
