### ISSUE TITLE
Game window sometimes losing focus and becoming uncontrollable

### ISSUE THREAD

**Issue by erikmartinessanches** [fgsfdsfgs/perfect_dark#481]
Until I click on the window again with the mouse, to focus the window so that it takes input again. (I am not using mouse controls, just a wireless xbox game pad.) Windows 10.

**Comment by fgsfdsfgs** [comment]
Just loses focus by itself? Or do you move your cursor to a different monitor or click something or something else happens?
If it's not by itself, then that's kind of intentional behavior. I will add an option to receive gamepad input regardless of window focus, as mentioned in #475.

**Comment by erikmartinessanches** [comment]
My bad, turns out my bluetooth xbox controller was getting out of range.
