### ISSUE TITLE
Can't copy saved games over

### ISSUE THREAD

**Issue by NotFragile74** [fgsfdsfgs/perfect_dark#486]
I tried copying the game folder over to my laptop so I could play this game on the road, but none of my save data (single player agent files, combat simulator player files, etc...) copied over. Is it located in a different folder?

**Comment by fgsfdsfgs** [comment]
The save file is called `eeprom.bin` and the config file is called `pd.ini`.

On Windows they are normally going to be in the same folder as `pd.exe`. If you put your game in `Program Files` or some other folder with no write access, it will instead write them to `%APPDATA%\perfectdark` (either paste that directly into the File Explorer's address bar or go to `C:\Users\YOUR_USERNAME\AppData\Roaming\perfectdark`).

On Linux they're normally located in `~/.local/share/perfectdark`.

**Comment by NotFragile74** [comment]
> The save file is called `eeprom.bin` and the config file is called `pd.ini`.
> 
> On Windows they are normally going to be in the same folder as `pd.exe`. If you put your game in `Program Files` or some other folder with no write access, it will instead write them to `%APPDATA%\perfectdark` (either paste that directly into the File Explorer's address bar or go to `C:\Users\YOUR_USERNAME\AppData\Roaming\perfectdark`).
> 
> On Linux they're normally located in `~/.local/share/perfectdark`.

OK, I deleted the copy of the game folder and tried copying it again, and it works! Thank you!
