### ISSUE TITLE
Weapon that passes through walls at certain levels

### ISSUE THREAD

**Issue by Dreamboum** [fgsfdsfgs/perfect_dark#490]
![Weapon that passes through walls at certain levels](https://github.com/user-attachments/assets/7bcd8329-8304-4e54-987a-b2c2763d61a8)

I don't know if other people have reported this problem, but on the Carrington Villa level, the weapons go through walls, regardless of the NTSC, PAL or JPN version.

**Comment by fgsfdsfgs** [comment]
Does that still happen on the [very latest build](https://github.com/fgsfdsfgs/perfect_dark/releases/tag/ci-dev-build)?

**Comment by Dreamboum** [comment]
No, it no longer does it on the latest build. Sorry I did not see

**Comment by fgsfdsfgs** [comment]
That's alright, thanks for checking.
