### ISSUE TITLE
How do I set N64 analog stick sensitivity?

### ISSUE THREAD

**Issue by NotFragile74** [fgsfdsfgs/perfect_dark#492]
I love having the option to play with a mouse or an N64 controller, but there's one problem: the N64 controller analog stick seems too sensitive, and I'm not sure how to change it. How do I change it?

**Comment by fgsfdsfgs** [comment]
Extended Options -> Controller -> Player # -> Stick Settings -> change the scale values.

**Comment by NotFragile74** [comment]
> Extended Options -> Controller -> Player # -> Stick Settings -> change the scale values.

OK, wasn't sure. Thanks!
