### ISSUE TITLE
Weird light reflexions on glass

### ISSUE THREAD

**Issue by johnblade** [fgsfdsfgs/perfect_dark#495]
Hi,
Played few months ago and don't notice this odd light reflexions on glass.
Don't know if it's me or a change, but it's very distracting...

[HERE](https://1drv.ms/v/s!AvpqXtvjYA0-gaVXTAxvy6gceFN4gg?e=LZgBv8) a video to illustrate...

**Comment by fgsfdsfgs** [comment]
That's just the GE/PD reflection map. It do be like that.

**Comment by BiatuAutMiahn** [comment]
looks like an FOV issue, I dont remember the orig PD doing that with reflections.

**Comment by LonelySpaceDetective** [comment]
> looks like an FOV issue, I dont remember the orig PD doing that with reflections.

Just loaded the game up with default FOV and even the original aspect ratio it ran at on N64, still does the weird thing the OP recorded.
I can't say I really feel like loading up an N64 emulator or my physical copy right now to confirm if this is original behavior, but I can at least confirm it has nothing to do with the FOV.

**Comment by johnblade** [comment]
I tested on MiSTer with N64 core and CRT TV, and yes it's almost the same maybe less ([VIDEO](https://1drv.ms/v/s!AvpqXtvjYA0-gaVYCiJYgTiXapBgxA?e=5HVXOO))
We didn't notice much that because N64 version is blurry as hell and so slow that is limit unplayable (don't know how I can play that when I was younger)...
First video was played with default settings on a 4:3 CRT VGA monitor.
