### ISSUE TITLE
[Feature Request] Imitate the Transfer Pak functionality of the original N64 game

### ISSUE THREAD

**Issue by LonelySpaceDetective** [fgsfdsfgs/perfect_dark#496]
Kinda stupid, but it's technically a missing feature from the N64 game, and might be convenient for people who don't want to use the Unlock Everything button but see the Transfer Pak as a legitimate method of unlocking some of the cheats. I also just find the interaction kinda neat, I guess.

I think the ideal implementation would be that the PC port checks the data directory for the Perfect Dark GBC ROM when booting, and if present the Transfer Pak cheats are automatically unlocked.

**Comment by fgsfdsfgs** [comment]
#499 has been merged, this is now a thing.
