### ISSUE TITLE
Can't use modded ROMs for the PC port

### ISSUE THREAD

**Issue by NotFragile74** [fgsfdsfgs/perfect_dark#498]
OK, so I was doing a little experiment: I made a copy of the PD folder and attempted to use a modded ROM where you could play as _Mario_ characters. Unfortunately, I got an error where it said I couldn't play the game because the ROM size was too big. Will there be any fix for this at some point?

**Comment by cylonicboom** [comment]
The rom is checked against the 1.1 hash. To play PD64 mods you need to extract the assets (like the level lists, files, etc) and re implement any new logic that isn't implemented as pure level ailsts

https://github.com/fgsfdsfgs/perfect_dark/wiki/Modding

**Comment by fgsfdsfgs** [comment]
It's not checked against the hash, it just checks the header and size. You can actually use the 1.0 ROM as well.

This is not a bug. It is not trivial to support modded ROMs. ROMs with custom code (such as GE X) can't be supported at all. Most I could do is support ROMs with asset replacements, but some of those would require a custom segment map, and you can already replace some assets via the aforementioned modding features. So for the general case this probably won't ever be a feature.
