### ISSUE TITLE
Slackware(64) 15.0 - I Cant compile net-port version.

### ISSUE THREAD

**Issue by inukaze** [fgsfdsfgs/perfect_dark#500]
[ inukaze  | 28-08-2024 | 02:05 pm ]
[~]$ `su`
Contraseña: 

[ root | 28-08-2024 | 02:05 pm ]
[inukaze]$ `mkdir -p /media/Compartido/Temporal/src`

[ root | 28-08-2024 | 02:05 pm ]
[inukaze]$ `cd /media/Compartido/Temporal/src`

[ root | 28-08-2024 | 02:05 pm ]
[src]$ `git clone https://github.com/fgsfdsfgs/perfect_dark perfect_dark_net-port`

> Clonando en 'perfect_dark_net-port'...
> remote: Enumerating objects: 93070, done.
> remote: Counting objects: 100% (1013/1013), done.
> remote: Compressing objects: 100% (324/324), done.
> remote: Total 93070 (delta 711), reused 946 (delta 675), pack-reused 92057 (from 1)
> Recibiendo objetos: 100% (93070/93070), 114.03 MiB | 138.00 KiB/s, listo.
> Resolviendo deltas: 100% (76799/76799), listo.
> Actualizando archivos: 100% (2271/2271), listo.
> 

[ root | 28-08-2024 | 03:07 pm ]
[src]$ `cd perfect_dark_net-port`

[ root | 28-08-2024 | 03:07 pm ]
[perfect_dark_net-port]$ `git checkout port-net`

> rama 'port-net' configurada para rastrear 'origin/port-net'.
> Cambiado a nueva rama 'port-net'
>

[ root | 28-08-2024 | 03:07 pm ]
[perfect_dark_net-port]$ `git submodule update --init --remote --recursive`

> Submódulo 'tools/recomp' (https://github.com/Emill/ido-static-recomp.git) registrado para ruta 'tools/recomp'
> Clonando en '/media/Compartido/Temporal/src/perfect_dark_net-port/tools/recomp'...
> Ruta de submódulo 'tools/recomp': check out realizado a '421e546956ceae984927e609b083195e9e81659e'
> 

[ root | 28-08-2024 | 03:08 pm ]
[perfect_dark_net-port]$ `export ROMID=pal-final`

[ root | 28-08-2024 | 03:08 pm ]
[perfect_dark_net-port]$ `make -f Makefile.port TARGET_PLATFORM=i686-linux`

> Host platform: x86_64-linux
> Target platform: i686-linux
> tools/assetmgr/mkanims --headers-only
> make: tools/assetmgr/mkanims: Permiso denegado
> make: *** [Makefile.port:286: src/generated/pal-final/animations.h] Error 127
> 

The weird is i try 
[ root | 28-08-2024 | 03:09 pm ]
[perfect_dark_net-port]$ `chmod 777 -R ./tools/assetmgr`

[ root | 28-08-2024 | 03:11 pm ]
[perfect_dark_net-port]$ `./tools/assetmgr/mkanims`

> bash: ./tools/assetmgr/mkanims: Permiso denegado

Note all binaries executable inside the folder ./tools/assetmgr all says « Denied Permission » i can't compile by this reason.

how i fix it ? 
broking selinux ?

**Comment by fgsfdsfgs** [comment]
Try not compiling as root.

**Comment by inukaze** [comment]
> Try not compiling as root.

That is the first thing i try, after i try again, after i try with the root user, thinking was possible some error with privilegies, and the finish try, was root again, and ever i give the same result because of that is i make this post here. 

with common user, and with root user, the result is exactly the same, and becuase of that i post this and becuase of this at the end i ask the follow :

> how i fix it ?
> broking selinux ?

**Comment by fgsfdsfgs** [comment]
Sorry, I got no clue. Something on your side. Maybe move it out of the `/media/*` mount and somewhere into your home directory?

**Comment by inukaze** [comment]
Ok trying with common user inside HOME : 

[ inukaze  | 29-08-2024 | 09:34 pm ]
[~]$ `mkdir "$HOME/src"`

[ inukaze  | 29-08-2024 | 09:34 pm ]
[~]$ `cd "$HOME/src"`

[ inukaze  | 29-08-2024 | 09:34 pm ]
[src]$ `git clone https://github.com/fgsfdsfgs/perfect_dark perfect_dark_net-port`
Clonando en 'perfect_dark_net-port'...
remote: Enumerating objects: 93070, done.
remote: Counting objects: 100% (1013/1013), done.
remote: Compressing objects: 100% (324/324), done.
remote: Total 93070 (delta 711), reused 946 (delta 675), pack-reused 92057 (from 1)
Recibiendo objetos: 100% (93070/93070), 109.47 MiB | 139.00 KiB/s, listo.
Resolviendo deltas: 100% (77144/77144), listo.
Actualizando archivos: 100% (2271/2271), listo.

[ inukaze  | 29-08-2024 | 10:53 pm ]
`cd perfect_dark_net-port`

[ inukaze  | 29-08-2024 | 10:53 pm ]
[perfect_dark_net-port]$ `git checkout port-net`
rama 'port-net' configurada para rastrear 'origin/port-net'.
Cambiado a nueva rama 'port-net'

[ inukaze  | 29-08-2024 | 10:53 pm ]
[perfect_dark_net-port]$ `git submodule update --init --remote --recursive`

> Submódulo 'tools/recomp' (https://github.com/Emill/ido-static-recomp.git) registrado para ruta 'tools/recomp'
> Clonando en '/home/inukaze/src/perfect_dark_net-port/tools/recomp'...
> Ruta de submódulo 'tools/recomp': check out realizado a '421e546956ceae984927e609b083195e9e81659e'

[ inukaze  | 29-08-2024 | 10:55 pm ]
[perfect_dark_net-port]$ `export ROMID=pal-final`

[ inukaze  | 29-08-2024 | 10:55 pm ]
`make -f Makefile.port TARGET_PLATFORM=i686-linux`

a lot of output right now is compiling 
finish after 4 mins

[ inukaze  | 29-08-2024 | 10:59 pm ]
[perfect_dark_net-port]$ `cd build/pal-final-port/`

[ inukaze  | 29-08-2024 | 11:00 pm ]
[pal-final-port]$ `ls`

> pd.pal.exe  port/  src/

Excelent is solved.

i just got another dunno, you know is exist something similar project like this but for GoldenEye 007 N64 version ?

**Comment by fgsfdsfgs** [comment]
There isn't a PC port for GoldenEye yet, no. There probably will be eventually after the decompilation project is finished.

**Comment by inukaze** [comment]
> There isn't a PC port for GoldenEye yet, no. There probably will be eventually after the decompilation project is finished.

Awesome, my final dunno is some clue when the game says :

> Could not open SDL window: Couldn't find matching GLX visual

Because of that i reinstall the nvidia driver 390.157 ( i use MSI Nvidia GeForce GT 620 ) but i got the same message ? 

i need recompile SDL and/or SDL2 ?

i had try this : 

`glxinfo | grep 0x022`

> 0x022 24 dc  0  24  0 r  y .   8  8  8  0 .  s  4 24  8 16 16 16 16  0 0 None

`export SDL_VIDEO_X11_VISUALID=0x022`

`./netport.pal-final.lignux32`

> version: port-net ae0ba57c2 (i686-linux)
> startup date: 30 Aug 2024 20:41:34
> base dir: ./data
> save dir: /home/inukaze/.local/share/perfectdark
> WARNING: GL: could not create GL3.0 context: Could not create GL context
> WARNING: GL: could not create GL3.2 context: Could not create GL context
> WARNING: GL: could not create GL2.1 context: Could not create GL context
> ERROR: FATAL: Could not create an OpenGL context of any supported version.
> SDL error: Could not create GL context
> 

Happend the same with the old versions i had compile, i supose can be and error on drivers or sdl.

**Comment by inukaze** [comment]
SOLVED i just reinstall again the nvidia drivers from .run file and again accepting 32 Bits Libraries compatibility and now is working

![PerfectDark](https://github.com/user-attachments/assets/5af2bde9-ce7e-460f-86a0-c632783980af)

The unique thing take me by surprise was
ERROR: could not save EEPROM to `/home/inukaze/.local/share/perfectdark/eeprom.bin`: No such file or directory

because that file already exist from the same path i am running the binary executable
