### ISSUE TITLE
[Feature Request] Use detailed models as world models

### ISSUE THREAD

**Issue by LuluZulu123** [fgsfdsfgs/perfect_dark#503]
I don't know if this is doable or even desirable, but with the processing power and memory available of current systems, would it be possible to replace the world model of guns with their detailed counterpart (as used in the pause menu or shooting range for example)?

Obviously this would not be the default but rather something you opt-in through some "[...] > advanced > [...]" menu options.

**Comment by fgsfdsfgs** [comment]
This would be a good idea for a mod. Without making new world models based on the view models it's not trivial to do though. They have hitboxes and all kinds of other stuff attached to them that you would have to fix.

**Comment by LonelySpaceDetective** [comment]
Are the view models even optimized to be seen from every angle? A lot of FPSes would not draw anything on the gun you didn't see from the animations, like the other side of the gun.

**Comment by fgsfdsfgs** [comment]
From what I can tell, the inventory screen actually uses view models for the rotating gun model, so I guess they are.

**Comment by LuluZulu123** [comment]
@LonelySpaceDetective in the background of the weapons selection of the pause menu they rotate, so yes. It is possible that they made three different models (another one for in-hand) but i find that unlikely.

Edit: nevermind then. 2 seconds late to reply
