### ISSUE TITLE
[Feature Request] Non-disappearing corpses in singleplayer

### ISSUE THREAD

**Issue by AJ292** [fgsfdsfgs/perfect_dark#509]
I'm not entirely sure how this is coded in the original game but it would be great if all corpses in singleplayer would stay in place in the game world instead of having some of them vanish. The original game seems to cull corpses in a fairly random manner (at least, with no pattern I've been able to discern) with some either staying put for the entire duration of the stage and others vanishing almost immediately.

Having some corpses (boy, this is a morbid request) stay in the game world was a feature of the original game, particularly in comparison to GoldenEye's behaviour of fading all of them away after death. No doubt, the culling of some of them in Perfect Dark was just down to resource management on the N64, but since that's not really a concern anymore, it would be interesting to see none of them disappear (which was potentially Rare's original intent).

**Comment by fgsfdsfgs** [comment]
This has been requested before in #217, and is possible, but would require some work. Check that issue for an explanation of why this is not trivial.
