### ISSUE TITLE
Environment mapped surfaces look incorrect

### ISSUE THREAD

**Issue by s-ilent** [fgsfdsfgs/perfect_dark#51]
It looks like the texture coordinates generation (`G_TEXTURE_GEN`) has an issue, or the normals are being read incorrectly... The opening logos demonstrate it pretty well. 
| Emulation | Current |
| - | - |
| ![simple64-gui_2023_08_20_02_44_22_791](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/f9e5daa7-e589-4478-8fbd-1c89b25e32a2) | ![pd_2023_08_20_02_47_01_293](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/02667449-c2ee-46b1-9a41-794ca1493e53)
| ![simple64-gui_2023_08_20_02_44_18_604](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/6b7734dd-8682-4485-a310-695dd74a167a) | ![pd_2023_08_20_02_45_56_326](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/1831aa8b-0bba-41fa-80b2-a910f26812e8) | 
| ![simple64-gui_2023_08_20_02_44_33_035](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/f9bf1ad2-3061-4e59-9715-ec3cf2f4c1e0) | ![pd_2023_08_20_02_46_10_110](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/ab490a9c-2bc6-436e-84a5-ff4062be3e65) |

**Comment by ghost** [comment]
<img width="640" alt="envmap error" src="https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/0e55a709-301e-4d66-aaf8-245efa87665d">

It looks like texture scale isn't being taken into consideration by the environment map effect. It's very noticeable on windows, and the desk at the start of Mr. Blonde's Revenge.

**Comment by Graslu** [comment]
Doors in Carrington Institute, Air Force One, all glass textures, Falcon 2... This applies to all models using the effect.

**Comment by fgsfdsfgs** [comment]
This should now be at least partially fixed. Was due to a dumb copypaste mistake in the renderer.

**Comment by ghost** [comment]
The env map effect looks to be closer to emulation now. Can't tell if it's a match since of small differences in angles between the screenshots.
![envmaps](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/f803233b-0a7d-4d58-9930-a6f7d4b99c7a)

**Comment by s-ilent** [comment]
Yep, the brokenness is definitely fixed! And reflections seem to match up pretty closely now.

| Emulation | Port |
| - | - |
| ![pd_2023_08_22_12_25_29_583](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/ad479f76-778e-4b9f-b821-ee24d5b498b9) | ![simple64-gui_2023_08_22_12_25_29_594](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/00c3c1e8-c26b-46fa-ace3-fa63a71dbba7) |
| ![pd_2023_08_22_12_38_04_513](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/774a64b7-53d0-4c49-a13a-4c935d45821f) | ![simple64-gui_2023_08_22_12_38_04_507](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/189cf591-e9ba-41cb-8a6a-f153e608325a) |

The difference in the opening logos appearance is pretty strange, I wonder if it has anything to do with the altered FOV calculation? In fact, this comparison is a bit misleading because the emulation screenshots have a black border around them. However, in testing, the difference in the shading is visible regardless of whether the port is in widescreen or not. 

| Emulation | Port |
| - | - |
| ![simple64-gui_2023_08_20_02_44_22_791](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/f9e5daa7-e589-4478-8fbd-1c89b25e32a2) | ![pd_2023_08_22_12_07_13_448](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/f01676f4-1538-4051-a83c-24b14b3b5474) |
| ![simple64-gui_2023_08_20_02_44_18_604](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/6b7734dd-8682-4485-a310-695dd74a167a) |  ![pd_2023_08_22_12_05_57_930](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/e09f1dae-a7ab-4464-8c5b-ae45131d5cc1) |
| ![simple64-gui_2023_08_20_02_44_33_035](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/f9bf1ad2-3061-4e59-9715-ec3cf2f4c1e0) | ![pd_2023_08_22_12_06_12_097](https://github.com/fgsfdsfgs/perfect_dark/assets/16026653/2579164d-6536-4264-bd7c-36863c69a620) | 

Maybe there's a bug to fix there, but the main problem is solved so feel free to close the issue.

**Comment by fgsfdsfgs** [comment]
I guess I'll close this for now, it looks close enough at least.

**Comment by Calinou** [comment]
@s-ilent It appears you have your top screenshots mixed up, as the "emulation" ones use bilinear texture filtering while the "port" ones use tri-point filtering. However, this port only supports bilinear filtering right now.

(The emulated screenshots also have that slight letterboxing from the NTSC resolution.)

**Comment by fgsfdsfgs** [comment]
It does actually support tri-point, though it incorrectly turns it on for all textures. You need to set `TextureFilter=2` in the config. But I suspect the difference in filtering might explain some of the differences in envmap rendering.
