### ISSUE TITLE
Suggestion: make cheese collectable, use to unlock new cheats

### ISSUE THREAD

**Issue by amazingalek** [fgsfdsfgs/perfect_dark#510]
This is probably a bad idea, just gauging interest :)

As you may know, all or most levels have a hidden piece of cheese. They don't do anything, and according to [an interview](https://www.svg.com/836712/heres-why-you-can-find-a-piece-of-cheese-in-every-level-of-perfect-dark/), they were never intended to either.

However, since they're already there, maybe we could use them for something? It could add another fun dimension to this already amazing game. 
The coolest use for them I can think of is unlocking new cheats, such as [allowing Slayer missiles to go out of bounds](https://github.com/fgsfdsfgs/perfect_dark/pull/445).
If that's not desirable, just having cheese progression displayed somewhere could be cool too.

As for how to collect the cheeses, I suggest shooting at them with bullets. Some are hidden in places where you can't walk, and we'd probably want to avoid accidently collecting them with explosions.

**Comment by amazingalek** [comment]
Not sure what to do when we want to add a cheat but have run out of pieces of cheese, though.
There's a fine line between respecting the original game and adding new features. Would adding new cheeses cross that line? Unsure :-)

**Comment by LonelySpaceDetective** [comment]
Speaking as a player, I feel this is a bit beyond the scope of just a PC port, and the issue with shooting the cheese is you can't really do that with some of them like the one in Deep Sea, unless you'd count the Farsight.

You could probably retool the idea to "look at/observe the cheese" rather than "shoot the cheese", but this is still much more of an idea for a mod than anything else.

**Comment by fgsfdsfgs** [comment]
Yeah, this is really more of a mod idea. Besides, I don't know if cheese is an actual "object" that can be interacted with in any way or just static level geometry.
