### ISSUE TITLE
Bots appear to be where they aren't in multiplayer

### ISSUE THREAD

**Issue by ryantho66** [fgsfdsfgs/perfect_dark#511]
Played with a buddy and had him stream his screen. He would see enemies that aren't there (and he can't damage), and wouldn't see enemies that are (and are killing him).

**Comment by fgsfdsfgs** [comment]
Bots are not supported in networked games yet.

**Comment by ryantho66** [comment]
): Kills half the fun of playing. Hope you can get it soon!
