### ISSUE TITLE
add other levels from goldeneye

### ISSUE THREAD

**Issue by FrostKnight** [fgsfdsfgs/perfect_dark#516]
library, full facility including back zone, surface 1 + bunker 1, surface 2 + bunker 2

Just a few ideas of interest. 

Mostly the first two have my interest but the others also would be interesting.

Especially given you can have 8 bots. lol

**Comment by LonelySpaceDetective** [comment]
Beyond the scope of just a PC port, though good idea for a mod.

**Comment by Atari-Dude** [comment]
If you use the GEPD Editor to make custom mp level setups using the GoldenEye X mod as a basis, this sounds like it would be doable. But of course, that's modding the game, and mods aren't bundled in with this PC port

However there is already an effort underway to make a definitive multiplayer PD mod of sorts, merging the content of previous mods including Perfect Dark Plus, All Solos in Multi, and GoldenEye X. So you get Skedar and Dr. Caroll in Combat Simulator, as well as Wreck's updated Stack & Caves from PD+... as well as all of PD's mission levels... as well as all of GoldenEye X's multiplayer arenas.

[Library is included via GE:X's maps.](https://youtu.be/XCSoCon3MGg?t=2268)

**Comment by FrostKnight** [comment]
> Beyond the scope of just a PC port, though good idea for a mod.

Would you know of anyone who is doing such a thing? I have interest in mentioning to said person.

@Atari-Dyude I am aware of Perfect Dark Plus. I just wish he had added Library instead of stack lol.

**Comment by 8sm32K4D1K5f3E** [comment]
Just checking, are you aware of this fork? 

https://github.com/jonaeru/perfect_dark
https://github.com/jonaeru/perfect_dark/wiki/How-to-Play-Mods

Issues like this would make more sense mentioning that I'd think.

**Comment by FrostKnight** [comment]
> Just checking, are you aware of this fork?
> 
> https://github.com/jonaeru/perfect_dark https://github.com/jonaeru/perfect_dark/wiki/How-to-Play-Mods
> 
> Issues like this would make more sense mentioning that I'd think.

Don't know how to use that repo.

Also, no issues tracker or discussion

**Comment by jonaeru** [comment]
@FrostKnight 
Can I join the N64 Vault discord server? https://discord.gg/ms5pJFNGZ9
You can also contact Wreck, author of Perfect Dark Plus, GoldenEye X.

**Comment by fgsfdsfgs** [comment]
This is indeed mod territory.
