### ISSUE TITLE
Some mirrored textures do not mirror.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#52]
This is easily noticeable with decals like metal impact holes.
<img width="640" alt="mirror issue" src="https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/78100fda-220a-4c9f-bb57-67b49ca10950">

**Comment by fgsfdsfgs** [comment]
I looked at this some more, and this isn't mirror related. The full bullet hole texture actually has both halves in it:
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/2997482/767f115c-63e9-4f91-95e5-3b474273159c)
This is related to the renderer dealing with texture LODs incorrectly. I'll close this, there is an issue for broken textures already.
