### ISSUE TITLE
Windows build no longer runs on my machine with latest release; error dialog claims .dll is missing

### ISSUE THREAD

**Issue by LonelySpaceDetective** [fgsfdsfgs/perfect_dark#526]
"The code execution cannot proceed because libstdc++-6.dll was not found. Reinstalling the program may fix this problem."

From very cursory googling, it sounds like the `-static-libgcc` and `-static-libstdc++` builder options may resolve this.
While I'm here, just about completely unrelated but too minor to really be worth filing a separate issue: The application icon seems to have been lost in the 64-bit transition; neither the x86 or x64 binaries have icons anymore.

**Comment by LonelySpaceDetective** [comment]
Corrected the title as I just checked the 32-bit build, and found out it isn't working either.

**Comment by fgsfdsfgs** [comment]
This is not a problem with the 64-bit transition, but with the CMake transition. I just forgot both of these things. Fixed.
