### ISSUE TITLE
Momentum displacement leads to softlock in The Duel

### ISSUE THREAD

**Issue by ZenithMDC** [fgsfdsfgs/perfect_dark#533]
I just discovered another bug. If you play at a higher difficulty, after you kill an opponent, your momentum will be kept when you are placed in autorun mode and can cause Joanna to miss the target destination, leading to the same softlock as in #532. This time, I had no trouble capturing it with OBS. 

https://github.com/user-attachments/assets/710f6739-48e1-4155-9e77-4120f5c25b97

Tested in [d747588](https://github.com/fgsfdsfgs/perfect_dark/commit/d7475883235c65b87e3a8bd69b58d69b79e517c0). x86_64 build.

**Comment by fgsfdsfgs** [comment]
Would this be an N64 bug then? Or maybe related to the PC controls? Wonder why it hasn't been reported before.

**Comment by ZenithMDC** [comment]
Just tested the N64 version. Joanna seems to only walk to her destination there, but she runs to it in the PC port. The displacement is present in the N64 version, too, but because she walks, it's a much smaller displacement and it doesn't end up causing the bug. I wonder what's causing her to run in the PC port, then?

**Comment by fgsfdsfgs** [comment]
Might be related to extended controls being enabled. I don't remember if they force maximum speed anywhere.
