### ISSUE TITLE
Can't press R-shoulder and left C-button combination on third party controller with macos

### ISSUE THREAD

**Issue by creamcast** [fgsfdsfgs/perfect_dark#539]
on MacOS Sequoia I'm using a generic third party n64 controller (SDL2 INFO: Nintendo Switch Pro Controller 0: SWITCH CO.,LTD. Pro Controller, USB_0f0d_00c1_0x12af09fb0 (guid 0300cb1c0d0f0000c100000072056800) with latest SDL2 (2.30.9) but trying to do a lean pressing the Left C-button and R shoulder doesn't seem to register . Downgrading SDL2 to 2.28.0 would remedy it. Not really sure if this bug in macos arm, sdl2 or with the application itself . I tested on a windows 11 pc and it doesn't have this issue.

**Comment by fgsfdsfgs** [comment]
The built-in controller bindings might've changed in SDL2. You can try to download [this file](https://raw.githubusercontent.com/mdqinc/SDL_GameControllerDB/refs/heads/master/gamecontrollerdb.txt) and put it either into the same directory as the game executable (`pd.x86_64` or `pd.arm64`) or into `/Users/USERNAME/Library/Application Support/perfectdark/`.

If this doesn't help, you can try to downgrade SDL2 to 2.28 locally:
```
cd path/to/game
rm -rf SDL2.framework
wget http://libsdl.org/release/SDL2-2.28.0.dmg -O SDL2.dmg
hdiutil mount SDL2.dmg
cp -vr /Volumes/SDL2/SDL2.framework .
```
though I'm not sure if it will allow this or complain about the version.
