### ISSUE TITLE
Crash after opening sequence

### ISSUE THREAD

**Issue by Phnod** [fgsfdsfgs/perfect_dark#54]
Getting a crash after loading into the Institute menu that I've narrowed down to having something to do with the radial menu section bondmove.c Line 1417 `g_Vars.currentplayer->amdowntime = 0;` in the radial menu in commit ffae454. Haven't been able to figure out how to actually debug the project so I'm not sure why this causes a crash, but when I comment it out, it stops crashing for me. Does anyone else get this crash?

Link to line 
https://github.com/fgsfdsfgs/perfect_dark/blob/8c6d6df5fc396bef8ca393397296a9562b70683e/src/game/bondmove.c#L1417C45-L1417C45

**Comment by cylonicboom** [comment]
I'll investigate. Are you on windows or linux? mouse/keyboard or controller?

**Comment by cylonicboom** [comment]
I can't reproduce this. Can you please share your repro steps?

**Comment by cylonicboom** [comment]
@Phnod , please try the build in the PR. It does a check before resetting the timer.

**Comment by Phnod** [comment]
I'll try again in a completely new directory, I had previously used mouse/keyboard on windows compiled on my machine, with and without prior save or ini file, and with or without the alternate menu option, it'd crash just after the startup sequence changes scenes. (If the alternate menu startup option is selected in the game options, it'll crash after that)

Let me know if there's any other details I could share. 🤔

![2023 08 20 T(16 03 05)Idle_MWomi0j32n](https://github.com/fgsfdsfgs/perfect_dark/assets/16583255/3e6d5716-9eb2-4dab-9e1f-6540528aa075)

**Comment by fgsfdsfgs** [comment]
When you pull some bigger changes you have to do a clean build. Run `make -f Makefile.port clean`, then recompile as normal.

**Comment by cylonicboom** [comment]
@Phnod does the issue reproduce w/ one of the binaries produced by the CI system?

**Comment by Phnod** [comment]
It's not crashing anymore I can't replicate it anymore, not even from a result of #59 but from who knows what. It's still crashing in my own repo, but not in [fgsfdsfgs](https://github.com/fgsfdsfgs) or [NeonNyan](https://github.com/NeonNyan)'s. I'll try the clean option, I had tried `make -B -f Makefile.port` thinking it'd clean but I'm guessing not? Will report back in a moment and close

**Comment by Phnod** [comment]
Whoops accidentally hit the wrong button, will close again once I've tested

**Comment by Phnod** [comment]
The clean fixed it, thank you!
