### ISSUE TITLE
[Feature Request] Weapon/Item Hotkeys

### ISSUE THREAD

**Issue by UncookedMoa** [fgsfdsfgs/perfect_dark#540]
If possible, I think it would be a good idea to add weapon/item hotkeys as possible binds to use for the game, which would help make the game feel more at home on PC. Basically, players should be able to press key (like a number key, or any other key really) to quickly swap to the item they want to use. Since the game has so many weapons that wouldn't fit the number line from 1-9, take a page from Half-Life's playbook and put the items into categories, so maybe Pistols on 1, automatics on 2, objective items on another number, etc.

And if the player want to rebind it, it should be possible to put them outside of the number line.

**Comment by fgsfdsfgs** [comment]
There is already a request for this, see #365. If something like this is added it would definitely be an option and not enforced by default.
