### ISSUE TITLE
Any idea what this strange purple smoke is?

### ISSUE THREAD

**Issue by ZenithMDC** [fgsfdsfgs/perfect_dark#541]
https://github.com/user-attachments/assets/948aa7bf-fa3c-4796-a923-2bf3d7bf8722

I wish I knew more so I could provide better info, but it seems to appear sometimes if I incapacitate a bunch of guards by disarming them. I've seen it appear once before in Chicago and just now in Carrington Villa. The 1st time I saw it, it was encircling the exploded cab. This time, it's just floating about in the air above the streets.

Using https://github.com/fgsfdsfgs/perfect_dark/commit/683d083fab5a1ec1f88e5de371cce113c5ed200f. x86_64 build. I reproduced it in an earlier commit, too, but don't remember the exact one.

**Comment by fgsfdsfgs** [comment]
Do you remember if it was before the 64-bit fixes or after?

**Comment by ZenithMDC** [comment]
It was a commit after the 64-bit fixes. I don't recall seeing it prior to them, but I also never ran around the level incapacitating all the guards either, which seems to be a prerequisite to producing this smoke. So, I can't say for certain whether this is 64-bit-fix exclusive or not.

**Comment by rafccq** [comment]
@ZenithMDC did you have any cheat activated?

**Comment by ZenithMDC** [comment]
No cheats enabled. I just ran around Chicago again, knocking out all the guards on the streets and backalleys. It seems like there's one guard in particular, who is one of the guards that is distracted by the diversion, where I actually see that purple smoke fly out of him as he's knocked out and then it shoots up into the air. After a while, it falls down and starts hovering around the crash site. Very bizarre.

Unfortunately, it doesn't happen every time I go through the level, so I'm still lacking an understanding of what exactly is triggering it.

Okay, it has everything to do with those four distracted guards, since I just tested shooting the rest of the guards. I just went through again and disarmed them all in a row, but leaving them conscious. The guard that was closest to the G5 parking garage had that smoke fly out of him as I disarmed him.

**Comment by rafccq** [comment]
Just by going there and disarming them, or did you complete the diversion objective first? Also, which difficulty?

**Comment by ZenithMDC** [comment]
I'm playing on Agent difficulty and always complete the diversion objective. I actually never tested doing it without completing the diversion 1st.

*Just tested and it seems to only occur if the diversion has occurred. I also wait for their scripted dialogue to occur and for them all to get into position. Then, I just run up to them all and disarm them. This latest run, I actually got two purple smoke clouds to form.

**Comment by fgsfdsfgs** [comment]
I wonder if that guard is supposed to drop something specific but somehow it gets changed into `PROPTYPE_SMOKE`.

**Comment by ZenithMDC** [comment]
After spawning the purple smoke and running around Chicago for ~10 minutes or so, the game will crash. It doesn't happen every time, but it's highly likely to crash after around that duration. Here is the log:

```
Crash!

EXCEPTION: 0xc0000094
PC: 00007ff6c02b7d20
MODULE: [00007ff6c0160000]
MAIN MODULE: [00007ff6c0160000]

BACKTRACE:
#00: 00007ff6c02b7d20: [00007ff6c0160000]+0000000000157d20
#01: 00007ff6c029e457: [00007ff6c0160000]+000000000013e457
#02: 00007ff6c02191ae: [00007ff6c0160000]+00000000000b91ae
#03: 00007ff6c02ec5e7: [00007ff6c0160000]+000000000018c5e7
#04: 00007ff6c02ecb1c: [00007ff6c0160000]+000000000018cb1c
#05: 00007ff6c02ecd62: [00007ff6c0160000]+000000000018cd62
#06: 00007ff6c02e4db5: [00007ff6c0160000]+0000000000184db5
#07: 00007ff6c016140a: [00007ff6c0160000]+000000000000140a
#08: 00007ff6c01614d6: [00007ff6c0160000]+00000000000014d6
#09: 00007ffb22947374: BaseThreadInitThunk+20
#10: 00007ffb2395cc91: RtlUserThreadStart+33
```

I've traced it to line 491 of `smoke.c`:
```c
if (smoke->age % g_SmokeTypes[smoke->type].spreadspeed == 1) {
```

It's a division by zero exception, which would imply that `g_SmokeTypes[smoke->type].spreadspeed` somehow becomes 0.

Tested using [9c4aded](https://github.com/fgsfdsfgs/perfect_dark/commit/9c4aded403976a90ca9641fb5fb989dd7c80ad7a). x86_64 build.

**Comment by fgsfdsfgs** [comment]
So either some garbage overwrites part of the `g_Smokes` array or some garbage overwrites part of the `g_SmokeTypes` array. Very likely the former.

**Comment by Mikan1520** [comment]
Can confirm I'm seeing this smoke on dataDyne Defection, after going down the elevator and killing the guards (before I entered the security room to place the ECM mine). x86_64 build
![Untitled](https://github.com/user-attachments/assets/8a3e234e-9230-48ec-951f-5b8cce8e7ed3)

**Comment by fgsfdsfgs** [comment]
This should be fixed now. Explanation by Ryan Dwyer:

> I've figured out the smoke bug. It's an N64 bug. When you disarm a guard, his gun is detached from the parent chr and is saved in `chr->gunprop`. When you pick up his gun the prop is freed but the pointer remains. The prop slot is then reused for smoke. When the chr's AI checks to see if the gun is retrievable, it reads the `gunprop` pointer, accesses the weapon union pointer (which is actually a struct smoke in this case) and sets a bitflag on it. The flag is written into offset 8. On 32-bit architectures this is the X position of a billboard texture and not noticeable. On 64-bit architectures it's the `type` field.
