### ISSUE TITLE
Skedar refuses to attack Joanna in Carrington Institute: Defense

### ISSUE THREAD

**Issue by ZenithMDC** [fgsfdsfgs/perfect_dark#542]
https://github.com/user-attachments/assets/7bcf0836-05e7-4339-aa85-b8007f8a75bb

This bug only occurs on the x86_64 build. Tested 2a5c3a351 and 9c4aded40. Behavior was identical between the two commits, if using the i686 build.

**Comment by fgsfdsfgs** [comment]
Well, I can't actually repro this on the latest commit. As long as you run out of the starting point quick enough the Skedar will shoot at you. If you take too long it will be distracted by whoever's firing from the back of the room. This happens on my end in both x86_64 and i686 builds. Is there anything specific you need to do to make this happen?

**Comment by ZenithMDC** [comment]
Hmm... That's strange. I just tested again on 67675d898 `x86_64`. No matter how fast I round the corner, the Skedar doesn't turn to shoot at Joanna and will just follow her menacingly. On 67675d898 `i686`, the Skedar will turn and shoot at her, even if I wait about a second or two.  Any longer than that and the Skedar will be distracted by the Carrington Institute guard. 2a5c3a351 (what I refer to as `port-pre-64`) has the same behavior as 67675d898 `i686`.

**Comment by fgsfdsfgs** [comment]
Might be fixed now. Explanation from Ryan Dwyer:
>  In aiIfPresetsTargetIsNotMyTarget, initialise mypresetchrstarget to -1.
The bugged version prints FOUND 1, skips FOUND 2 and prints FOUND 3 while the good version does all three. The problem command is if_chrpresets_target_is_different on line 3462 of gailists.c. The skedar has chrpreset1 set to -1, so there's a use of an uninitialised variable. This can make the ailist not follow the label when it should.
