### ISSUE TITLE
Text in multiplayer flickers before it appears

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#55]
Text will appear as either fully green, or red squares for a brief moment before it correctly fades in.

https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/fd756203-ebb5-4f7b-bcbc-acad4a60ce68

EDIT: I have not seen this happen to me in singleplayer yet, so I have edited the issue to specify.

**Comment by megatog615** [comment]
Confirmed happens for me too.

**Comment by Darken93** [comment]
This also happens in single player, just not as noticeable as it is either the same green color as the text or the same color as the subtitles if you have them enabled. CI Training behaves the same as combat simulator

**Comment by StenApp** [comment]
I also see red unreadable texts before and sometimes after a message like "Weapon x picked up"

**Comment by fgsfdsfgs** [comment]
Should be fixed now.

**Comment by StenApp** [comment]
Fixed for me, thank you!
