### ISSUE TITLE
Can't seem to build correctly

### ISSUE THREAD

**Issue by zhaDeth** [fgsfdsfgs/perfect_dark#554]
I followed the instructions on how to build and managed to build a pd.x86_64.exe but when I run it I get an error: "The application was unable to start correctly (0x0000007b)."

**Comment by fgsfdsfgs** [comment]
You have built it correctly, but the DLL files required to run the game are not in the same folder as the executable. Either get them from one of the x86_64-windows builds in releases, or run the game from within the MINGW64 prompt, or copy them yourself by doing this:
```
cp /mingw64/bin/{SDL2.dll,zlib1.dll,libwinpthread-1.dll,libgcc_s_seh-1.dll} build/
```

**Comment by zhaDeth** [comment]
That worked thanks
