### ISSUE TITLE
CTD loading Crash Site

### ISSUE THREAD

**Issue by 8sm32K4D1K5f3E** [fgsfdsfgs/perfect_dark#56]
Unsure when this first began appearing, as video shows, some game sessions Crash Site will be working and can be loaded perfectly fine, either from abort reload or from institute. Other game sessions it will crash any time it's loaded.
[2023-08-20 15-00-52.webm](https://github.com/fgsfdsfgs/perfect_dark/assets/97014490/8a798f17-c4d7-45de-aba5-3096b59071a7)
Attached video is;
-Abort reload
-Abort reload
-Carrington load
-Reboot game
-Carrington crash
-Reboot game
-Carrington crash

Happens across multiple savefiles, but haven't seen it occur with any other level.

**Comment by fgsfdsfgs** [comment]
This should be fixed in the latest commit.

**Comment by 8sm32K4D1K5f3E** [comment]
Did numerous abort reloads, and numerous reboot fresh loads, didn't crash once so should be fixed.
