### ISSUE TITLE
game cant be finished

### ISSUE THREAD

**Issue by SusDTSteve** [fgsfdsfgs/perfect_dark#563]
at the end of perfect dark where the perfect dark logo scrolls across the screen. at that point it doesent matter how many times or how hard i click buttons, i remain stuck on that screen. playing on keyboard

**Comment by SusDTSteve** [comment]
https://github.com/user-attachments/assets/f6322d2a-c753-44ad-bb01-9064f48ce566

**Comment by fgsfdsfgs** [comment]
That might be how the original game works as well, requiring you to reset your N64? Not sure.

**Comment by cylonicboom** [comment]
It is. The XBLA version adds a 'press a' hud widget to bail out back to the CI hub.

**Comment by fgsfdsfgs** [comment]
I guess that would be a good feature to have.

**Comment by SusDTSteve** [comment]
i reset the game and it doesent save progress

**Comment by fgsfdsfgs** [comment]
If you restart it and you get the alternate intro (looks the same as the ending), that means it did save.

**Comment by LonelySpaceDetective** [comment]
At least Mr. Blonde's Revenge should be unlocked as well among the bonus missions, as far as I know.

Anyway, the game just looping after the credits and expecting you to turn the game off is normal N64 behavior, though not very good UX in general. Doing something like XBLA to let you quit back to CI would be nice.

**Comment by fgsfdsfgs** [comment]
If you want, you can try again now (after the autobuild is done) and report back if it's still broken or something.
