### ISSUE TITLE
64-Bit Build Changes Cause ARM 32-Bit Builds to Crash After Intro Logo on Raspberry Pi 4 Bullseye

### ISSUE THREAD

**Issue by fac3l3ss79** [fgsfdsfgs/perfect_dark#567]
Earlier builds, before changes to support 64-bit compilation, worked on ARM32. However, after those changes, recent ARM32 builds crash at the end of the intro logo scene on Raspberry Pi OS Bullseye. In contrast, 64-bit builds run without crashes on AArch64 in both Bullseye and Bookworm.

**Comment by fgsfdsfgs** [comment]
Does it crash when you set `SkipIntro=1` in `pd.ini` or run it with `--skip-intro` on the command line?
EDIT: It's a certified ARM moment. It dies because of an unaligned access because I guess some of the portal vertices are not aligned to 4 after conversion?

**Comment by fgsfdsfgs** [comment]
Should be fixed in 0443c70.

**Comment by fac3l3ss79** [comment]
Thank you! I can confirm that it doesn't crash anymore with the 32 bit kernel on a raspberry pi 4.
It does crash at startup compiled with clang-11 in a 64 bit kernel with 32 bit userspace, which results in a much smaller file, with optimizations I guess.
But if compiled with gcc-10, all is fine!
Happy new year!
