### ISSUE TITLE
Crash in Air Force One

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#58]
How to reproduce: Play through Air Force One until you reach the cutscene, the game will then crash

**Comment by fgsfdsfgs** [comment]
You mean the first cutscene after you find the president?

**Comment by ghost** [comment]
Correct. On my end the game draws a black screen and then crashes.

**Comment by fgsfdsfgs** [comment]
Either this has been fixed in the latest commit or I can't reproduce it. If you're building the game locally, do a clean build by running `make -f Makefile.port clean` first.

**Comment by ghost** [comment]
It no longer crashes as of https://github.com/fgsfdsfgs/perfect_dark/actions/runs/5919429665
Seems like the empty room crash may have been the cause.
