### ISSUE TITLE
Stairs on Villa are broken

### ISSUE THREAD

**Issue by megatog615** [fgsfdsfgs/perfect_dark#6]
Some of the stairs on Villa do not allow the player to descend or ascend, notably the interior stairs. Exterior stairs seem to work fine in my testing.

**Comment by fgsfdsfgs** [comment]
There is a bug where the collision breaks when you push a pushable object, like a box or a desk. Shooting at them is fine, but as soon as you touch it, stuff like this starts happening. It might be because of that.

**Comment by fgsfdsfgs** [comment]
The bug I mentioned above should be fixed after the latest commit, so maybe this is fixed as well.

**Comment by 8sm32K4D1K5f3E** [comment]
From a few hours of testing I was not able to get the broken stairs (not being able to go down inside the villa) or even the broken doors (doors getting stuck in a position) so this bug seems to be fixed.
