### ISSUE TITLE
dD-Investigation monitor screens fall when destroyed

### ISSUE THREAD

**Issue by LanHikariDS** [fgsfdsfgs/perfect_dark#67]
https://github.com/fgsfdsfgs/perfect_dark/assets/42668580/021132bc-0ec7-4eb8-9af9-543b4a2bcb5b

**Comment by ghost** [comment]
This also happens with the turrets outside Area 51 Infiltration, it's likely a global issue with destroyed props.

**Comment by RyanDwyer** [comment]
This also happens in the original game, and it's intentional. The code responsible for it is here: https://github.com/fgsfdsfgs/perfect_dark/blob/58e13db61350c9f8d80a6516379bed4cb9ef47e3/src/game/propobj.c#L13944

**Comment by fgsfdsfgs** [comment]
So this isn't an issue then?

**Comment by LanHikariDS** [comment]
I was gonna double-check the original game on hardware, I'd only tested that it doesn't do that in the XBLA port

**Comment by LanHikariDS** [comment]
Yeah, this is N64 behavior
