### ISSUE TITLE
Some characters get stuck in place

### ISSUE THREAD

**Issue by megatog615** [fgsfdsfgs/perfect_dark#7]
Some characters can get stuck in place, repeating an animation loop. This can result in a failed mission if the character is necessary to the objective.

**Comment by Lebon14** [comment]
I've seen the Graslu stream. I think it's those that are scripted that have issues.
Here are those are broken:
1. Datadyne Central Defection, 00 Agent: the guy that you use for the password breaks.
2. Chicago, Stealth, all difficulties: civilians are bound to break.
3. Area 51 Escape, all difficulties: Jonathan breaks.

Funnily enough, all other missions that have somebody following you are fine:
Datadyne Central Extraction, Air Force One Antiterrorism, Crash Site Confrontation, Pelagic II Exploration, Deep Sea Nullify Threat and Attack Ship Covert Assault.

I would check them as well if the three above are broken, just to be sure.

**Comment by Graslu** [comment]
I think it's related to this: #6 
> There is a bug where the collision breaks when you push a pushable object, like a box or a desk. Shooting at them is fine, but as soon as you touch it, stuff like this starts happening. It might be because of that.

I was able to make hostages get stuck on CI Defence by touching the couches in the lobby. On dataDyne Defection, Chicago Stealth and A51 Escape you are more than likely to touch many physic objects that may trigger this.

**Comment by djdv** [comment]
>I think it's related to this: https://github.com/fgsfdsfgs/perfect_dark/issues/6

Adding my anecdote to this.
I broke Jonathan in A51 escape after trying to move the explosive barrels.
Replaying the mission and not doing that worked fine.

**Comment by fgsfdsfgs** [comment]
The bug with the pushables mentioned above should be fixed after the latest commit, so maybe this is fixed as well.

**Comment by Graslu** [comment]
Can confirm both this and #6 seems to be fixed as well. I tested A51 Escape for Jonathan, CI Defence for the hostages, and Villa for the stairs.

**Comment by fgsfdsfgs** [comment]
Cool, closing for now.
