### ISSUE TITLE
Cassandra won't drop her necklace on Attack Ship

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#72]
Self explanatory.

![Base Profile Screenshot 2023 08 21 - 19 21 27 27](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/c64d466a-860f-4576-9194-efd11bb8a6d6)

**Comment by RyanDwyer** [comment]
She only drops it on Perfect Agent. And when she does, the one around her neck remains. This is the same as the N64 version.

**Comment by Graslu** [comment]
Huh, I'm almost certain I was never able to pick it up on my Perfect Agent plays. My bad then.

**Comment by Graslu** [comment]
Yeah can confirm it does work on Perfect Agent. I may be remembering when I first played through it last week.
