### ISSUE TITLE
Slow-mo softlocks mission endings

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#73]
If you trigger a mission ending with slow motion, the screen will flicker until the combat boost depletes or if using the slow-mo cheat you'll simply be softlocked. This does not affect mid mission cutscenes like G5 Building conspiracy, only endings.

Also the footstep glitch seems to still be a thing despite the fix efforts.

https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/f494c181-3b92-453c-b79f-d2ac1ec4a897

https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/c3e4e63f-3437-408a-b72f-e87c68886b76

**Comment by tmyqlfpir** [comment]
>Also the footstep glitch seems to still be a thing despite the fix efforts.

Have you tried this workaround? https://github.com/fgsfdsfgs/perfect_dark/pull/53

**Comment by Graslu** [comment]
> Have you tried this workaround? #53

I just did and it is indeed fixed (The footsteps, not the softlock). Sorry, thought it was merged with the main branch. I was using the latest build in Actions.

**Comment by Graslu** [comment]
Another one - In Area 51 Escape, if you're inside the room with Elvis while the medpack is being administered, the cutscene won't start until the message goes away, giving the same screen flicker as if combat boost was enabled.

Edit: Tested it again, couldn't get it to flicker again even with the message on-screen. Sadly I wasn't able to record it the first time it happened. Could it have been a frame drop that happened just at the time?
