### ISSUE TITLE
Fairly reproducible inventory crash (G5 Building?)

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#74]
I had all guns and infinite ammo no reloads cheats enabled - go to the start menu, inventory, and select anything then press enter to exit. Seems to crash the game randomly, but consistently on G5 Building just before the CamSpy section. Going back to the objectives menu and pressing enter again won't crash.

https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/38e89fb2-5ce7-4a80-92b2-64b4a8ddef7e

**Comment by fgsfdsfgs** [comment]
This might be fixed now? There was an issue related to selecting stuff in the inventory screen that could've theoretically caused crashes.

**Comment by djdv** [comment]
Chiming in.
I was experiencing this on Chicago when selecting the remote mine.
Tried latest (2533a844a72b4de9695f168f8454fbc1b2c5e672) and used the menu exclusively for selecting things and it didn't crash.
