### ISSUE TITLE
Elvis not repeating lines in Pelagic II

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#75]
Known bug from N64, I think it applies to more NPC's other than Elvis but this is the most known:

If you shoot his gun in Pelagic II, he'll say the line over and over again. On the PC port, he'll only play the animation and show the subtitles, but won't say anything.

PC Port:

https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/8ba03c19-0a73-4218-a3f2-97025e3d4942

1964 GEPD:

https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/68a67104-587a-44ed-8bcd-82c7af4bf473

**Comment by Graslu** [comment]
This is probably related to mp3's not repeating properly. This occurs on cutscenes as well if you quit while it plays and restart.

**Comment by tmyqlfpir** [comment]
The current MP3 implementation does not support interruptions by retriggering the same audio.

**Comment by fgsfdsfgs** [comment]
Somehow I didn't realize this would be necessary. Will fix shortly.

**Comment by fgsfdsfgs** [comment]
Should be fixed now.

**Comment by Graslu** [comment]
Can confirm it's fixed.
