### ISSUE TITLE
Character bios ignore automatic aspect ratio.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#80]
It appears to position the models of the characters with 4:3 still in mind, making them appear off center.
![aspectbug1](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/68e23a28-2d95-417a-aa0d-b30efeeb407d)

Enabling 16:9 aspect in the video options fixes it. The model's position will still break if the aspect ratio is changed to anything other than 16:9, however.

![aspectbug2](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/f8a9f530-8611-41d2-95fa-f0c17fe223e6)

**Comment by fgsfdsfgs** [comment]
This is probably fixed now. Same applies to the inventory models.

**Comment by ghost** [comment]
Looks to be rendering correctly now. The text boxes stretch on very large horizontal aspects, but that's outside the scope of this issue.

![bio](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/2ff0820c-31f2-4ad4-bbdf-78d193f4d10f)

**Comment by fgsfdsfgs** [comment]
That's because all 2D elements are still rendered in 4:3.
