### ISSUE TITLE
Night Vision is missing visual effects.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#82]
![night vision](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/96780beb-54b3-4e50-8900-1dcb547f5efc)

The Night Vision on PC (Left) is missing the video effect, along with the green tint. The video effect DOES work on the Camspy but the Night Vision is likely doing it through framebuffer effects so the green tint can also be applied.

**Comment by fgsfdsfgs** [comment]
Motion blur, fisheye on the Camspy and some other framebuffer effects are also missing.

**Comment by fgsfdsfgs** [comment]
Added the colors back, but it's still missing the video effect. On the Camspy that effect is different and done without framebuffer use.

**Comment by eliander30** [comment]
@fgsfdsfgs maybe in the engine library there is a function for add such video effect, i saw now is green but sitll the scan lines missing, need to research about it

**Comment by fgsfdsfgs** [comment]
This has been fixed for a while now.
