### ISSUE TITLE
Mouselook sensitivty on Slayer rockets is extremely low.

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#84]
I have to slide my whole mouse across the desk multiple times to simply rotate it around.

https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/d0b125ff-ec75-4218-9c84-a029ee534d70

**Comment by fgsfdsfgs** [comment]
That was kind of semi-intentional, because otherwise it would be really easy to steer. But I guess I went a bit overboard.

**Comment by Phnod** [comment]
Maybe the rotation can be clamped instead of multiplied?

**Comment by fgsfdsfgs** [comment]
Tried to do that. Tell me if it's still too low.

**Comment by ghost** [comment]
Still feels a bit slower compared to controller, but this is a step forward.

**Comment by Phnod** [comment]
Yeah I agree, this feels great but maybe a little bit more, no more than 2x what it currently is.

**Comment by fgsfdsfgs** [comment]
Alright, increased by 1.5 times. How about now?

**Comment by ghost** [comment]
It feels just about right. Controller is still a tiny bit faster, but this balances it out since mouse aim is far more precise.

**Comment by fgsfdsfgs** [comment]
Alright then.
