### ISSUE TITLE
Shield is now missing after the classic weapons were added.

### ISSUE THREAD

**Issue by Lion-EXE** [fgsfdsfgs/perfect_dark#85]
The shield is no longer selectable/missing in Combat Simulator after the classic weapons were added.

**Comment by fgsfdsfgs** [comment]
I didn't merge that PR. Or were you trying it out?

**Comment by Lion-EXE** [comment]
Ooh, copy. I did not realize it was a different branch, sorry about that. But yeah I was trying it out and I noticed that the shield isn't there.

**Comment by fgsfdsfgs** [comment]
I'll close this here, it's better if discussions of the PR are in the PR itself.

**Comment by tmyqlfpir** [comment]
This should be resolved now.
