### ISSUE TITLE
-ldl is needed to support Sniper Steam Runtime environment

### ISSUE THREAD

**Issue by megatog615** [fgsfdsfgs/perfect_dark#86]
If my method for compiling for Steam Deck is correct(creating a Debian 11 32-bit virtual machine and installing the relevant dev packages; Sniper is based on Debian 11), make will error at the very end complaining about missing libdl. I see that -ldl is already set up to be added for non-x86 systems(aarch) but perhaps it should just be added for everything(*nix, that is).

**Comment by fgsfdsfgs** [comment]
As long as that doesn't cause any issues on other distros, sure.
