### ISSUE TITLE
IR Scanner + Slayer fly-wire turns the screen all red

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#88]
When using the fly-wire rocket on the Slayer, the IR Scanner gets unequipped. This is normal, but the effect won't be disabled and it'll apply to everything, including menus and other levels.

Also unrelated question - should we report all the texture issues we see or are they all expected to be broken due to the mipmap calculation not working?

https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/626daa7a-dbec-481a-b311-73f35cc98987

**Comment by fgsfdsfgs** [comment]
Should be fixed now.

**Comment by Graslu** [comment]
Confirmed fixed
