### ISSUE TITLE
Texture transparency blending is broken on some effects

### ISSUE THREAD

**Issue by megatog615** [fgsfdsfgs/perfect_dark#9]
Effects such as blood spurts, sparks from bullets hitting walls, tracer fire, etc seem to have incorrect alpha blending.

**Comment by fgsfdsfgs** [comment]
This might be at least partially related to the issue which was causing garbage textures, which was fixed just now. Though I suspect some of them will have broken alpha regardless.

**Comment by Graslu** [comment]
Some textures still seem to be broken, weird considering this one wasn't transparent.

![Base Profile Screenshot 2023 08 15 - 17 37 01 19](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/55708a9b-633f-4723-a99b-0fecbb06ceaa)

**Comment by ghost** [comment]
Spark effects render without their alpha blend, which is strange since tracers render fine.

![sparks](https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/d377d6b9-5844-41aa-ad01-d0ea40ac34ae)

EDIT: Rain appears to not render correctly, which may be caused by the same issue.

**Comment by OpenRift412** [comment]
Adding to the list, the impact effects when you hit an enemy seem to lack transparency as well.

**Comment by fgsfdsfgs** [comment]
Closing this in favor of #101.
