### ISSUE TITLE
Credits text renders incorrectly

### ISSUE THREAD

**Issue by iamgreaser** [fgsfdsfgs/perfect_dark#92]
Not quite sure what's going on here, but it seems to be repeating part of the glyph on the left. It looks like it's partially filling a texture buffer, but then rendering parts of it which weren't filled during that step. I suspect this one will be quite a head scratcher.
![image](https://github.com/fgsfdsfgs/perfect_dark/assets/138113/cedd8604-c5ab-41ce-b540-c0eb616b3e46)

I am playing in a maximised window on a 4K monitor, so not sure if that affects it.

(On a side note, after the credits play and the Perfect Dark "screensaver" (I guess that's what it is?) shows up I still can't press a button to advance, but I don't know if that was also in the original version or not.)

**Comment by Graslu** [comment]
> (On a side note, after the credits play and the Perfect Dark "screensaver" (I guess that's what it is?) shows up I still can't press a button to advance, but I don't know if that was also in the original version or not.)

That's normal. You were meant to restart the game. Would be nice to circumvent that, though.

**Comment by iamgreaser** [comment]
Yeah, it was obviously going to be an "I'm not sure if it's a bug, but if not, there would be a good enhancement" thing

**Comment by fgsfdsfgs** [comment]
Texture importing issue. Wrong size calculated in the importer. Happens a lot.
What I'm wondering is did this happen before?

**Comment by MaikelChan** [comment]
At some point it didn't even render. But that was probably fixed after the depth clamp. So maybe it has always been this way. So it's not a rendering issue? Dividing by two the uv coordinates fixes it.

**Comment by fgsfdsfgs** [comment]
No, it is a rendering issue. Meant "texture importer" as in the thing that loads the textures in the renderer.
To clarify, I've noticed that sometimes the height (and rarely width) of textures is calculated there to a value that's exactly 2x the size. Almost as if I'm missing some sort of a mask or divisor that I need to apply to texture size to prevent that from happening.

**Comment by MaikelChan** [comment]
What you mention about twice the size might be the flickering effect that the texts have, which is intended. Texture sizes look fine to me. I'm comparing with GlideN64 and there's this line in the vertex shader that gets applied to these texts:

`if (uTexturePersp == 0 && aModify[2] == 0.0) texCoord *= 0.5;`

That's what makes them look correct.

**Comment by fgsfdsfgs** [comment]
Oh, interesting. `gDPSetTexturePersp` is not handled at all in the renderer, so maybe I should just do that. Thanks.

**Comment by MaikelChan** [comment]
I think I got it working on my end too, but still doing some tests.

**Comment by MaikelChan** [comment]
I submitted a PR: https://github.com/fgsfdsfgs/perfect_dark/pull/94
