### ISSUE TITLE
The new laser doesn't seem to scale properly

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#95]
May just be personal preference, but I feel like it's way bigger than it should be. It seems to flicker at certain distances as well.

![Base Profile Screenshot 2023 08 26 - 14 06 58 30](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/3f28af5b-364b-4657-a889-9faca3aa948f)

**Comment by fgsfdsfgs** [comment]
Well, the size calculation for it hasn't been changed at all. Might be a bit better after the latest commit.

**Comment by Graslu** [comment]
Much better in my opinion. Thank you!

![Base Profile Screenshot 2023 08 26 - 15 27 26 33](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/7cce32eb-7f60-4ad4-9102-7d9036199538)
