### ISSUE TITLE
Villa is now completely broken

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/perfect_dark#97]
<img width="630" alt="broken" src="https://github.com/fgsfdsfgs/perfect_dark/assets/130617241/29853abe-b9c5-4970-a7b5-db2a63d529dc">

This has only occurred on the most recent commits.

**Comment by fgsfdsfgs** [comment]
Should be fixed again now. `GBI_FLOATS` needs some more fixes I guess.

**Comment by ghost** [comment]
Makes sense. Similar issues like this happen in GoldenEye when using sniper zoom on Runway, and that map has a small scale which leads to floating point precision issues. Seems to be working right with it being re-disabled again, so I'll close this issue.
