### ISSUE TITLE
Villa, Air Base and Crash Site have broken bg

### ISSUE THREAD

**Issue by Graslu** [fgsfdsfgs/perfect_dark#99]
Self-explanatory.

![Base Profile Screenshot 2023 08 26 - 15 39 42 47](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/d9764484-247f-4401-8624-288b8c22c383)

![Base Profile Screenshot 2023 08 26 - 15 35 43 18](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/b91f3d8b-10f7-406c-a229-0bd54ad62812)

![Base Profile Screenshot 2023 08 26 - 15 38 26 34](https://github.com/fgsfdsfgs/perfect_dark/assets/34986384/b6568e6a-b453-485e-afeb-1496d0450563)

**Comment by fgsfdsfgs** [comment]
Should be fixed again now. `GBI_FLOATS` needs some more fixes I guess.

**Comment by Graslu** [comment]
Seems correct now.
